### PR TITLE
IN-390 unit test panelapp.py

### PR DESCRIPTION
**Pull request by JasonLing95**
# Update
- unit testing for panelapp.py

```
(env) python manage.py test tests.test_panels_backend.test_management.test_commands.test_panelapp
Found 11 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
........Aborting because API returned a non-200 exit code: 500
...
----------------------------------------------------------------------
Ran 11 tests in 0.075s

OK
Destroying test database for alias 'default'...
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/98)

### CODE REVIEW

**Review by corbin-chris — CHANGES_REQUESTED** [review]
Delaying half of review until I better understand what's going on halfway up

> Reviewed 5 of 11 files at r1, 5 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/98#-:-Nroqrqa2b3rVqqGMAGS:bgty811)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @JasonLing95)

___
*[`tests/test_panels_backend/test_management/test_commands/test_panelapp/mockresponse.py` line 1 at r1](https://reviewable.io/reviews/eastgenomics/eris/98#-Nrog8JY2-4mn9nU8m0l:-Nrog8JY2-4mn9nU8m0m:b-hlyat6) ([raw file](https://github.com/eastgenomics/eris/blob/567af84c91d26e4b0e76ec668f10cc9d6ae7a2f0/tests/test_panels_backend/test_management/test_commands/test_panelapp/mockresponse.py#L1)):*
> ```Python
> class MockResponse:
> ```

Docstring please
___
*[`tests/test_panels_backend/test_management/test_commands/test_panelapp/test_fetch_latest_signed_off_version_based_on_panel_id.py` line 50 at r2](https://reviewable.io/reviews/eastgenomics/eris/98#-NrokgDbBrFwkjU-JDUb:-NrokgDbBrFwkjU-JDUc:b-xncij8) ([raw file](https://github.com/eastgenomics/eris/blob/df8b159c58c124e514049cf1bf5b4f359061096b/tests/test_panels_backend/test_management/test_commands/test_panelapp/test_fetch_latest_signed_off_version_based_on_panel_id.py#L50)):*
> ```Python
>         )
> 
>         self.assertRaises(
> ```

Could you please use self.assertRaisesRegex here, to check that the exception's error message is correct too? The section of code you're testing is showing as 'not covered' in coverage.py and I think it's either because you don't check the error message, or because you don't supply an ID to _fetch_latest_signedoff
It will look something like this:



_Code snippet:_
```Python
expected_error_msg = "Could not fetch...blah blah blah" #replace this with actual expected message
self.assertRaisesRegex(Exception, expected_error_msg):
    _fetch_latest_signed_off_version_based_on_panel_id(1141)
```
___
*[`tests/test_panels_backend/test_management/test_commands/test_panelapp/test_get_latest_version_panel.py` line 31 at r2](https://reviewable.io/reviews/eastgenomics/eris/98#-NronwC_6zmMkYqXgPrB:-NronwC_6zmMkYqXgPrC:by2spg1) ([raw file](https://github.com/eastgenomics/eris/blob/df8b159c58c124e514049cf1bf5b4f359061096b/tests/test_panels_backend/test_management/test_commands/test_panelapp/test_get_latest_version_panel.py#L31)):*
> ```Python
> 
>         with mock.patch(
>             "panels_backend.management.commands.panelapp.get_panel_from_url"
> ```

Do you mean to mock over requests.get instead, and _check_superpanel_status, as these are the functions called within get_latest_version_panel? I think if you mock over the entirety of get_panel_from_url you won't be able to test get_panel_from_url?
The Python script is 'test_get_latest_version_panel' but the test class in it is TestGetPanelFromUrl, which contains the method get_latest_version_panel - could you please do a bit of renaming here as it's confusing

**Review by corbin-chris — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/98)* status: all files reviewed, 2 unresolved discussions (waiting on @JasonLing95)

___
*[`tests/test_panels_backend/test_management/test_commands/test_panelapp/test_get_latest_version_panel.py` line 12 at r2](https://reviewable.io/reviews/eastgenomics/eris/98#-NsDJfuVEsmM5Z7pWWBP:-NsDJfuVEsmM5Z7pWWBQ:btflrbo) ([raw file](https://github.com/eastgenomics/eris/blob/df8b159c58c124e514049cf1bf5b4f359061096b/tests/test_panels_backend/test_management/test_commands/test_panelapp/test_get_latest_version_panel.py#L12)):*
> ```Python
> 
> class TestGetPanelFromUrl(TestCase):
>     def get_latest_version_panel(self):
> ```

The function 'get_latest_version_panel' from panelapp.py is still showing as coverage 0. It isn't actually getting detected as a test on my computer, because the test function doesn't start with 'test_' (see output in the code snippet - it isn't getting detected).
My unittest config only detects test functions if they start with 'test_'.
Does it run on yours if you carry out the below command? If not, please rename the function to start with 'test_'.



_Code snippet:_
```Python
python manage.py test tests.test_panels_backend.test_management.test_commands.test_panelapp.test_get_latest_version_panel
Found 0 test(s).
System check identified no issues (0 silenced).

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```
___
*[`tests/test_panels_backend/test_management/test_commands/test_panelapp/test_get_latest_version_panel.py` line 31 at r2](https://reviewable.io/reviews/eastgenomics/eris/98#-NronwC_6zmMkYqXgPrB:-NsDKympBVojwhrmvR2u:bwh47de) ([raw file](https://github.com/eastgenomics/eris/blob/df8b159c58c124e514049cf1bf5b4f359061096b/tests/test_panels_backend/test_management/test_commands/test_panelapp/test_get_latest_version_panel.py#L31)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

sorry this should be testing get_latest_version_panel. get_panel_from_url need to be mocked because it's called within get_latest_version_panel - else the test will fail depending if the API calling is successful or not
</blockquote></details>

It's clearer now but see above comment.

**Review by corbin-chris — COMMENTED** [review]
Please add a test for 'get_specific_version_panel' too!
It has partial coverage because it is mocked a lot for other tests.
However, its output is never tested directly, so the return line is uncovered:
return panel, is_superpanel

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/98#-:-NsDLrCG2z7_5Vlm16jz:b28w2h4)* status: all files reviewed, 2 unresolved discussions (waiting on @JasonLing95)

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/98)* status: all files reviewed, 2 unresolved discussions (waiting on @corbin-chris)

___
*[`tests/test_panels_backend/test_management/test_commands/test_panelapp/test_get_latest_version_panel.py` line 12 at r2](https://reviewable.io/reviews/eastgenomics/eris/98#-NsDJfuVEsmM5Z7pWWBP:-NsI8TiH6WAEt3fIpMAw:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/df8b159c58c124e514049cf1bf5b4f359061096b/tests/test_panels_backend/test_management/test_commands/test_panelapp/test_get_latest_version_panel.py#L12)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

The function 'get_latest_version_panel' from panelapp.py is still showing as coverage 0. It isn't actually getting detected as a test on my computer, because the test function doesn't start with 'test_' (see output in the code snippet - it isn't getting detected).
My unittest config only detects test functions if they start with 'test_'.
Does it run on yours if you carry out the below command? If not, please rename the function to start with 'test_'.
</blockquote></details>

done
___
*[`tests/test_panels_backend/test_management/test_commands/test_panelapp/test_get_latest_version_panel.py` line 31 at r2](https://reviewable.io/reviews/eastgenomics/eris/98#-NronwC_6zmMkYqXgPrB:-NsI9XFDCml4kPjVP3kd:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/df8b159c58c124e514049cf1bf5b4f359061096b/tests/test_panels_backend/test_management/test_commands/test_panelapp/test_get_latest_version_panel.py#L31)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

It's clearer now but see above comment.
</blockquote></details>

done

**Review by corbin-chris — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/98)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
