### PR TITLE
Review Page

### PR DESCRIPTION
**Pull request by JasonLing95**
# Changes
- update to review page where either automation make changes or user make changes to either new panel / clinical indication / clinical indication-panel logic, it will be presented in this page for Approve / Ignore request

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/16)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/16)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @JasonLing95)

___
*[`web/views.py` line 834 at r1](https://reviewable.io/reviews/eastgenomics/eris/16#-Ncb132y2FwBm2UGShiY:-Ncb132y2FwBm2UGShiZ:b934dhr) ([raw file](https://github.com/eastgenomics/eris/blob/24db4b2b21abcb6aff6c066a35374ba5d00fa2e3/web/views.py#L834)):*
> ```Python
>                 ClinicalIndicationPanelHistory.objects.create(
>                     clinical_indication_panel_id=ci.id,
>                     user="online",
> ```

what is user and why is it hard coded to online?



_Code quote:_
```Python
user="online",
```
___
*[`web/views.py` line 894 at r1](https://reviewable.io/reviews/eastgenomics/eris/16#-Ncb1Ea7Ax59SeRIqOHF:-Ncb1Ea7Ax59SeRIqOHG:b-2331ru) ([raw file](https://github.com/eastgenomics/eris/blob/24db4b2b21abcb6aff6c066a35374ba5d00fa2e3/web/views.py#L894)):*
> ```Python
>             clinical_indication_id = request.POST.get("ci_id")
> 
>             Panel.objects.filter(id=clinical_indication_id).delete()
> ```

is this comment meant to be the same for both? does the 2nd not delete the ci record?



_Code quote:_
```Python
        if action == "approve_ci":
            # this action is purely removing `pending` label
            clinical_indication_id = request.POST.get("ci_id")

            clinical_indication = ClinicalIndication.objects.get(
                id=clinical_indication_id
            )
            clinical_indication.pending = False
            clinical_indication.save()

        elif action == "remove_ci":
            # this action is purely removing `pending` label
            clinical_indication_id = request.POST.get("ci_id")

            Panel.objects.filter(id=clinical_indication_id).delete()
```
___
*[`web/views.py` line 936 at r1](https://reviewable.io/reviews/eastgenomics/eris/16#-Ncb1Rqk6wdrSNEKMpCA:-Ncb1Rqk6wdrSNEKMpCB:b-p0oobx) ([raw file](https://github.com/eastgenomics/eris/blob/24db4b2b21abcb6aff6c066a35374ba5d00fa2e3/web/views.py#L936)):*
> ```Python
>                     user="online",
>                 )
>         elif action == "revert_cip":
> ```

can you add a comment for here pls



_Code quote:_
```Python
   elif action == "revert_cip":
```

**Comment by JasonLing95** [comment]
Screenshot 2023-08-24 at 21 58 25
Screenshot 2023-08-24 at 21 58 38

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/16)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`web/views.py` line 834 at r1](https://reviewable.io/reviews/eastgenomics/eris/16#-Ncb132y2FwBm2UGShiY:-Ncbq0Cq2iQ9ZJXEuGoG:bf0zms0) ([raw file](https://github.com/eastgenomics/eris/blob/24db4b2b21abcb6aff6c066a35374ba5d00fa2e3/web/views.py#L834)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what is user and why is it hard coded to online?
</blockquote></details>

currently we don't have user function to log who is doing what (login function). thus everything done online will just be 'online' to know that action is done through web / front-end
___
*[`web/views.py` line 894 at r1](https://reviewable.io/reviews/eastgenomics/eris/16#-Ncb1Ea7Ax59SeRIqOHF:-Ncbq9iz4b3YnmUUWkgt:bniawqi) ([raw file](https://github.com/eastgenomics/eris/blob/24db4b2b21abcb6aff6c066a35374ba5d00fa2e3/web/views.py#L894)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this comment meant to be the same for both? does the 2nd not delete the ci record?
</blockquote></details>

changed. realized this is what caused the failure in the demo
___
*[`web/views.py` line 936 at r1](https://reviewable.io/reviews/eastgenomics/eris/16#-Ncb1Rqk6wdrSNEKMpCA:-NcbqD_NBraTyy3RYQTQ:b-p1i752) ([raw file](https://github.com/eastgenomics/eris/blob/24db4b2b21abcb6aff6c066a35374ba5d00fa2e3/web/views.py#L936)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you add a comment for here pls
</blockquote></details>

added comment

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
