### PR TITLE
Add superpanels

### PR DESCRIPTION
**Pull request by corbin-chris**
Problem: A small number of panels in PanelApp are super-panels, which are made by collecting a set of standard panels together. An example is panel ID 465, 'Other rare neuromuscular disorders'. The result was Eris was treating super-panels erratically. 
For example, they can contain the same gene more than once, which isn't the case for standard panels, and that can cause a gene to have the incorrect confidence assigned to it within a superpanel. Therefore, changes needed to be made to ensure super-panels are processed correctly.

Changes: Superpanels are now parsed from the JSON with SuperPanelClass, which creates a list of child PanelClass objects to represent the constituent panels. Rather than being stored in the Panel table, superpanels are stored in the SuperPanel database table, and a linking table connects them to their child Panels. Code that handles panels and clinical indication assignment has been changed to extract from the new SuperPanels in addition to the old Panels.

Current state: Unit tests are passing, and '_generate_genepanels' works correctly to output. The original issue no longer occurs, because instead of being linked to SuperPanels directly, Genes are linked to the child Panels instead.

**Unit test passing as of 23rd Oct 2023, 09:14:**

```
(eris_3.10) corbin@starling:~/wc/eris/eris$ python manage.py test
Found 81 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
Inserting test directory data into database... forced: False
R123: No SuperPanel record has panelapp ID 123
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
R234: No SuperPanel record has panelapp ID 123
R234: No SuperPanel record has panelapp ID 234
Data insertion completed.
.Inserting test directory data into database... forced: True
Data insertion completed.
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
R67.1: No SuperPanel record has panelapp ID 123
Data insertion completed.
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
R123: No SuperPanel record has panelapp ID 123
Data insertion completed.
.Inserting test directory data into database... forced: False
R123: No SuperPanel record has panelapp ID 234
Data insertion completed.
.Inserting test directory data into database... forced: False
R123: No SuperPanel record has panelapp ID 123
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
..............None: No Panel record has panelapp ID 999
...........For panel Acute rhabdomyolyosis, skipping gene without HGNC ID: acyl-CoA dehydrogenase family member 9
............................................
----------------------------------------------------------------------
Ran 81 tests in 2.593s

OK
Destroying test database for alias 'default'...

```

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/43)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 17 files at r1, 1 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/43)* status: 6 of 28 files reviewed, 2 unresolved discussions (waiting on @corbin-chris and @JasonLing95)

___
*[`requests_app/management/commands/_insert_ci.py` line 94 at r3](https://reviewable.io/reviews/eastgenomics/eris/43#-NhaGeC26qysBj8fBlD1:-NhaGeC26qysBj8fBlD2:b1xx2u7) ([raw file](https://github.com/eastgenomics/eris/blob/6ec1348389e186ab259233d411f145346d35e536/requests_app/management/commands/_insert_ci.py#L94)):*
> ```Python
>     This function is normally called when there is a new ci-superpanel link when seeding thus
>     the old ci-superpanel link will be flagged to be deactivated / ignored
>     while the new one will be created with pending `True`
> ```

docstring missing inputs
___
*[`requests_app/management/commands/_insert_ci.py` line 150 at r3](https://reviewable.io/reviews/eastgenomics/eris/43#-NhaGhW19rzBz5VNv1sS:-NhaGhW19rzBz5VNv1sT:bmkhw9t) ([raw file](https://github.com/eastgenomics/eris/blob/6ec1348389e186ab259233d411f145346d35e536/requests_app/management/commands/_insert_ci.py#L150)):*
> ```Python
>     Additionally, create a history record.
>     Intended for use when you are making 'best guesses' for links based on
>     previous CI-SuperPanel links.
> ```

stringdoc missing inputs

**Review by jethror1 — COMMENTED** [review]
> Reviewed 4 of 21 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/43)* status: 10 of 28 files reviewed, 2 unresolved discussions (waiting on @corbin-chris and @JasonLing95)

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/43)* status: 10 of 28 files reviewed, 2 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`requests_app/management/commands/_insert_ci.py` line 94 at r3](https://reviewable.io/reviews/eastgenomics/eris/43#-NhaGeC26qysBj8fBlD1:-Nhb533n0GERl2IBXd_7:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/6ec1348389e186ab259233d411f145346d35e536/requests_app/management/commands/_insert_ci.py#L94)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

docstring missing inputs
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_insert_ci.py` line 150 at r3](https://reviewable.io/reviews/eastgenomics/eris/43#-NhaGhW19rzBz5VNv1sS:-Nhb52gR9HgBDiy6IErS:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/6ec1348389e186ab259233d411f145346d35e536/requests_app/management/commands/_insert_ci.py#L150)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

stringdoc missing inputs
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 17 files at r1, 2 of 21 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/43)* status: 16 of 28 files reviewed, 1 unresolved discussion (waiting on @corbin-chris)

___
*[`requests_app/management/commands/panelapp.py` line 168 at r5](https://reviewable.io/reviews/eastgenomics/eris/43#-Ni-B7pJ-NdIU_zI2RWQ:-Ni-B7pJ-NdIU_zI2RWR:b-7ymf5h) ([raw file](https://github.com/eastgenomics/eris/blob/f04ad0fbb463fbdb890e81c19d14c53209776578/requests_app/management/commands/panelapp.py#L168)):*
> ```Python
> 
>     if response.status_code != 200:
>         return None
> ```

how is this handled where it is called? do we need to differentiate return codes besides 200?



_Code quote:_
```Python
    if response.status_code != 200:
        return None
```

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 17 files at r1, 1 of 21 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/43)* status: 18 of 28 files reviewed, 1 unresolved discussion (waiting on @corbin-chris)

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/43)* status: 18 of 28 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`requests_app/management/commands/panelapp.py` line 168 at r5](https://reviewable.io/reviews/eastgenomics/eris/43#-Ni-B7pJ-NdIU_zI2RWQ:-Ni09z7GAooljnDY2YGw:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/f04ad0fbb463fbdb890e81c19d14c53209776578/requests_app/management/commands/panelapp.py#L168)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

how is this handled where it is called? do we need to differentiate return codes besides 200?
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
> Reviewed 9 of 21 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/43)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbin-chris)

**Pull request merged**
