### PR TITLE
In 417 ensure correct output file formats

### PR DESCRIPTION
**Pull request by corbin-chris**
## Changes
- genepanels: Test directory panels now are made with version 1.0 by default, not None
- genepanels: PanelApp external IDs provided for PanelApp-derived IDs
- g2t: Transcript status back to being 'clinical_transcript' or 'not_clinical_transcript' (rather than True or False)

## Example output files
Example genepanels output based on mid-2023 test directory:

R211.1_Inherited polyposis and early onset colorectal cancer - germline testing	Inherited polyposis and early onset colorectal cancer - germline testing_2.0	HGNC:9588	504
R212.1_Peutz Jeghers Syndrome	HGNC:11389_1.0	HGNC:11389	

Example g2t output based on mid-2023 test directory. N.B I have not yet worked on making g2t align with VEP, so expect transcripts that might not be present in the VEP's GFF file:

HGNC:2186       NM_080630.4     not_clinical_transcript
HGNC:2186       NM_001190709.2  not_clinical_transcript
HGNC:2186       NM_001854.4     clinical_transcript
HGNC:2186       NM_080629.3     not_clinical_transcript
HGNC:2187       NM_080680.3     clinical_transcript
HGNC:2187       NM_001163771.2  not_clinical_transcript

## Unit tests
Ran 137 tests in 4.147s

OK
Destroying test database for alias 'default'...

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/81)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/81)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @corbin-chris)

___
*[`panels_backend/management/commands/generate.py` line 218 at r1](https://reviewable.io/reviews/eastgenomics/eris/81#-NpOWzJo7Gqzmvvcki1p:-NpOWzJo7Gqzmvvcki1q:bf4kdon) ([raw file](https://github.com/eastgenomics/eris/blob/04ddce50a9cc430988efc0e1fba0db3794cdf217/panels_backend/management/commands/generate.py#L218)):*
> ```Python
>                     if panel_dict["ci_panel__panel__external_id"]
>                     else ""
>                 )
> ```

can this not just be `panel_dict.get("ci_panel__panel__external_id", "")`



_Code quote:_
```Python
                panelapp_id: str = (
                    panel_dict["ci_panel__panel__external_id"]
                    if panel_dict["ci_panel__panel__external_id"]
                    else ""
                )
```
___
*[`panels_backend/management/commands/generate.py` line 269 at r1](https://reviewable.io/reviews/eastgenomics/eris/81#-NpOX8LmAUbE8T38yYtd:-NpOX8LnDjA16GS3FEJb:b-9chp70) ([raw file](https://github.com/eastgenomics/eris/blob/04ddce50a9cc430988efc0e1fba0db3794cdf217/panels_backend/management/commands/generate.py#L269)):*
> ```Python
>                     if panel_dict["ci_superpanel__superpanel__external_id"]
>                     else ""
>                 )
> ```

as above



_Code quote:_
```Python
                panelapp_id: str = (
                    panel_dict["ci_superpanel__superpanel__external_id"]
                    if panel_dict["ci_superpanel__superpanel__external_id"]
                    else ""
                )
```
___
*[`panels_backend/management/commands/generate.py` line 290 at r1](https://reviewable.io/reviews/eastgenomics/eris/81#-NpOXCwV55qceDYGK1M9:-NpOXCwV55qceDYGK1MA:b-itxah6) ([raw file](https://github.com/eastgenomics/eris/blob/04ddce50a9cc430988efc0e1fba0db3794cdf217/panels_backend/management/commands/generate.py#L290)):*
> ```Python
>                             f"{panel_dict['ci_superpanel__superpanel__panel_name']}_{panel_version}",
>                             hgnc,
>                             f"{panelapp_id}",
> ```

f string seems redundant



_Code quote:_
```Python
f"{panelapp_id}",
```
___
*[`panels_backend/management/commands/generate.py` line 462 at r1](https://reviewable.io/reviews/eastgenomics/eris/81#-NpOXPhC4r-b1NKwcQq8:-NpOXPhC4r-b1NKwcQq9:b51smdc) ([raw file](https://github.com/eastgenomics/eris/blob/04ddce50a9cc430988efc0e1fba0db3794cdf217/panels_backend/management/commands/generate.py#L462)):*
> ```Python
>                 "clinical": "clinical_transcript"
>                 if clinical_status
>                 else "not_clinical_transcript",
> ```

not sure I'm a strong fan of conditionals inside a dict definition, but guess its fine if there's only one, feels not pep8y somehow



_Code quote:_
```Python
                "clinical": "clinical_transcript"
                if clinical_status
                else "not_clinical_transcript",
```

**Review by corbin-chris — COMMENTED** [review]
Ran 137 tests in 4.252s

OK
Destroying test database for alias 'default'...

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/81#-:-NpP539B-IwnDPpwcsmj:bsquri0)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[`panels_backend/management/commands/generate.py` line 218 at r1](https://reviewable.io/reviews/eastgenomics/eris/81#-NpOWzJo7Gqzmvvcki1p:-NpOlHqU3yDvhaIoWhW2:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/04ddce50a9cc430988efc0e1fba0db3794cdf217/panels_backend/management/commands/generate.py#L218)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can this not just be `panel_dict.get("ci_panel__panel__external_id", "")`
</blockquote></details>

Done.
___
*[`panels_backend/management/commands/generate.py` line 269 at r1](https://reviewable.io/reviews/eastgenomics/eris/81#-NpOX8LmAUbE8T38yYtd:-NpOlqrJ8M3xM6NW6lrd:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/04ddce50a9cc430988efc0e1fba0db3794cdf217/panels_backend/management/commands/generate.py#L269)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

as above
</blockquote></details>

Done.
___
*[`panels_backend/management/commands/generate.py` line 290 at r1](https://reviewable.io/reviews/eastgenomics/eris/81#-NpOXCwV55qceDYGK1M9:-NpOm9AjD2s9sBrV0WFb:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/04ddce50a9cc430988efc0e1fba0db3794cdf217/panels_backend/management/commands/generate.py#L290)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

f string seems redundant
</blockquote></details>

Done.
___
*[`panels_backend/management/commands/generate.py` line 462 at r1](https://reviewable.io/reviews/eastgenomics/eris/81#-NpOXPhC4r-b1NKwcQq8:-NpOmsjQ8x7SUDZG7_iC:bhmquhf) ([raw file](https://github.com/eastgenomics/eris/blob/04ddce50a9cc430988efc0e1fba0db3794cdf217/panels_backend/management/commands/generate.py#L462)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

not sure I'm a strong fan of conditionals inside a dict definition, but guess its fine if there's only one, feels not pep8y somehow
</blockquote></details>

Done as I'm not fussed either way

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/81)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @corbin-chris)

___
*[`panels_backend/management/commands/generate.py` line 269 at r1](https://reviewable.io/reviews/eastgenomics/eris/81#-NpOX8LmAUbE8T38yYtd:-NpP6ZED2potO7N4ACN6:b6d1uow) ([raw file](https://github.com/eastgenomics/eris/blob/04ddce50a9cc430988efc0e1fba0db3794cdf217/panels_backend/management/commands/generate.py#L269)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

have you changed this or did reviewable not update correctly?
___
*[`panels_backend/management/commands/generate.py` line 216 at r3](https://reviewable.io/reviews/eastgenomics/eris/81#-NpP6BQm639qD4Te3m3g:-NpP6BQm639qD4Te3m3h:bai9ji0) ([raw file](https://github.com/eastgenomics/eris/blob/12702d01dfad432699b427f8c4325f2ce8017e2a/panels_backend/management/commands/generate.py#L216)):*
this isn't needed since you're providing a default to `get()` so `panelapp_id` will already be an empty string:

```
>>> d={'a':1}
>>> b = d.get('b', '')
>>> b
''
```



_Code quote:_
```Python
                if not panelapp_id:
                    panelapp_id = ""
```
___
*[`panels_backend/management/commands/generate.py` line 228 at r3](https://reviewable.io/reviews/eastgenomics/eris/81#-NpP6UgDCXHuec9gLSYN:-NpP6UgE5YrTp75yamWK:b-9chp70) ([raw file](https://github.com/eastgenomics/eris/blob/12702d01dfad432699b427f8c4325f2ce8017e2a/panels_backend/management/commands/generate.py#L228)):*
> ```Python
>                     )
>                     if not panel_version:
>                         panel_version = ""
> ```

as above



_Code quote:_
```Python
                    if not panel_version:
                        panel_version = ""
```

**Review by corbin-chris — COMMENTED** [review]
Ran 137 tests in 5.412s

OK
Destroying test database for alias 'default'...

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/81#-:-NpPDxn57jz7c0T35d9i:bavdcvf)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`panels_backend/management/commands/generate.py` line 269 at r1](https://reviewable.io/reviews/eastgenomics/eris/81#-NpOX8LmAUbE8T38yYtd:-NpPDu9MEkopaUdn3Js8:bxvg4xh) ([raw file](https://github.com/eastgenomics/eris/blob/04ddce50a9cc430988efc0e1fba0db3794cdf217/panels_backend/management/commands/generate.py#L269)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

have you changed this or did reviewable not update correctly?
</blockquote></details>

Missed it first time, sorry. Done it now, same rationale as previously.
___
*[`panels_backend/management/commands/generate.py` line 216 at r3](https://reviewable.io/reviews/eastgenomics/eris/81#-NpP6BQm639qD4Te3m3g:-NpPC-em3Q5d9jWancxF:bjpa56k) ([raw file](https://github.com/eastgenomics/eris/blob/12702d01dfad432699b427f8c4325f2ce8017e2a/panels_backend/management/commands/generate.py#L216)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this isn't needed since you're providing a default to `get()` so `panelapp_id` will already be an empty string:

```
>>> d={'a':1}
>>> b = d.get('b', '')
>>> b
''
```
</blockquote></details>

The value of "ci_panel__panel__external_id" can be None. This doesn't trigger a key error, so 'get' doesn't fail back to "". I saw this in my unit tests when I made your originally recommended changes.
I need the None to be converted to a blank string for the finally-formatted file - hence the panelapp_id = "" line.
___
*[`panels_backend/management/commands/generate.py` line 228 at r3](https://reviewable.io/reviews/eastgenomics/eris/81#-NpP6UgDCXHuec9gLSYN:-NpPCGq--fhEg5fTcpKh:b-a7ewvn) ([raw file](https://github.com/eastgenomics/eris/blob/12702d01dfad432699b427f8c4325f2ce8017e2a/panels_backend/management/commands/generate.py#L228)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

as above
</blockquote></details>

As explained

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/81)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @corbin-chris)

**Pull request merged**
