### PR TITLE
In 454 unit test panels backend queries

### PR DESCRIPTION
**Pull request by corbin-chris**
Added tests for _queries.py, plus some edit.py functions created by refactoring.

Ran 156 tests in 4.981s

OK
Destroying test database for alias 'default'...

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/90)

### CODE REVIEW

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/90)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @JasonLing95 and @jethror1)

___
*[`panels_backend/management/commands/_queries.py` line 25 at r1](https://reviewable.io/reviews/eastgenomics/eris/90#-Nr5_hrq0n4tyd4_GPuC:-NrAB1En0ZzkeJY3ufh2:b-8nt12e) ([raw file](https://github.com/eastgenomics/eris/blob/974a0b0d7c235100dab471b5dd45477853b94b17/panels_backend/management/commands/_queries.py#L25)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

I think smaller function which do single task is easier to read than a large controller function.
</blockquote></details>

Reviewable isn't actually showing me highlighting, and I'm having to copy-paste from old commits, so bear with me.

I think that this:  

def get\_clinical\_indication\_by\_database\_id(
    id: str,
) -> ClinicalIndication | None:
    """
    Get clinical indication by database id

    :param id: clinical indication database id
    """
    try:
        return ClinicalIndication.objects.get(id=id)
    except ClinicalIndication.DoesNotExist:
        return None

Is not actually easier to read than this, which is already very self-explanatory:  

clinical\_indication = ClinicalIndication.objects.filter(r\_code\_\_iexact=clinical\_indication\_r\_code)

And at least in this example, by changing the code so that I use 'filter' instead of 'get',  that returns an empty list which can be treated as None, removing the need to to the try/except.

In addition, for such a straightforward 'filter', there's less need to test because it's not doing any special logic that isn't already in Django - which we sure hope is tested well.  
The controller is also equally fairly straightforward to unit test, so there's not much change there.

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/90)* status: all files reviewed, 5 unresolved discussions (waiting on @corbin-chris and @jethror1)

___
*[`panels_backend/management/commands/edit.py` line 45 at r1](https://reviewable.io/reviews/eastgenomics/eris/90#-NrAE7m40fvKaxRrXUQO:-NrAE7m40fvKaxRrXUQP:b-gl5u5) ([raw file](https://github.com/eastgenomics/eris/blob/5ed5ec6468bf320fa690a43ad2cadb15cb3fc84e/panels_backend/management/commands/edit.py#L45)):*
> ```Python
>             clinical_indication = clinical_indication[0]
>         except IndexError:
>             raise IndexError("No clinical indication found.")
> ```

could this specify the input within the raised Exception as well 
e.g. No clinical indication found for r code: <r_code>
___
*[`panels_backend/management/commands/edit.py` line 52 at r1](https://reviewable.io/reviews/eastgenomics/eris/90#-NrAEK-sBImNrtDsRjWT:-NrAEK-sBImNrtDsRjWU:b-kobbnw) ([raw file](https://github.com/eastgenomics/eris/blob/5ed5ec6468bf320fa690a43ad2cadb15cb3fc84e/panels_backend/management/commands/edit.py#L52)):*
> ```Python
>         except ClinicalIndication.DoesNotExist:
>             raise ClinicalIndication.DoesNotExist(
>                 f"The clinical indication {ci_id} was not found"
> ```

The clinical indication "id" {ci_id}
___
*[`panels_backend/management/commands/edit.py` line 80 at r1](https://reviewable.io/reviews/eastgenomics/eris/90#-NrAEMpz4M-6BqTmI9ub:-NrAEMpz4M-6BqTmI9uc:b-wz6qeh) ([raw file](https://github.com/eastgenomics/eris/blob/5ed5ec6468bf320fa690a43ad2cadb15cb3fc84e/panels_backend/management/commands/edit.py#L80)):*
> ```Python
>         except Panel.DoesNotExist:
>             raise Panel.DoesNotExist(
>                 f"The panel {panel_id} was not found in the database"
> ```

The panel "id" {panel_id}
___
*[`tests/test_panels_backend/test_management/test_commands/test_edit/test_get_ci_from_r_code_or_id.py` line 66 at r1](https://reviewable.io/reviews/eastgenomics/eris/90#-NrAE_sV2fX1Us95W09S:-NrAE_sV2fX1Us95W09T:bwucguj) ([raw file](https://github.com/eastgenomics/eris/blob/5ed5ec6468bf320fa690a43ad2cadb15cb3fc84e/tests/test_panels_backend/test_management/test_commands/test_edit/test_get_ci_from_r_code_or_id.py#L66)):*
> ```Python
>         user_ci_id = None
>         with self.assertRaisesRegex(
>             IndexError, "No clinical indication " "found"
> ```

weird string separation, I assume this is done by Black?
___
*[`tests/test_panels_backend/test_management/test_commands/test_queries/test_activate_clinical_indication_panel.py` line 46 at r1](https://reviewable.io/reviews/eastgenomics/eris/90#-NrAF8f3AgtkDifwkm9j:-NrAF8f4BWl96bI1n7Df:bebocve) ([raw file](https://github.com/eastgenomics/eris/blob/5ed5ec6468bf320fa690a43ad2cadb15cb3fc84e/tests/test_panels_backend/test_management/test_commands/test_queries/test_activate_clinical_indication_panel.py#L46)):*
> ```Python
>         cips = ClinicalIndicationPanel.objects.all()
>         assert len(cips) == 1
>         self.assertEquals(cips[0], self.ci_panel)
> ```

rather than asserting equal, I think it might be better to assert that the current value is True since that's the intended outcome

**Review by corbin-chris — COMMENTED** [review]
Tests passing, except for one on variant_db which is currently being fixed.
Seeding from CLI worked, so did generating genepanels and g2t files.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/90#-:-NrAR3AoAcxhreKluxNv:bp12xhn)* status: 6 of 10 files reviewed, 5 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`panels_backend/management/commands/edit.py` line 45 at r1](https://reviewable.io/reviews/eastgenomics/eris/90#-NrAE7m40fvKaxRrXUQO:-NrALfXoC0p-TfxvH5BD:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/5ed5ec6468bf320fa690a43ad2cadb15cb3fc84e/panels_backend/management/commands/edit.py#L45)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

could this specify the input within the raised Exception as well 
e.g. No clinical indication found for r code: <r_code>
</blockquote></details>

Done.
___
*[`panels_backend/management/commands/edit.py` line 52 at r1](https://reviewable.io/reviews/eastgenomics/eris/90#-NrAEK-sBImNrtDsRjWT:-NrALky68csi3B3-lxLa:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/5ed5ec6468bf320fa690a43ad2cadb15cb3fc84e/panels_backend/management/commands/edit.py#L52)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

The clinical indication "id" {ci_id}
</blockquote></details>

Done.
___
*[`panels_backend/management/commands/edit.py` line 80 at r1](https://reviewable.io/reviews/eastgenomics/eris/90#-NrAEMpz4M-6BqTmI9ub:-NrALp0s2GVdOd1TSRmH:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/5ed5ec6468bf320fa690a43ad2cadb15cb3fc84e/panels_backend/management/commands/edit.py#L80)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

The panel "id" {panel_id}
</blockquote></details>

Done.
___
*[`tests/test_panels_backend/test_management/test_commands/test_edit/test_get_ci_from_r_code_or_id.py` line 66 at r1](https://reviewable.io/reviews/eastgenomics/eris/90#-NrAE_sV2fX1Us95W09S:-NrAM1Ol7CITNtCbVpHB:b-ocvqfs) ([raw file](https://github.com/eastgenomics/eris/blob/5ed5ec6468bf320fa690a43ad2cadb15cb3fc84e/tests/test_panels_backend/test_management/test_commands/test_edit/test_get_ci_from_r_code_or_id.py#L66)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

weird string separation, I assume this is done by Black?
</blockquote></details>

Done yeah not sure of the cause - either Black or me having a weird brain moment
___
*[`tests/test_panels_backend/test_management/test_commands/test_queries/test_activate_clinical_indication_panel.py` line 46 at r1](https://reviewable.io/reviews/eastgenomics/eris/90#-NrAF8f3AgtkDifwkm9j:-NrAMZo07o91eIjhfOW7:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/5ed5ec6468bf320fa690a43ad2cadb15cb3fc84e/tests/test_panels_backend/test_management/test_commands/test_queries/test_activate_clinical_indication_panel.py#L46)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

rather than asserting equal, I think it might be better to assert that the current value is True since that's the intended outcome
</blockquote></details>

Done.

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/90)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
