### PR TITLE
In 354 td versions

### PR DESCRIPTION
**Pull request by corbin-chris**
This branch addresses ticket IN-354.
Changes:

- Added TestDirectoryRelease, and linking tables to ci-panel/ci-superpanel 
- Refactored test directory-related metadata out of other models, into TestDirectoryRelease
- CiPanels and CiSuperpanels now get linked to all relevant TestDirectoryReleases (some metadata may still change in CiPanels/CiSuperpanels - this continues to be logged in history tables)
- Added unit tests for much of the above

Unit tests for requests_app are completing:

Ran 109 tests in 2.718s

OK
Destroying test database for alias 'default'...

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/50)

### CODE REVIEW

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 19 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/50)* status: 13 of 20 files reviewed, 12 unresolved discussions (waiting on @corbin-chris and @jethror1)

___
*[`requests_app/models.py` line 177 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-Njl87t42SL3xMvdSz3x:-Njl87t42SL3xMvdSz3y:b-4ioq13) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/models.py#L177)):*
> ```Python
> 
>     created = models.DateTimeField(
>         verbose_name="created in Eris",
> ```

this is the created date of the row for model TestDirectoryRelease?
___
*[`requests_app/models.py` line 200 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlTmqX5UVG2hYAPRWP:-NjlTmqX5UVG2hYAPRWQ:bf9yxhp) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/models.py#L200)):*
> ```Python
> 
>     # creation date
>     created = models.DateTimeField(
> ```

this might be a repeat of the above (created in TestDirectoryRelease model)
___
*[`requests_app/management/commands/_insert_ci.py` line 184 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlAwns5T0dNIZqyqYk:-NjlAwns5T0dNIZqyqYl:b5qd3rm) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/management/commands/_insert_ci.py#L184)):*
> ```Python
> 
>     # attribute the pending Ci-Panel link to the current TestDirectoryRelease
>     if ci_panel_instance and td_version:
> ```

the logic here should be linking CI-Panel only when the CI-Panel is created right? because those that are not new-ly created should already have a linked Ci-PanelRelease 
___
*[`requests_app/management/commands/_insert_ci.py` line 232 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlB6GoDIyQNv0hsHp5:-NjlB6GoDIyQNv0hsHp6:b-slcxhx) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/management/commands/_insert_ci.py#L232)):*
> ```Python
>     )
> 
>     if ci_superpanel_instance and td_version:
> ```

same for here. The linking of Ci-SuperPanelTdRelease should only apply for those that are newly created right?
___
*[`requests_app/management/commands/_insert_ci.py` line 447 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlCrZYAckZE_75cMru:-NjlCrZYAckZE_75cMrv:bqr0qjl) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/management/commands/_insert_ci.py#L447)):*
> ```Python
>         if previous_ci_panels:  # in the case where there are old ci-panel
>             for ci_panel in previous_ci_panels:
>                 latest_active_td_release = _get_most_recent_td_release_for_ci_panel(
> ```

the logic here seems wrong. the current seeding should be using whatever td_release it is using for the current seed rather than picking the td_release from the database
___
*[`requests_app/management/commands/_insert_ci.py` line 457 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlCzhw7Vku8acv3r6n:-NjlCzhx3Iy5CjuToO3W:brhan25) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/management/commands/_insert_ci.py#L457)):*
> ```Python
>                 new_clinical_indication_panel = (
>                     provisionally_link_clinical_indication_to_panel(
>                         panel_instance.id, ci.id, td_source, latest_active_td_release
> ```

so if we are seeding td --version 5.1 now this should be 5.1 regardless of what is in the database.
___
*[`requests_app/management/commands/_insert_ci.py` line 532 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlDsK62TEdYGBRA9fw:-NjlDsK62TEdYGBRA9fx:bhn5vu5) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/management/commands/_insert_ci.py#L532)):*
> ```Python
>     the database, or None if there isn't an entry yet
>     """
>     latest_tds = TestDirectoryRelease.objects.all().order_by("-release")
> ```

there's no need to order_by right because the CharField can't be sorted in this case. Instead it might be better to return unique.
___
*[`requests_app/management/commands/_insert_panel.py` line 297 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlHxBs77hpYELT7DJD:-NjlHxBs77hpYELT7DJE:b-govjoe) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/management/commands/_insert_panel.py#L297)):*
> ```Python
>     releases = (
>         CiSuperpanelTdRelease.objects.filter(ci_superpanel=ci_superpanel)
>         .order_by("-td_release")
> ```

does order_by work with CharField? and you could return unique since we don't need duplicates
___
*[`requests_app/management/commands/_insert_panel.py` line 298 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlHqMV6ZgwiC60BzmA:-NjlHqMV6ZgwiC60BzmB:b-kr639i) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/management/commands/_insert_panel.py#L298)):*
> ```Python
>         CiSuperpanelTdRelease.objects.filter(ci_superpanel=ci_superpanel)
>         .order_by("-td_release")
>         .first()
> ```

if there is no return from the .filter the .first will cause an error - will be better to put it after the if statement below
___
*[`requests_app/management/commands/generate.py` line 262 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlIVhv3fWAfPgHd0AI:-NjlIVhv3fWAfPgHd0AJ:b-4oxbbj) ([raw file](https://github.com/eastgenomics/eris/blob/7bb84db33c0f953a1d5647da9a39be18856d1d96/requests_app/management/commands/generate.py#L262)):*
> ```Python
>         print("Creating genepanels file")
> 
>         if not ClinicalIndicationPanel.objects.filter(
> ```

this shouldn't be replaced though, it make sense for genepanel creation to check for ci-panel association in the database as that's where the gene-panel is based on
___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_ci/test_check_td_version_valid.py` line 10 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlIyguABPXCnhVdql4:-NjlIyguABPXCnhVdql5:bssfwp8) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/tests/tests_requests_app/test_management/test_commands/test_insert_ci/test_check_td_version_valid.py#L10)):*
> ```Python
>     Ensure that the test directory version validity checker, passes
>     when the currently-uploaded version of the td is higher than or
>     equal to the most-recent version in the database.
> ```

it shouldn't pass if the current seeded td_version is equal to the version in the db. The default should only allow any version higher than whatever version there is in the db unless `--force` parameter is used
___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_ci/test_flag_panels_removed_from_test_directory.py` line 17 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlJpmJ-xEG4yNxu0Rw:-NjlJpmJ-xEG4yNxu0Rx:bstegv0) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/tests/tests_requests_app/test_management/test_commands/test_insert_ci/test_flag_panels_removed_from_test_directory.py#L17)):*
> ```Python
> class TestPanelsFlaggedWhenNoLongerInTd(TestCase):
>     """
>     CASE: We have list of td-file panels, some are current, some are not.
> ```

I think I get what you mean but could you give an example - I think you mean
e.g.
clinical indication A used to have panel 1 and panel 2 but the recent seed, clinical indication A only have panel 1 thus we expect "clinical indication A - panel 2 link to be flagged (pending True) and current False

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 19 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/50)* status: all files reviewed (commit messages unreviewed), 14 unresolved discussions (waiting on @corbin-chris and @jethror1)

___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_ci/test_make_panels_from_hgncs.py` line 199 at r3](https://reviewable.io/reviews/eastgenomics/eris/50#-Njldqft3fxuF76V7Nym:-Njldqft3fxuF76V7Nyn:b-e5ge5r) ([raw file](https://github.com/eastgenomics/eris/blob/a01c465d407a38645668c0daf0c3b006845475df/tests/tests_requests_app/test_management/test_commands/test_insert_ci/test_make_panels_from_hgncs.py#L199)):*
> ```Python
>         )  # both links should be flagged for review)
> 
>         # TODO: check version link made
> ```

i think this is done below
___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_get_most_recent_td_release_for_ci_panel.py` line 43 at r3](https://reviewable.io/reviews/eastgenomics/eris/50#-NjleEtPAq-gICnD3aGu:-NjleEtPAq-gICnD3aGv:bg8si37) ([raw file](https://github.com/eastgenomics/eris/blob/a01c465d407a38645668c0daf0c3b006845475df/tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_get_most_recent_td_release_for_ci_panel.py#L43)):*
> ```Python
> 
>     def test_single_entry(self):
>         answer = _get_most_recent_td_release_for_ci_panel(self.ci_panel)
> ```

to test this, I think there should be multiple release entries v1.0 and v1.1 and the function should return v1.1

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/50)* status: 18 of 20 files reviewed, 19 unresolved discussions (waiting on @corbin-chris and @JasonLing95)

___
*[`requests_app/models.py` line 177 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-Njl87t42SL3xMvdSz3x:-NjmNqMg5b-2yJeQtjxK:bk4zxkn) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/models.py#L177)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this is the created date of the row for model TestDirectoryRelease?
</blockquote></details>

should this not be a `DateField`? and is this the date of being imported or another date?
___
*[`requests_app/management/commands/_insert_ci.py` line 447 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlCrZYAckZE_75cMru:-NjmSLpBBGp9G5_cajKC:b4c9lyr) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/management/commands/_insert_ci.py#L447)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

the logic here seems wrong. the current seeding should be using whatever td_release it is using for the current seed rather than picking the td_release from the database
</blockquote></details>

:thumbsup: 
___
*[`requests_app/management/commands/_insert_ci.py` line 457 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlCzhw7Vku8acv3r6n:-NjmSOLr5-DIWOFpTaUh:b4c9lyr) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/management/commands/_insert_ci.py#L457)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

so if we are seeding td --version 5.1 now this should be 5.1 regardless of what is in the database.
</blockquote></details>

:thumbsup: 
___
*[`requests_app/management/commands/_insert_ci.py` line 58 at r5](https://reviewable.io/reviews/eastgenomics/eris/50#-NjmOrgb37K92QAyeQf0:-NjmOrgcDq7xPvT9f33M:bmoecd) ([raw file](https://github.com/eastgenomics/eris/blob/e79d6d094088a710b24e1ab56d62ac45beef1deb/requests_app/management/commands/_insert_ci.py#L58)):*
instead of sorting by key and indexing you can use `max()`:
```
>>> l = ['1.0.0', '1.1.0', '1.1.1']
>>> max(l, key=Version)
'1.1.1'
```



_Code quote:_
```Python
        td_releases.sort(key=Version, reverse=True)
        latest_td = str(td_releases[0])
```
___
*[`requests_app/management/commands/_insert_ci.py` line 185 at r5](https://reviewable.io/reviews/eastgenomics/eris/50#-NjmPYzs0HQEZ_Be8B5Z:-NjmPYzs0HQEZ_Be8B5_:b-zd2r2f) ([raw file](https://github.com/eastgenomics/eris/blob/e79d6d094088a710b24e1ab56d62ac45beef1deb/requests_app/management/commands/_insert_ci.py#L185)):*
> ```Python
>     # attribute the pending Ci-Panel link to the current TestDirectoryRelease
>     if ci_panel_instance and td_version:
>         release_link, create = CiPanelTdRelease.objects.get_or_create(
> ```

is this unused and can it be `_` if so?



_Code quote:_
```Python
create
```
___
*[`requests_app/management/commands/_insert_ci.py` line 394 at r5](https://reviewable.io/reviews/eastgenomics/eris/50#-NjmRcPSESDfuEtHjSEn:-NjmRcPSESDfuEtHjSEo:b-6a05d2) ([raw file](https://github.com/eastgenomics/eris/blob/e79d6d094088a710b24e1ab56d62ac45beef1deb/requests_app/management/commands/_insert_ci.py#L394)):*
> ```Python
>     formatted_panel_name = (
>         panel_name[:245] + "TRUNCATED" if len(panel_name) > 255 else panel_name
>     )
> ```

was is the reason for this? afaik the limit for VARCHAR type in postgres is very large and what is used by CharField, if not could also use TextField so we can actually store the full name



_Code quote:_
```Python
    # make the panel name
    # the max length of Panel name is 255
    # if the length of panel_name is more than 255, truncate it to 245
    # and add TRUNCATED (9 chars) which will be 254 chars in total

    panel_name = ",".join(sorted(hgnc_list))
    formatted_panel_name = (
        panel_name[:245] + "TRUNCATED" if len(panel_name) > 255 else panel_name
    )
```
___
*[`requests_app/management/commands/_insert_ci.py` line 538 at r5](https://reviewable.io/reviews/eastgenomics/eris/50#-NjmSZQD7pxn4zEWwgaN:-NjmSZQD7pxn4zEWwgaO:bhi4act) ([raw file](https://github.com/eastgenomics/eris/blob/e79d6d094088a710b24e1ab56d62ac45beef1deb/requests_app/management/commands/_insert_ci.py#L538)):*
> ```Python
>         releases = [v.release for v in latest_tds]
>         releases.sort(key=Version, reverse=True)
>         latest = str(releases[0])
> ```

same as before with using `max()`



_Code quote:_
```Python
        releases = [v.release for v in latest_tds]
        releases.sort(key=Version, reverse=True)
        latest = str(releases[0])
```
___
*[`requests_app/management/commands/_insert_panel.py` line 357 at r5](https://reviewable.io/reviews/eastgenomics/eris/50#-NjmT1O3-YiqXN3u9tGI:-NjmT1O3-YiqXN3u9tGJ:b-wsybi9) ([raw file](https://github.com/eastgenomics/eris/blob/e79d6d094088a710b24e1ab56d62ac45beef1deb/requests_app/management/commands/_insert_panel.py#L357)):*
> ```Python
>         td_releases = [v.td_release.release for v in releases]
>         td_releases.sort(key=Version, reverse=True)
>         latest_td = str(td_releases[0])
> ```

again max



_Code quote:_
```Python
        td_releases.sort(key=Version, reverse=True)
        latest_td = str(td_releases[0])
```

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/50)* status: 12 of 20 files reviewed, 19 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`requests_app/models.py` line 177 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-Njl87t42SL3xMvdSz3x:-NjluWrP3k7mHNuPJnRR:b1knimg) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/models.py#L177)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should this not be a `DateField`? and is this the date of being imported or another date?
</blockquote></details>

DONE  removed it following Jason's next comment
___
*[`requests_app/models.py` line 200 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlTmqX5UVG2hYAPRWP:-Njlv3Vo57X4zekwL7bq:b-4he6vr) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/models.py#L200)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this might be a repeat of the above (created in TestDirectoryRelease model)
</blockquote></details>

Done Yep - removed it now
___
*[`requests_app/management/commands/_insert_ci.py` line 184 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlAwns5T0dNIZqyqYk:-NjmS_JP1KlMse8mpueo:b-tqbblq) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/management/commands/_insert_ci.py#L184)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

the logic here should be linking CI-Panel only when the CI-Panel is created right? because those that are not new-ly created should already have a linked Ci-PanelRelease
</blockquote></details>

Done No. CI-Panels can be linked to multiple releases. So, for example, a not-new CI-Panel (which is currently linked to td_release version 2) could be updated to current=True, pending=True, then linked to td_release version 3.
___
*[`requests_app/management/commands/_insert_ci.py` line 232 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlB6GoDIyQNv0hsHp5:-NjmTKA58QbXTlsrLo55:b-nbu6wf) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/management/commands/_insert_ci.py#L232)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

same for here. The linking of Ci-SuperPanelTdRelease should only apply for those that are newly created right?
</blockquote></details>

Done Same logic as last answer.
___
*[`requests_app/management/commands/_insert_ci.py` line 447 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlCrZYAckZE_75cMru:-NjmcjihBKut7mjCJ-fS:b-896fjb) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/management/commands/_insert_ci.py#L447)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

:thumbsup:
</blockquote></details>

Done 
___
*[`requests_app/management/commands/_insert_ci.py` line 457 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlCzhw7Vku8acv3r6n:-NjmcqFrD33ONFZvjoOY:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/management/commands/_insert_ci.py#L457)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

:thumbsup:
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_insert_ci.py` line 532 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlDsK62TEdYGBRA9fw:-NjmdBWJDSMzpxAgwQXv:bb6un1j) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/management/commands/_insert_ci.py#L532)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

there's no need to order_by right because the CharField can't be sorted in this case. Instead it might be better to return unique.
</blockquote></details>

Done
___
*[`requests_app/management/commands/_insert_ci.py` line 58 at r5](https://reviewable.io/reviews/eastgenomics/eris/50#-NjmOrgb37K92QAyeQf0:-NjmdXxv2jVgUCj9xuw6:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/e79d6d094088a710b24e1ab56d62ac45beef1deb/requests_app/management/commands/_insert_ci.py#L58)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

instead of sorting by key and indexing you can use `max()`:
```
>>> l = ['1.0.0', '1.1.0', '1.1.1']
>>> max(l, key=Version)
'1.1.1'
```
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_insert_ci.py` line 185 at r5](https://reviewable.io/reviews/eastgenomics/eris/50#-NjmPYzs0HQEZ_Be8B5Z:-NjmTFEm8ppbAKdcCi_2:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/e79d6d094088a710b24e1ab56d62ac45beef1deb/requests_app/management/commands/_insert_ci.py#L185)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this unused and can it be `_` if so?
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_insert_ci.py` line 394 at r5](https://reviewable.io/reviews/eastgenomics/eris/50#-NjmRcPSESDfuEtHjSEn:-Njmb478BVNrl6AYoMTa:b-kan08) ([raw file](https://github.com/eastgenomics/eris/blob/e79d6d094088a710b24e1ab56d62ac45beef1deb/requests_app/management/commands/_insert_ci.py#L394)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

was is the reason for this? afaik the limit for VARCHAR type in postgres is very large and what is used by CharField, if not could also use TextField so we can actually store the full name
</blockquote></details>

Done this is getting its own ticket so is out of scope here
___
*[`requests_app/management/commands/_insert_ci.py` line 538 at r5](https://reviewable.io/reviews/eastgenomics/eris/50#-NjmSZQD7pxn4zEWwgaN:-NjmdiT6AzpYc_PVYujo:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/e79d6d094088a710b24e1ab56d62ac45beef1deb/requests_app/management/commands/_insert_ci.py#L538)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

same as before with using `max()`
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_insert_panel.py` line 297 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlHxBs77hpYELT7DJD:-Njmdv1N3Ld-hndtI2uZ:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/management/commands/_insert_panel.py#L297)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

does order_by work with CharField? and you could return unique since we don't need duplicates
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_insert_panel.py` line 298 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlHqMV6ZgwiC60BzmA:-Njme9hw9DevIKJHhuZ8:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/requests_app/management/commands/_insert_panel.py#L298)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

if there is no return from the .filter the .first will cause an error - will be better to put it after the if statement below
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_insert_panel.py` line 357 at r5](https://reviewable.io/reviews/eastgenomics/eris/50#-NjmT1O3-YiqXN3u9tGI:-NjmeFpADzLk9oRHhFVm:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/e79d6d094088a710b24e1ab56d62ac45beef1deb/requests_app/management/commands/_insert_panel.py#L357)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

again max
</blockquote></details>

Done.
___
*[`requests_app/management/commands/generate.py` line 262 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlIVhv3fWAfPgHd0AI:-NjmfCsEBxCjFOziaRgA:bs7wumx) ([raw file](https://github.com/eastgenomics/eris/blob/7bb84db33c0f953a1d5647da9a39be18856d1d96/requests_app/management/commands/generate.py#L262)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this shouldn't be replaced though, it make sense for genepanel creation to check for ci-panel association in the database as that's where the gene-panel is based on
</blockquote></details>

Done. 
___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_ci/test_check_td_version_valid.py` line 10 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlIyguABPXCnhVdql4:-Njmg_ox-UJwRQ9eQwEk:b-fbd7q) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/tests/tests_requests_app/test_management/test_commands/test_insert_ci/test_check_td_version_valid.py#L10)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

it shouldn't pass if the current seeded td_version is equal to the version in the db. The default should only allow any version higher than whatever version there is in the db unless `--force` parameter is used
</blockquote></details>

Done. Class description didn't match actual behaviour.

I do think that equal-versions should be permitted for more-complex actions such as transcript-seeding however. Otherwise, we'd never be able to update the HGNC (which changes often) without waiting for a new MANE release.
___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_ci/test_flag_panels_removed_from_test_directory.py` line 17 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlJpmJ-xEG4yNxu0Rw:-NjmldQa2jU60ZSVLH9m:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/tests/tests_requests_app/test_management/test_commands/test_insert_ci/test_flag_panels_removed_from_test_directory.py#L17)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

I think I get what you mean but could you give an example - I think you mean
e.g.
clinical indication A used to have panel 1 and panel 2 but the recent seed, clinical indication A only have panel 1 thus we expect "clinical indication A - panel 2 link to be flagged (pending True) and current False
</blockquote></details>

Done.
___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_ci/test_make_panels_from_hgncs.py` line 199 at r3](https://reviewable.io/reviews/eastgenomics/eris/50#-Njldqft3fxuF76V7Nym:-Njmj8RHB5dNWTXytRoF:bb6un1j) ([raw file](https://github.com/eastgenomics/eris/blob/a01c465d407a38645668c0daf0c3b006845475df/tests/tests_requests_app/test_management/test_commands/test_insert_ci/test_make_panels_from_hgncs.py#L199)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

i think this is done below
</blockquote></details>

Done
___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_get_most_recent_td_release_for_ci_panel.py` line 43 at r3](https://reviewable.io/reviews/eastgenomics/eris/50#-NjleEtPAq-gICnD3aGu:-Njmjusj3sGdCU1bFiVL:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/a01c465d407a38645668c0daf0c3b006845475df/tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_get_most_recent_td_release_for_ci_panel.py#L43)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

to test this, I think there should be multiple release entries v1.0 and v1.1 and the function should return v1.1
</blockquote></details>

Done.

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/50)* status: all files reviewed, 6 unresolved discussions (waiting on @corbin-chris and @jethror1)

___
*[`requests_app/management/commands/generate.py` line 262 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlIVhv3fWAfPgHd0AI:-NjqejB80Wt2C4GOzglw:bpf3p19) ([raw file](https://github.com/eastgenomics/eris/blob/7bb84db33c0f953a1d5647da9a39be18856d1d96/requests_app/management/commands/generate.py#L262)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the two if statements are returning the same error. combine them both maybe?
___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_ci/test_check_td_version_valid.py` line 10 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlIyguABPXCnhVdql4:-NjqfACTEtOUTRpBZ7K_:b-ag10bg) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/tests/tests_requests_app/test_management/test_commands/test_insert_ci/test_check_td_version_valid.py#L10)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Done. Class description didn't match actual behaviour.

I do think that equal-versions should be permitted for more-complex actions such as transcript-seeding however. Otherwise, we'd never be able to update the HGNC (which changes often) without waiting for a new MANE release.
</blockquote></details>

transcript seeding shouldn't be affected by test directory release version, if it does, we might need to revisit the model interaction because transcript seeding allows updating gene symbols and alias symbols for new HGNCs.

**Review by JasonLing95 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/50)* status: all files reviewed, 5 unresolved discussions (waiting on @jethror1)

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/50)* status: 18 of 20 files reviewed, 5 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`requests_app/management/commands/generate.py` line 262 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlIVhv3fWAfPgHd0AI:-NjqnduU4UkEkpNhsSxu:bm8ici5) ([raw file](https://github.com/eastgenomics/eris/blob/7bb84db33c0f953a1d5647da9a39be18856d1d96/requests_app/management/commands/generate.py#L262)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

the two if statements are returning the same error. combine them both maybe?
</blockquote></details>

They have the same solution but they do have different messages:
"ClinicalIndicationPanel table is empty, run: " vs "Test Directory has not yet been imported, run: "

But I've changed the format of the function now, so that all the errors get gathered and returned in 1 go.
___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_ci/test_check_td_version_valid.py` line 10 at r2](https://reviewable.io/reviews/eastgenomics/eris/50#-NjlIyguABPXCnhVdql4:-NjqlC0wAfMIzfEEt2Au:b-u1utdd) ([raw file](https://github.com/eastgenomics/eris/blob/2a4518a96e471c640a3e54a4684cf1f654fe50a2/tests/tests_requests_app/test_management/test_commands/test_insert_ci/test_check_td_version_valid.py#L10)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

transcript seeding shouldn't be affected by test directory release version, if it does, we might need to revisit the model interaction because transcript seeding allows updating gene symbols and alias symbols for new HGNCs.
</blockquote></details>

Oh no, sorry, I didn't mean that we use test directory version for transcript seeding. I meant that when we do validity-checks for those release versions which are relevant to transcript seeding (HGNC, MANE, HGMD, GFF) we might have to allow same-versions.

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 19 files at r1, 2 of 7 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/50)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbin-chris)

**Pull request merged**
