### PR TITLE
Add custom Gene function

### PR DESCRIPTION
**Pull request by JasonLing95**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/19)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/19)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @JasonLing95)

___
*[`.DS_Store` line 0 at r1](https://reviewable.io/reviews/eastgenomics/eris/19#-Ne2Dhux6C_w4qtGD4EH:-Ne2Dhux6C_w4qtGD4EI:bu701a9) ([raw file](https://github.com/eastgenomics/eris/blob/354467186637d09b1f02b113f8137b8958e61cfd/.DS_Store#L0)):*
can you delete this and add to your .gitignore please
___
*[`web/forms.py` line 53 at r1](https://reviewable.io/reviews/eastgenomics/eris/19#-Ne2E4PR0gC3kLdI8lz5:-Ne2E4PR0gC3kLdI8lz6:bopohkc) ([raw file](https://github.com/eastgenomics/eris/blob/354467186637d09b1f02b113f8137b8958e61cfd/web/forms.py#L53)):*
> ```Python
> 
> 
> class GeneForm(forms.Form):
> ```

what is this form for and to be used for? is it to add new gene symbols in and link to a HGNC ID? does this account for previous / alias symbols etc?
___
*[`web/views.py` line 1296 at r1](https://reviewable.io/reviews/eastgenomics/eris/19#-Ne2FadD-IwAjgaJ3dor:-Ne2FadE74XSm1DIJFBE:b-syr808) ([raw file](https://github.com/eastgenomics/eris/blob/354467186637d09b1f02b113f8137b8958e61cfd/web/views.py#L1296)):*
> ```Python
> 
> 
> def genes(request):
> ```

missing doc string

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/19)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`.DS_Store` line  at r1](https://reviewable.io/reviews/eastgenomics/eris/19#-Ne2Dhux6C_w4qtGD4EH:-Ne2IyS63gS_q5qGPbDI:baynhhg) ([raw file](https://github.com/eastgenomics/eris/blob/354467186637d09b1f02b113f8137b8958e61cfd/.DS_Store#L)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you delete this and add to your .gitignore please
</blockquote></details>

added to gitignore. can't seems to see .DS_Store in my workstation. weird
___
*[`web/forms.py` line 53 at r1](https://reviewable.io/reviews/eastgenomics/eris/19#-Ne2E4PR0gC3kLdI8lz5:-Ne2HseK-h2qnHmvbkFT:bkeg4ua) ([raw file](https://github.com/eastgenomics/eris/blob/354467186637d09b1f02b113f8137b8958e61cfd/web/forms.py#L53)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what is this form for and to be used for? is it to add new gene symbols in and link to a HGNC ID? does this account for previous / alias symbols etc?
</blockquote></details>

yes this one is to add custom gene into the database. was thinking of fetching that from hgnc website instead - no such function exist yet
___
*[`web/views.py` line 1296 at r1](https://reviewable.io/reviews/eastgenomics/eris/19#-Ne2FadD-IwAjgaJ3dor:-Ne2IxChCtfOSB1JN9z0:b-h8vpmk) ([raw file](https://github.com/eastgenomics/eris/blob/354467186637d09b1f02b113f8137b8958e61cfd/web/views.py#L1296)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

missing doc string
</blockquote></details>

added docstring

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/19)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`.DS_Store` line  at r1](https://reviewable.io/reviews/eastgenomics/eris/19#-Ne2Dhux6C_w4qtGD4EH:-Ne2Jkfb68tY72JgU77E:b-tanlzd) ([raw file](https://github.com/eastgenomics/eris/blob/354467186637d09b1f02b113f8137b8958e61cfd/.DS_Store#L)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

added to gitignore. can't seems to see .DS_Store in my workstation. weird
</blockquote></details>

found it, file deleted

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/19)* status: all files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

___
*[`.DS_Store` line  at r1](https://reviewable.io/reviews/eastgenomics/eris/19#-Ne2Dhux6C_w4qtGD4EH:-Ne2PeQ20six-UcxVkoX:b5jzr36) ([raw file](https://github.com/eastgenomics/eris/blob/354467186637d09b1f02b113f8137b8958e61cfd/.DS_Store#L)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

found it, file deleted
</blockquote></details>

its a mac specific file, and in finder etc wouldn't display since its a hidden file

**Pull request merged**
