### PR TITLE
In 432 specify gff at g2t output

### PR DESCRIPTION
**Pull request by corbin-chris**
We need to make sure that when we output g2t files, that we only output transcripts which are compatible with the currently-used version of VEP. We would do this by ensuring that the correct GFF release is used.
Changes:
- In the README - add 'check that your version of the GFF is identical to that used by your pipeline's current version of VEP'
- generate.py: the user provides a GFF release at g2t generation time. Instead of defaulting to the latest GFF, Eris will use that release. If that release isn’t available, it will throw an error

Ran 138 tests in 4.457s

OK
Destroying test database for alias 'default'...

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/84)

### CODE REVIEW

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/84)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @JasonLing95 and @mattgarner)

___
*[`panels_backend/models.py` line 877 at r2](https://reviewable.io/reviews/eastgenomics/eris/84#-NpsotoXBeiX_bA1no91:-Npsr-iS4aSh7Oho0upL:b7ub8cb) ([raw file](https://github.com/eastgenomics/eris/blob/461f053161e3f21cf597806b631c9c45193594cf/panels_backend/models.py#L877)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Why GENCODE version rather than RefSeq? (since it's the RefSeq gff)
</blockquote></details>

It was suggested by Adriana when I discussed it with her last week - but I can use RefSeq if that removes clunkiness. Shall I do that?

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/84)* status: all files reviewed, 7 unresolved discussions (waiting on @corbin-chris and @mattgarner)

___
*[`panels_backend/management/commands/_parse_transcript.py` line 677 at r2](https://reviewable.io/reviews/eastgenomics/eris/84#-NpyXkXm8CrEAcZjLgWp:-NpyXkXm8CrEAcZjLgWq:b-t1uirk) ([raw file](https://github.com/eastgenomics/eris/blob/461f053161e3f21cf597806b631c9c45193594cf/panels_backend/management/commands/_parse_transcript.py#L677)):*
> ```Python
>             # log the error and return the data - it
>             err = f"Versionless transcript in MANE more than once, can't resolve: {tx}"
>             return True, err
> ```

since this is a backend task, i think we can just raise ValueError like the above rather than returning the err message
___
*[`panels_backend/management/commands/_parse_transcript.py` line 704 at r2](https://reviewable.io/reviews/eastgenomics/eris/84#-NpyYVUrDzEtP8eMlf0Z:-NpyYVUrDzEtP8eMlf0_:b4hyd2p) ([raw file](https://github.com/eastgenomics/eris/blob/461f053161e3f21cf597806b631c9c45193594cf/panels_backend/management/commands/_parse_transcript.py#L704)):*
> ```Python
>         mane_plus_clinical_data["clinical"] = True
>         mane_plus_clinical_data["match_base"] = True
>         mane_plus_clinical_data["match_version"] = does_version_match
> ```

could just write True here
___
*[`panels_backend/management/commands/_parse_transcript.py` line 776 at r2](https://reviewable.io/reviews/eastgenomics/eris/84#-NpyYQ4V8YqM77zj34Wy:-NpyYQ4V8YqM77zj34Wz:b-1s1ltu) ([raw file](https://github.com/eastgenomics/eris/blob/461f053161e3f21cf597806b631c9c45193594cf/panels_backend/management/commands/_parse_transcript.py#L776)):*
> ```Python
>                 mane_select_data,
>                 mane_plus_clinical_data,
>                 does_version_match=True,
> ```

if this is always True, this function param is not needed
___
*[`panels_backend/management/commands/generate.py` line 444 at r2](https://reviewable.io/reviews/eastgenomics/eris/84#-Npy_nwp2sBVaUVbKaoT:-Npy_nwp2sBVaUVbKaoU:b-tlz9w5) ([raw file](https://github.com/eastgenomics/eris/blob/461f053161e3f21cf597806b631c9c45193594cf/panels_backend/management/commands/generate.py#L444)):*
> ```Python
> 
>         # We only need to assess those transcripts which are linked to the correct GFF release and reference genome
>         gff_transcripts = TranscriptGffRelease.objects.filter(
> ```

this return a TranscriptGffRelease model object. Does the downstream task work locally by just calling transcript.transcript below?
___
*[`panels_backend/management/commands/generate.py` line 454 at r2](https://reviewable.io/reviews/eastgenomics/eris/84#-Npy_ywe6ljTlYolNx2U:-Npy_ywe6ljTlYolNx2V:b3kqt) ([raw file](https://github.com/eastgenomics/eris/blob/461f053161e3f21cf597806b631c9c45193594cf/panels_backend/management/commands/generate.py#L454)):*
> ```Python
>         for transcript in gff_transcripts:
>             clinical_status = self.get_current_transcript_clinical_status_for_g2t(
>                 transcript.transcript, latest_select, latest_plus_clinical, latest_hgmd
> ```

*
___
*[`panels_backend/management/commands/generate.py` line 459 at r2](https://reviewable.io/reviews/eastgenomics/eris/84#-Npy_UyiEOGWqowL6cyh:-Npy_UyiEOGWqowL6cyi:b5d6kdi) ([raw file](https://github.com/eastgenomics/eris/blob/461f053161e3f21cf597806b631c9c45193594cf/panels_backend/management/commands/generate.py#L459)):*
> ```Python
>                 "clinical_transcript" if clinical_status else "not_clinical_transcript"
>             )
>             displayable_clinical_status = (
> ```

duplicate

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/84)* status: 2 of 8 files reviewed, 7 unresolved discussions (waiting on @JasonLing95 and @mattgarner)

___
*[`panels_backend/models.py` line 877 at r2](https://reviewable.io/reviews/eastgenomics/eris/84#-NpsotoXBeiX_bA1no91:-Npz5k8oD4XXp0GXic65:b-p5kohh) ([raw file](https://github.com/eastgenomics/eris/blob/461f053161e3f21cf597806b631c9c45193594cf/panels_backend/models.py#L877)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

It was suggested by Adriana when I discussed it with her last week - but I can use RefSeq if that removes clunkiness. Shall I do that?
</blockquote></details>

Done switched to Ensembl
___
*[`panels_backend/management/commands/_parse_transcript.py` line 677 at r2](https://reviewable.io/reviews/eastgenomics/eris/84#-NpyXkXm8CrEAcZjLgWp:-Npz6JOM-gS52C0JAwg9:b-704gne) ([raw file](https://github.com/eastgenomics/eris/blob/461f053161e3f21cf597806b631c9c45193594cf/panels_backend/management/commands/_parse_transcript.py#L677)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

since this is a backend task, i think we can just raise ValueError like the above rather than returning the err message
</blockquote></details>

No, because we want the code to continue rather than stop, if the error only affects transcripts which aren't clinically relevant. You probably need to expand the unchanged code to see this.
If the code IS clinically relevant, this is a stop event.
___
*[`panels_backend/management/commands/_parse_transcript.py` line 704 at r2](https://reviewable.io/reviews/eastgenomics/eris/84#-NpyYVUrDzEtP8eMlf0Z:-Npz6mLeCMUDE7GytOs7:bm2t195) ([raw file](https://github.com/eastgenomics/eris/blob/461f053161e3f21cf597806b631c9c45193594cf/panels_backend/management/commands/_parse_transcript.py#L704)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

could just write True here
</blockquote></details>

Expand the code and look at function \_populate\_mane\_dict\_by\_category which I created by refactoring, to reduce repetition, and which gets used twice - once in a scenario with matching versions, once in a scenario where the versions are different. does_version_match is True in one usage and False in the other.
___
*[`panels_backend/management/commands/_parse_transcript.py` line 776 at r2](https://reviewable.io/reviews/eastgenomics/eris/84#-NpyYQ4V8YqM77zj34Wy:-Npz7e_y6rDZqg2LShv6:bpiezwr) ([raw file](https://github.com/eastgenomics/eris/blob/461f053161e3f21cf597806b631c9c45193594cf/panels_backend/management/commands/_parse_transcript.py#L776)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

if this is always True, this function param is not needed
</blockquote></details>

It's False in the section below (you might need to click to expand it)
___
*[`panels_backend/management/commands/generate.py` line 444 at r2](https://reviewable.io/reviews/eastgenomics/eris/84#-Npy_nwp2sBVaUVbKaoT:-Npz95U1-MRMq1jVdF4l:bhzzu2z) ([raw file](https://github.com/eastgenomics/eris/blob/461f053161e3f21cf597806b631c9c45193594cf/panels_backend/management/commands/generate.py#L444)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this return a TranscriptGffRelease model object. Does the downstream task work locally by just calling transcript.transcript below?
</blockquote></details>

Added more details in the docstring below 'for gff_tx in gff_transcripts'
___
*[`panels_backend/management/commands/generate.py` line 454 at r2](https://reviewable.io/reviews/eastgenomics/eris/84#-Npy_ywe6ljTlYolNx2U:-Npz8BSv8K5uUd3gdXYS:b-d3a41w) ([raw file](https://github.com/eastgenomics/eris/blob/461f053161e3f21cf597806b631c9c45193594cf/panels_backend/management/commands/generate.py#L454)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

*
</blockquote></details>

I think you missed a bit here
___
*[`panels_backend/management/commands/generate.py` line 459 at r2](https://reviewable.io/reviews/eastgenomics/eris/84#-Npy_UyiEOGWqowL6cyh:-Npz8CvS5eQXObwFNt6r:b-74bepi) ([raw file](https://github.com/eastgenomics/eris/blob/461f053161e3f21cf597806b631c9c45193594cf/panels_backend/management/commands/generate.py#L459)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

duplicate
</blockquote></details>

Done. Removed it.

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/84)* status: all files reviewed, 9 unresolved discussions (waiting on @corbin-chris, @JasonLing95, and @mattgarner)

___
*[`panels_backend/management/commands/_parse_transcript.py` line 763 at r3](https://reviewable.io/reviews/eastgenomics/eris/84#-Nq21CT31nHRq1Dgfq2-:-Nq21CT31nHRq1Dgfq20:b-3njbzg) ([raw file](https://github.com/eastgenomics/eris/blob/e41b46880d0f0c5e2c31263b04738848ccc6df4d/panels_backend/management/commands/_parse_transcript.py#L763)):*
> ```Python
>     relevant_panels = PanelGene.objects.filter(gene__hgnc_id=hgnc_id)
> 
>     if mane_exact_match:
> ```

there might be a way to reduce the amount of code written here since you basically do the same thing in the if and elif with just the `mane_exact_match` and `mane_base_match` changing
___
*[`panels_backend/management/commands/_parse_transcript.py` line 764 at r3](https://reviewable.io/reviews/eastgenomics/eris/84#-Nq20kTO5V_Y_6DXvnrt:-Nq20kTO5V_Y_6DXvnru:b-tjry17) ([raw file](https://github.com/eastgenomics/eris/blob/e41b46880d0f0c5e2c31263b04738848ccc6df4d/panels_backend/management/commands/_parse_transcript.py#L764)):*
> ```Python
> 
>     if mane_exact_match:
>         error, error_msg = _check_for_more_than_one_tx_match(
> ```

minor thing but I'd rather call `error` something like `multiple_matches` to fit what the name of the function suggests it does

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/84)* status: 7 of 8 files reviewed, 8 unresolved discussions (waiting on @JasonLing95, @mattgarner, and @Yu-jinKim)

___
*[`panels_backend/management/commands/_parse_transcript.py` line 763 at r3](https://reviewable.io/reviews/eastgenomics/eris/84#-Nq21CT31nHRq1Dgfq2-:-Nq2bFPz8WfORPSa9R4W:bjlpv1u) ([raw file](https://github.com/eastgenomics/eris/blob/e41b46880d0f0c5e2c31263b04738848ccc6df4d/panels_backend/management/commands/_parse_transcript.py#L763)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

there might be a way to reduce the amount of code written here since you basically do the same thing in the if and elif with just the `mane_exact_match` and `mane_base_match` changing
</blockquote></details>

Done  I've removed some repetition here (cut ~10 lines)

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/84)* status: all files reviewed, 7 unresolved discussions (waiting on @JasonLing95 and @mattgarner)

**Review by mattgarner — COMMENTED** [review]
> Reviewed 2 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/84)* status: all files reviewed, 6 unresolved discussions (waiting on @JasonLing95)

**Review by mattgarner — APPROVED** [review]
> Reviewed 2 of 8 files at r1, 3 of 6 files at r3.
> Dismissed @JasonLing95 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/84)* status: all files reviewed, 1 unresolved discussion (waiting on @JasonLing95 and @Yu-jinKim)

**Pull request merged**
