### PR TITLE
In 334 335 release info

### PR DESCRIPTION
**Pull request by corbin-chris**
PR to close the following two tickets, and improve auditing in the database:
IN-334 Add HGNC release info to the Eris db (these get linked to affected Genes)
IN-335 Add GFF file release info to the Eris db (these get linked to affected Transcripts)

Changes included:
- Adding release-related user inputs for HGNC and GFF
- Added sanity checkers for releases to enforce correct format, and to stop old releases overwriting newer ones
- HGNC release versions are created in the db, and linked to any Genes that are created/modified by that release (e.g. if an alias symbol changes) or are present in that release
- GFF release versions are created in the db, and linked to any Transcripts that are created by that release, or are present in that release

Unit tests were amended to include these changes.
Unit tests are completing:
----------------------------------------------------------------------
Ran 99 tests in 2.659s

OK

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/47)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/47)* status: 2 of 15 files reviewed, 11 unresolved discussions (waiting on @corbin-chris and @JasonLing95)

___
*[`requests_app/management/commands/_parse_transcript.py` line 201 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Nitwx316ldTH2c4nTY0:-Nitwx316ldTH2c4nTY1:bmo5ktn) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L201)):*
> ```Python
>     # get every HGNC ID in the HGNC file
>     all_hgnc_in_approved = list(set(hgnc_id_to_symbol.keys()))
>     all_hgnc_in_alias = list(set(hgnc_id_to_alias.keys()))
> ```

since these are dictionaries, is the `list(set())` not redundant since keys have to be unique?



_Code quote:_
```Python
    all_hgnc_in_approved = list(set(hgnc_id_to_symbol.keys()))
    all_hgnc_in_alias = list(set(hgnc_id_to_alias.keys()))
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 234 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Nitxyf0EIZOvhBL49uG:-Nitxyf0EIZOvhBL49uH:bkz6xc2) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L234)):*
> ```Python
>         if not symbol_change:
>             if not alias_change:
>                 if gene.hgnc_id in all_hgnc_file_entries:
> ```

this could be written in one as:

`if not symbol_change and not alias_change and gene.hgnc_id in all_hgnc_file_entries:`

maybe could keep the in to a separate statement, but nested if statements where there's no intermediary else statements is redundant



_Code quote:_
```Python
        if not symbol_change:
            if not alias_change:
                if gene.hgnc_id in all_hgnc_file_entries:
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 284 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-NitzMoXBqo3ayWYthNI:-NitzMoXBqo3ayWYthNJ:bpzmjc9) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L284)):*
> ```Python
>     :param hgnc_version: a string describing the in-house-assigned release version of
>     the HGNC file
>     :param user: str, the user's name
> ```

what user is this and why are we storing it? where does it come from?



_Code quote:_
```Python
:param user: str, the user's name
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 494 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Nitzc27BcGZGkTULpEq:-Nitzc285SDu7yjGJaPJ:b-rmwllq) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L494)):*
> ```Python
>         else:
>             # neither transcript nor its GFF link are new - no need to add history info
>             return tx
> ```

can this be `if elif else` to remove the nesting



_Code quote:_
```Python
    if tx_created:
        message = History.tx_gff_release_new()
    else:
        if tx_gff_created:
            message = History.tx_gff_release_present()
        else:
            # neither transcript nor its GFF link are new - no need to add history info
            return tx
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 709 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Nitzl8y4SJ_-SZ9L7gz:-Nitzl8zCfKC3hAajti8:b7n6znh) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L709)):*
> ```Python
>     """
>     Add a release version to the database for the GFF file.
>     Add reference genome information.
> ```

docstring missing params and return



_Code quote:_
```Python
 Add reference genome information.
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 828 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Nitzqwt7Xz0SJmYso-V:-Nitzqwt7Xz0SJmYso-W:b-6fac61) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L828)):*
> ```Python
> def _get_latest_hgnc_release() -> str | None:
>     """
>     Get the latest release in HgncRelease,using LooseVersion because the version formatting
> ```

missing space



_Code quote:_
```Python
,u
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 837 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Niu1tUr9j4VmCxxS3_e:-Niu1tUr9j4VmCxxS3_f:b-va4roz) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L837)):*
> ```Python
>     else:
>         hgnc_releases = [v.hgnc_release for v in hgncs]
>         hgnc_releases.sort(key=LooseVersion, reverse=True)
> ```

consider using packaging.version instead for stricter comparison



_Code quote:_
```Python
LooseVersion
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 858 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Niu23hR97cokqfvNUk5:-Niu23hR97cokqfvNUk6:b-3jh3rd) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L858)):*
> ```Python
>     else:
>         gff_list = [v.gff_release for v in gffs]
>         gff_list.sort(key=LooseVersion, reverse=True)
> ```

 here for packaging



_Code quote:_
```Python
LooseVersion,
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 884 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Niu26KD7rxJjRMptfMu:-Niu26KD7rxJjRMptfMv:b-ytwyha) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L884)):*
> ```Python
>     else:
>         db_results_list = [v.release for v in db_results]
>         db_results_list.sort(key=LooseVersion, reverse=True)
> ```

and again



_Code quote:_
```Python
LooseVersion
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 947 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Niu2ON-CHwTtFO9zow1:-Niu2ON-CHwTtFO9zow2:bbfey6y) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L947)):*
> ```Python
>         for key, value in too_old.items():
>             joined_output_str.append(f"{key} is a lower version than {value}")
>         error = "; ".join(joined_output_str)
> ```

`error = "; ".join([f"{key} is a lower version than {value}" for key, value in too_old.items()])`



_Code quote:_
```Python
        joined_output_str = []
        for key, value in too_old.items():
            joined_output_str.append(f"{key} is a lower version than {value}")
        error = "; ".join(joined_output_str)
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 971 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Niu7ZBA4LgP2ujNzdTK:-Niu7ZBBAZ3UQ_t9Fhux:b-bbyc1) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L971)):*
> ```Python
> ) -> None:
>     """
>     Main function to seed transcripts
> ```

Friday brain given up, Monday brain  I am here



_Code quote:_
```Python
Main function to seed transcripts
```

**Review by corbin-chris — COMMENTED** [review]
Requesting application of Monday brain to rest of code

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/47#-:-Nj8e5Xq6CDEy7OL56lr:bd281mu)* status: 2 of 15 files reviewed, 11 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`requests_app/management/commands/_parse_transcript.py` line 201 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Nitwx316ldTH2c4nTY0:-Nj8Z7E46xkCTk--qFOE:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L201)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

since these are dictionaries, is the `list(set())` not redundant since keys have to be unique?
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_parse_transcript.py` line 234 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Nitxyf0EIZOvhBL49uG:-Nj8ZLB89uN_1IEW37Xu:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L234)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this could be written in one as:

`if not symbol_change and not alias_change and gene.hgnc_id in all_hgnc_file_entries:`

maybe could keep the in to a separate statement, but nested if statements where there's no intermediary else statements is redundant
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_parse_transcript.py` line 284 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-NitzMoXBqo3ayWYthNI:-Nj8ZNI31EmRYp-B2Q4Z:b65tdo3) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L284)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what user is this and why are we storing it? where does it come from?
</blockquote></details>

Eventually we want user to populate from a User database table, for actions such as logging changes to the database. But right now we aren't implementing that for v1 of Eris. The dangling ends are meant to save time later but they confuse people at the moment, so I'm not sure what the best action to take is.
___
*[`requests_app/management/commands/_parse_transcript.py` line 494 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Nitzc27BcGZGkTULpEq:-Nj8_96T04lcsx7kLKQq:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L494)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can this be `if elif else` to remove the nesting
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_parse_transcript.py` line 709 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Nitzl8y4SJ_-SZ9L7gz:-Nj8_WMIAM1sf4TlBdKA:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L709)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

docstring missing params and return
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_parse_transcript.py` line 828 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Nitzqwt7Xz0SJmYso-V:-Nj8_ZjI16jLT46WJpU4:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L828)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

missing space
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_parse_transcript.py` line 858 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Niu23hR97cokqfvNUk5:-Nj8cvxn8qvm9KKbLl6e:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L858)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

here for packaging
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_parse_transcript.py` line 884 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Niu26KD7rxJjRMptfMu:-Nj8cwhi7QB3lW0iuFbO:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L884)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

and again
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_parse_transcript.py` line 947 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Niu2ON-CHwTtFO9zow1:-Nj8e3beEQhvNE3o_VFE:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L947)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`error = "; ".join([f"{key} is a lower version than {value}" for key, value in too_old.items()])`
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_parse_transcript.py` line 971 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-Niu7ZBA4LgP2ujNzdTK:-Nj8e4vTE7jXsv-vRA-A:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L971)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

Friday brain given up, Monday brain  I am here
</blockquote></details>

Done.

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/47)* status: 7 of 15 files reviewed, 16 unresolved discussions (waiting on @corbin-chris and @jethror1)

___
*[`requests_app/management/commands/_parse_transcript.py` line 67 at r2](https://reviewable.io/reviews/eastgenomics/eris/47#-NjByAuUBnK9W9QLiwsb:-NjByAuUBnK9W9QLiwsc:b-9vxmaw) ([raw file](https://github.com/eastgenomics/eris/blob/64b5e3fce4142c56cbdbe5924fd5457eec9076e3/requests_app/management/commands/_parse_transcript.py#L67)):*
> ```Python
>         GeneHgncReleaseHistory.objects.create(
>             gene_hgnc_release=gene_hgnc_release,
>             note=History.gene_hgnc_release_approved_symbol_change(),
> ```

is it possible to record what it change from and to
___
*[`requests_app/management/commands/_parse_transcript.py` line 104 at r2](https://reviewable.io/reviews/eastgenomics/eris/47#-NjByKcbEWV9IOAUSAUf:-NjByKcbEWV9IOAUSAUg:bjxfsbn) ([raw file](https://github.com/eastgenomics/eris/blob/64b5e3fce4142c56cbdbe5924fd5457eec9076e3/requests_app/management/commands/_parse_transcript.py#L104)):*
> ```Python
>         GeneHgncReleaseHistory.objects.create(
>             gene_hgnc_release=gene_hgnc_release,
>             note=History.gene_hgnc_release_alias_symbol_change(),
> ```

same for this one, could we record what it change from and to
___
*[`requests_app/management/commands/_parse_transcript.py` line 178 at r2](https://reviewable.io/reviews/eastgenomics/eris/47#-NjC26SYCL8xeN912Kv0:-NjC26SYCL8xeN912Kv1:b4hd2lv) ([raw file](https://github.com/eastgenomics/eris/blob/64b5e3fce4142c56cbdbe5924fd5457eec9076e3/requests_app/management/commands/_parse_transcript.py#L178)):*
> ```Python
> 
> def _make_hgnc_gene_sets(
>     hgnc_id_to_symbol: dict[str:str], hgnc_id_to_alias: dict[str:str]
> ```

hgnc_id_to_alias is a dict[str:list] right?
___
*[`requests_app/management/commands/_parse_transcript.py` line 241 at r2](https://reviewable.io/reviews/eastgenomics/eris/47#-NjC3nmr-j84dpiC5i_-:-NjC3nmr-j84dpiC5i_0:b-gqvry7) ([raw file](https://github.com/eastgenomics/eris/blob/64b5e3fce4142c56cbdbe5924fd5457eec9076e3/requests_app/management/commands/_parse_transcript.py#L241)):*
> ```Python
>             "hgnc_id": hgnc_id,
>             "symbol": (
>                 hgnc_id_to_symbol[hgnc_id] if hgnc_id_to_symbol[hgnc_id] else None
> ```

won't his throw an error if hgnc_id is not in hgnc_id_to_symbol since hgnc_id_to_symbol is a dictionary, will be better to do hgnc_id_to_symbol.get(hgnc_id) which will return None if hgnc_id is not in hgnc_id_to_symbol which is False as boolean
___
*[`requests_app/management/commands/_parse_transcript.py` line 261 at r2](https://reviewable.io/reviews/eastgenomics/eris/47#-NjC2Xv55BNstKPDbodS:-NjC2Xv55BNstKPDbodT:bdv6q8) ([raw file](https://github.com/eastgenomics/eris/blob/64b5e3fce4142c56cbdbe5924fd5457eec9076e3/requests_app/management/commands/_parse_transcript.py#L261)):*
> ```Python
>     if the input was blank/just np.nan values.
>     """
>     if start_alias:
> ```

this can be combined into one if statement
`if start_alias and not pd.isna(start_alias).all()`

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/47)* status: 7 of 15 files reviewed, 17 unresolved discussions (waiting on @corbin-chris and @jethror1)

___
*[`requests_app/management/commands/_parse_transcript.py` line 312 at r2](https://reviewable.io/reviews/eastgenomics/eris/47#-NjC4LEA2QKNP_8PWCLs:-NjC4LEA2QKNP_8PWCLt:b1rpr0c) ([raw file](https://github.com/eastgenomics/eris/blob/64b5e3fce4142c56cbdbe5924fd5457eec9076e3/requests_app/management/commands/_parse_transcript.py#L312)):*
> ```Python
>         _update_existing_gene_metadata_symbol_in_db(symbol_changed, hgnc_release, user)
>         _update_existing_gene_metadata_aliases_in_db(alias_changed, hgnc_release, user)
>         _link_unchanged_genes_to_new_release(unchanged_genes, hgnc_release, user)
> ```

what about the link between the unchanged gene with the old release? will those be "un-linked"?

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/47)* status: 7 of 15 files reviewed, 18 unresolved discussions (waiting on @corbin-chris and @jethror1)

___
*[`requests_app/management/commands/_parse_transcript.py` line 837 at r2](https://reviewable.io/reviews/eastgenomics/eris/47#-NjC4wAF8yQXaf33B9_y:-NjC4wAF8yQXaf33B9_z:braf1g2) ([raw file](https://github.com/eastgenomics/eris/blob/64b5e3fce4142c56cbdbe5924fd5457eec9076e3/requests_app/management/commands/_parse_transcript.py#L837)):*
> ```Python
>     else:
>         hgnc_releases = [v.hgnc_release for v in hgncs]
>         hgnc_releases.sort(key=Version, reverse=True)
> ```

if this is order_by in django query, why are we sorting it again? If the release version is stored using sortable_version in util.py, you could just get the first result since the value is query-able / sortable using django orm

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 15 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/47)* status: 14 of 15 files reviewed, 20 unresolved discussions (waiting on @corbin-chris and @jethror1)

___
*[`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_update_existing_gene_metadata_in_db.py` line 145 at r2](https://reviewable.io/reviews/eastgenomics/eris/47#-NjC8PUI-Giy5MKOm8kK:-NjC8PUI-Giy5MKOm8kL:bhqerce) ([raw file](https://github.com/eastgenomics/eris/blob/c26464abcee8a5643ac13f7576a721c8be4bf0ef/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_update_existing_gene_metadata_in_db.py#L145)):*
> ```Python
>         assert gene_db[0].alias_symbols == ",".join(made_up_aliases)
> 
>     def test_alias_now_numpy_na(self):
> ```

is this scenario not going to happen or why is it removed? I thought resolve_alias function will return None in this scenario
___
*[`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_update_existing_gene_metadata_in_db.py` line 161 at r2](https://reviewable.io/reviews/eastgenomics/eris/47#-NjC8duW-XmgZAju4MMm:-NjC8duW-XmgZAju4MMn:b-e9qcet) ([raw file](https://github.com/eastgenomics/eris/blob/c26464abcee8a5643ac13f7576a721c8be4bf0ef/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_update_existing_gene_metadata_in_db.py#L161)):*
> ```Python
>         assert gene_db[0].alias_symbols == self.FAM234A.alias_symbols
> 
>     def test_alias_list_empty(self):
> ```

same goes with this scenario, is it not going to happen?

**Review by JasonLing95 — COMMENTED** [review]
> Reviewed 1 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/47)* status: all files reviewed, 20 unresolved discussions (waiting on @corbin-chris and @jethror1)

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/47)* status: all files reviewed, 11 unresolved discussions (waiting on @corbin-chris)

___
*[`requests_app/management/commands/_parse_transcript.py` line 284 at r1](https://reviewable.io/reviews/eastgenomics/eris/47#-NitzMoXBqo3ayWYthNI:-NjC8Ph4DbzCPeO3kAX0:bkm9yl2) ([raw file](https://github.com/eastgenomics/eris/blob/92a47d3972c216c51dee773b20c4898909c45909/requests_app/management/commands/_parse_transcript.py#L284)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Eventually we want user to populate from a User database table, for actions such as logging changes to the database. But right now we aren't implementing that for v1 of Eris. The dangling ends are meant to save time later but they confuse people at the moment, so I'm not sure what the best action to take is.
</blockquote></details>

ah okay, that makes sense
___
*[`requests_app/management/commands/_parse_transcript.py` line 1005 at r2](https://reviewable.io/reviews/eastgenomics/eris/47#-NjC8fIP9EaCwsBhY96a:-NjC8fIP9EaCwsBhY96b:bto69na) ([raw file](https://github.com/eastgenomics/eris/blob/64b5e3fce4142c56cbdbe5924fd5457eec9076e3/requests_app/management/commands/_parse_transcript.py#L1005)):*
> ```Python
> 
>     # user - replace this with something sensible one day
>     user = "transcripts_test_user"
> ```

can you add TODO's where user is referenced to make it easier to catch in the next version? also maybe set the user to something like `init_v1_user` if this is actually getting written into the db so long term we don't have a 'test' user saved against records



_Code quote:_
```Python
    # user - replace this with something sensible one day
    user = "transcripts_test_user"
```

**Review by jethror1 — APPROVED** [review]
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/47)* status: 12 of 16 files reviewed, 9 unresolved discussions (waiting on @JasonLing95)

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/47)* status: all files reviewed, 2 unresolved discussions (waiting on @corbin-chris)

___
*[`requests_app/management/commands/_parse_transcript.py` line 178 at r2](https://reviewable.io/reviews/eastgenomics/eris/47#-NjC26SYCL8xeN912Kv0:-NjHSUTaDw46qhtb5Vmq:bh8wury) ([raw file](https://github.com/eastgenomics/eris/blob/64b5e3fce4142c56cbdbe5924fd5457eec9076e3/requests_app/management/commands/_parse_transcript.py#L178)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

No, _make_hgnc_gene_sets() calls _resolve_alias() to join them into a comma-separated string.
</blockquote></details>

but when it comes into this function, it's a dict[str, list]? _resolve_alias() is called later on within this function
___
*[`requests_app/management/commands/_parse_transcript.py` line 57 at r4](https://reviewable.io/reviews/eastgenomics/eris/47#-NjHUZ5JBBWoqMPulVtb:-NjHUZ5JBBWoqMPulVtc:b-fgcfaa) ([raw file](https://github.com/eastgenomics/eris/blob/75fc03e52df739275729811697478b8216cac03b/requests_app/management/commands/_parse_transcript.py#L57)):*
> ```Python
>     now = datetime.datetime.now().strftime("%H:%M:%S")
>     print(f"Start gene symbol bulk update: {now}")
>     Gene.objects.bulk_update(gene_symbol_updates, ["gene_symbol"])
> ```

is there a possibility that the bulk_update failed to update the metadata but we record the change in GeneHgncReleaseHistory below? how can that be prevented here?
___
*[`requests_app/management/commands/_parse_transcript.py` line 98 at r4](https://reviewable.io/reviews/eastgenomics/eris/47#-NjHUiP0A6jDSQv62-Pm:-NjHUiP0A6jDSQv62-Pn:bu5z3hp) ([raw file](https://github.com/eastgenomics/eris/blob/75fc03e52df739275729811697478b8216cac03b/requests_app/management/commands/_parse_transcript.py#L98)):*
> ```Python
>     now = datetime.datetime.now().strftime("%H:%M:%S")
>     print(f"Start gene alias bulk update: {now}")
>     Gene.objects.bulk_update(gene_alias_updates, ["alias_symbols"])
> ```

same for this one: is there a possibility that the bulk_update failed to update the metadata but we record the change in GeneHgncReleaseHistory below? how can that be prevented here?

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/47)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @JasonLing95 and @transaction)

___
*[`requests_app/management/commands/_parse_transcript.py` line 178 at r2](https://reviewable.io/reviews/eastgenomics/eris/47#-NjC26SYCL8xeN912Kv0:-NjI_dyMAgve10y8NDMl:bb6un1j) ([raw file](https://github.com/eastgenomics/eris/blob/64b5e3fce4142c56cbdbe5924fd5457eec9076e3/requests_app/management/commands/_parse_transcript.py#L178)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

but when it comes into this function, it's a dict[str, list]? _resolve_alias() is called later on within this function
</blockquote></details>

Done
___
*[`requests_app/management/commands/_parse_transcript.py` line 57 at r4](https://reviewable.io/reviews/eastgenomics/eris/47#-NjHUZ5JBBWoqMPulVtb:-NjIXmGS0gemTVD4G73m:b-9lqgfb) ([raw file](https://github.com/eastgenomics/eris/blob/75fc03e52df739275729811697478b8216cac03b/requests_app/management/commands/_parse_transcript.py#L57)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

is there a possibility that the bulk_update failed to update the metadata but we record the change in GeneHgncReleaseHistory below? how can that be prevented here?
</blockquote></details>

bulk_update and the release and history-creating calls, are in a function which is called inside a 'with transaction.atomic()' block. That means that if there's a database failure inside the block, it should cause all changes to 'roll back' (undo), including the bulk_update line. It also controls some locking behaviour of the database.

If the block completes successfully - it'll enter the @transaction.atomic block that wraps the function calling THAT, 'seed\_transcripts'. So, seed_transcripts is supposed to be 'all or nothing', if it fails partway through, everything is undone.



_Code snippet:_
```Python
with transaction.atomic():
    \_update\_existing\_gene\_metadata\_symbol\_in\_db(symbol\_changed, hgnc\_release, user)
    \_update\_existing\_gene\_metadata\_aliases\_in\_db(alias\_changed, hgnc\_release, user)
    \_link\_unchanged\_genes\_to\_new\_release(unchanged\_genes, hgnc\_release, user)
    \_add\_new\_genes\_to\_db(new\_genes, hgnc\_release, user)
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 98 at r4](https://reviewable.io/reviews/eastgenomics/eris/47#-NjHUiP0A6jDSQv62-Pm:-NjI_8Ar9sAzXJKrueq5:b-kegvk) ([raw file](https://github.com/eastgenomics/eris/blob/75fc03e52df739275729811697478b8216cac03b/requests_app/management/commands/_parse_transcript.py#L98)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

same for this one: is there a possibility that the bulk_update failed to update the metadata but we record the change in GeneHgncReleaseHistory below? how can that be prevented here?
</blockquote></details>

Similar explanation as above

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/47)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbin-chris)

**Pull request merged**
