### PR TITLE
In 484 unit tests db seeding

### PR DESCRIPTION
**Pull request by corbin-chris**
I added more unit testing to cover a few gaps in '_insert_ci.py', '_insert_panel.py' and '_parse_transcript.py'.
Unit tests passed: https://github.com/eastgenomics/eris/actions/runs/8159627258
For overall coverages, see the 'Run Tests' tab on this page: https://github.com/eastgenomics/eris/actions/runs/8159627258/job/22304358390

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/103)

### CODE REVIEW

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/103)* status: 12 of 15 files reviewed, 4 unresolved discussions (waiting on @corbin-chris)

___
*[`panels_backend/management/commands/_parse_transcript.py` line 695 at r1](https://reviewable.io/reviews/eastgenomics/eris/103#-NsJFcs83uN__Kzf0_Gx:-NsJFcs83uN__Kzf0_Gy:bz4k8j7) ([raw file](https://github.com/eastgenomics/eris/blob/c51d0a01a767a8753f18eeaecc5d8efbbacd68cc/panels_backend/management/commands/_parse_transcript.py#L695)):*
> ```Python
> 
> def _check_if_tx_genes_are_relevant_to_panels(
>     transcript_matches: list[dict[str:str]], tx: str
> ```

what's the structure of transcript_matches?
___
*[`panels_backend/management/commands/_parse_transcript.py` line 821 at r1](https://reviewable.io/reviews/eastgenomics/eris/103#-NsJFmzkD2LddRcVaZiH:-NsJFmzkD2LddRcVaZiI:b-maykd1) ([raw file](https://github.com/eastgenomics/eris/blob/c51d0a01a767a8753f18eeaecc5d8efbbacd68cc/panels_backend/management/commands/_parse_transcript.py#L821)):*
> ```Python
>     if mane_exact_match or mane_base_match:
>         # work out whether or not the transcript exists multiple times in MANE
>         if len(transcript_list) > 1:
> ```

sorry I forgot, what's the structure of transcript_list?
___
*[`tests/test_panels_backend/test_management/test_commands/test_insert_ci/test_insert_test_directory_data.py` line 223 at r1](https://reviewable.io/reviews/eastgenomics/eris/103#-NsJGSloATcRjSAgsXbi:-NsJGSloATcRjSAgsXbj:b-t55ig2) ([raw file](https://github.com/eastgenomics/eris/blob/c51d0a01a767a8753f18eeaecc5d8efbbacd68cc/tests/test_panels_backend/test_management/test_commands/test_insert_ci/test_insert_test_directory_data.py#L223)):*
> ```Python
>     def test_make_clinical_indication_with_no_panel_links(self):
>         """
>         We create a clinical indication which has no currently linked panels
> ```

this docstring is not clear
___
*[`tests/test_panels_backend/test_management/test_commands/test_insert_panel/test_disable_custom_hgnc_panels.py` line 71 at r1](https://reviewable.io/reviews/eastgenomics/eris/103#-NsJMChZ9F_YGESbj56r:-NsJMChZ9F_YGESbj56s:b-le6qif) ([raw file](https://github.com/eastgenomics/eris/blob/c51d0a01a767a8753f18eeaecc5d8efbbacd68cc/tests/test_panels_backend/test_management/test_commands/test_insert_panel/test_disable_custom_hgnc_panels.py#L71)):*
> ```Python
>             panel_version=None,
>             test_directory=True,
>             custom=True,
> ```

probably doesn't matter but in this case, custom is False

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/103)* status: 11 of 18 files reviewed, 4 unresolved discussions (waiting on @JasonLing95)

___
*[`panels_backend/management/commands/_parse_transcript.py` line 695 at r1](https://reviewable.io/reviews/eastgenomics/eris/103#-NsJFcs83uN__Kzf0_Gx:-NsJctln7ovY02I2SoIy:bkxub42) ([raw file](https://github.com/eastgenomics/eris/blob/b7d54d1d06fc7bbd4102770d7cd7a390065ea427/panels_backend/management/commands/_parse_transcript.py#L695)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

what's the structure of transcript_matches?
</blockquote></details>

It's list[dict[str:str]] and I've added more description to the docstring 
___
*[`panels_backend/management/commands/_parse_transcript.py` line 821 at r1](https://reviewable.io/reviews/eastgenomics/eris/103#-NsJFmzkD2LddRcVaZiH:-NsJdEKl8ub249XeXv_E:bn84euu) ([raw file](https://github.com/eastgenomics/eris/blob/b7d54d1d06fc7bbd4102770d7cd7a390065ea427/panels_backend/management/commands/_parse_transcript.py#L821)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

sorry I forgot, what's the structure of transcript_list?
</blockquote></details>

They're the same as mane_exact_match and mane_base_match. So, they're the same as mane_data.
Added more info to the mane_data docstring.
___
*[`tests/test_panels_backend/test_management/test_commands/test_insert_ci/test_insert_test_directory_data.py` line 223 at r1](https://reviewable.io/reviews/eastgenomics/eris/103#-NsJGSloATcRjSAgsXbi:-NsJem30Er8NjP5Z2Dgk:b-4sq4i2) ([raw file](https://github.com/eastgenomics/eris/blob/b7d54d1d06fc7bbd4102770d7cd7a390065ea427/tests/test_panels_backend/test_management/test_commands/test_insert_ci/test_insert_test_directory_data.py#L223)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this docstring is not clear
</blockquote></details>

Added more detail - I wrote this test to cover a 'continue' line for clinical indications which have an empty 'panel' list in the test directory JSON file. I didn't succeed the first time, but I've made another change and it's covered now.
___
*[`tests/test_panels_backend/test_management/test_commands/test_insert_panel/test_disable_custom_hgnc_panels.py` line 71 at r1](https://reviewable.io/reviews/eastgenomics/eris/103#-NsJMChZ9F_YGESbj56r:-NsJgknG34ei2FBQNVt9:bk9u5pe) ([raw file](https://github.com/eastgenomics/eris/blob/b7d54d1d06fc7bbd4102770d7cd7a390065ea427/tests/test_panels_backend/test_management/test_commands/test_insert_panel/test_disable_custom_hgnc_panels.py#L71)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

probably doesn't matter but in this case, custom is False
</blockquote></details>

Changed it - are there 3 types of panel then, 'PanelApp' 'Test Directory' and 'custom'?

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/103)* status: 11 of 18 files reviewed, 5 unresolved discussions (waiting on @corbin-chris)

___
*[`panels_backend/management/commands/_parse_transcript.py` line 733 at r2](https://reviewable.io/reviews/eastgenomics/eris/103#-NsN8QoLDTDazG0m7uVS:-NsN8QoLDTDazG0m7uVT:bfpaiz) ([raw file](https://github.com/eastgenomics/eris/blob/0cc722200380249afdf151737cb577e4f8b17a49/panels_backend/management/commands/_parse_transcript.py#L733)):*
> ```Python
>         # log the error and return the data - it
>         err = f"Versionless transcript in MANE more than once, can't resolve: {tx}"
>         return True, err
> ```

felt like the boolean could be defined outside of the function and this function could focus solely on raising ValueError
___
*[`panels_backend/management/commands/_parse_transcript.py` line 825 at r2](https://reviewable.io/reviews/eastgenomics/eris/103#-NsN8_l00rP7puFKYZza:-NsN8_l00rP7puFKYZzb:b9f8l1l) ([raw file](https://github.com/eastgenomics/eris/blob/0cc722200380249afdf151737cb577e4f8b17a49/panels_backend/management/commands/_parse_transcript.py#L825)):*
> ```Python
>     if mane_exact_match or mane_base_match:
>         # work out whether or not the transcript exists multiple times in MANE
>         if len(transcript_list) > 1:
> ```

since the if statement here determine the value of multiple_matches, it seems more appropriate to define it here than returned by the function _check_if_tx_genes_are_relevant_to_panels
___
*[`panels_backend/management/commands/_parse_transcript.py` line 828 at r2](https://reviewable.io/reviews/eastgenomics/eris/103#-NsN7yK71Y9YzUP5yObH:-NsN7yK71Y9YzUP5yObI:b-auzm70) ([raw file](https://github.com/eastgenomics/eris/blob/0cc722200380249afdf151737cb577e4f8b17a49/panels_backend/management/commands/_parse_transcript.py#L828)):*
> ```Python
>             (
>                 multiple_matches,
>                 error_msg,
> ```

I felt like the returned error message isn't really dealt with downstream or am I wrong

**Review by corbin-chris — COMMENTED** [review]
Output files still being generated and look normal

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/103#-:-NsNJETy-jN1cN6VqIqS:bt5cb1u)* status: 11 of 18 files reviewed, 5 unresolved discussions (waiting on @JasonLing95)

___
*[`panels_backend/management/commands/_parse_transcript.py` line 733 at r2](https://reviewable.io/reviews/eastgenomics/eris/103#-NsN8QoLDTDazG0m7uVS:-NsNGyp8-Vy9d_8Sa-Yt:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/0cc722200380249afdf151737cb577e4f8b17a49/panels_backend/management/commands/_parse_transcript.py#L733)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

felt like the boolean could be defined outside of the function and this function could focus solely on raising ValueError
</blockquote></details>

Done.
___
*[`panels_backend/management/commands/_parse_transcript.py` line 825 at r2](https://reviewable.io/reviews/eastgenomics/eris/103#-NsN8_l00rP7puFKYZza:-NsNHDySDzGaGDqZtnc0:b-ebg03r) ([raw file](https://github.com/eastgenomics/eris/blob/0cc722200380249afdf151737cb577e4f8b17a49/panels_backend/management/commands/_parse_transcript.py#L825)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

since the if statement here determine the value of multiple_matches, it seems more appropriate to define it here than returned by the function _check_if_tx_genes_are_relevant_to_panels
</blockquote></details>

I don't understand what you mean, sorry.
I've already refactored this code a lot - I'm reluctant to refactor further unless there's a lot of redundancy that can be cut out, especially if dev is going to be paused anyway.
___
*[`panels_backend/management/commands/_parse_transcript.py` line 828 at r2](https://reviewable.io/reviews/eastgenomics/eris/103#-NsN7yK71Y9YzUP5yObH:-NsNGTmE9z_pBnWQPXya:bydg4v9) ([raw file](https://github.com/eastgenomics/eris/blob/0cc722200380249afdf151737cb577e4f8b17a49/panels_backend/management/commands/_parse_transcript.py#L828)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

I felt like the returned error message isn't really dealt with downstream or am I wrong
</blockquote></details>

It isn't. This is because we didn't choose a logging strategy for Eris overall, which would involve putting in a location for log storage on the cluster, and also a routine of checking them. Currently we print urgent things, but this seems like it isn't urgent enough to clutter the console with, but also it's something we might want to know because it indicates an issue with our TARK download. Liv said she'd look into this but it's still on hold.

I think 'decide how to handle logging' should be its own, separate ticket.

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/103)* status: 11 of 18 files reviewed, 3 unresolved discussions (waiting on @corbin-chris)

___
*[`panels_backend/management/commands/_parse_transcript.py` line 825 at r2](https://reviewable.io/reviews/eastgenomics/eris/103#-NsN8_l00rP7puFKYZza:-NsNM0s0AO_VslJOtFqD:bj3cb0s) ([raw file](https://github.com/eastgenomics/eris/blob/0cc722200380249afdf151737cb577e4f8b17a49/panels_backend/management/commands/_parse_transcript.py#L825)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I don't understand what you mean, sorry.
I've already refactored this code a lot - I'm reluctant to refactor further unless there's a lot of redundancy that can be cut out, especially if dev is going to be paused anyway.
</blockquote></details>

you might need to add `multiple_matches = True` under the if statement (if len(transcript_list) > 1) since that's what determine if multiple_matches is True or False. 
___
*[`panels_backend/management/commands/_parse_transcript.py` line 828 at r2](https://reviewable.io/reviews/eastgenomics/eris/103#-NsN7yK71Y9YzUP5yObH:-NsNLvvx4ggibSK1D9eL:brkwc75) ([raw file](https://github.com/eastgenomics/eris/blob/0cc722200380249afdf151737cb577e4f8b17a49/panels_backend/management/commands/_parse_transcript.py#L828)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

It isn't. This is because we didn't choose a logging strategy for Eris overall, which would involve putting in a location for log storage on the cluster, and also a routine of checking them. Currently we print urgent things, but this seems like it isn't urgent enough to clutter the console with, but also it's something we might want to know because it indicates an issue with our TARK download. Liv said she'd look into this but it's still on hold.

I think 'decide how to handle logging' should be its own, separate ticket.
</blockquote></details>

make sense

**Review by corbin-chris — COMMENTED** [review]
Output files still being generated OK

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/103#-:-NsNOaqI1-3pChTU89D3:b-9ltmif)* status: 11 of 18 files reviewed, 3 unresolved discussions (waiting on @JasonLing95)

___
*[`panels_backend/management/commands/_parse_transcript.py` line 825 at r2](https://reviewable.io/reviews/eastgenomics/eris/103#-NsN8_l00rP7puFKYZza:-NsNO5vQDXq_K9hqHMVU:b-4e0101) ([raw file](https://github.com/eastgenomics/eris/blob/0cc722200380249afdf151737cb577e4f8b17a49/panels_backend/management/commands/_parse_transcript.py#L825)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

you might need to add `multiple_matches = True` under the if statement (if len(transcript_list) > 1) since that's what determine if multiple_matches is True or False.
</blockquote></details>

Good catch, added

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 5 of 6 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/103)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @corbin-chris)

___
*[`tests/test_panels_backend/test_management/test_commands/test_insert_panel/test_disable_custom_hgnc_panels.py` line 71 at r1](https://reviewable.io/reviews/eastgenomics/eris/103#-NsJMChZ9F_YGESbj56r:-NsNQ8Fn-_BpCLPge7vY:b-vymhiw) ([raw file](https://github.com/eastgenomics/eris/blob/b7d54d1d06fc7bbd4102770d7cd7a390065ea427/tests/test_panels_backend/test_management/test_commands/test_insert_panel/test_disable_custom_hgnc_panels.py#L71)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Changed it - are there 3 types of panel then, 'PanelApp' 'Test Directory' and 'custom'?
</blockquote></details>

yea. PanelApp from PanelApp API, Test Directory are like HGNCs- type from Test Directory, custom is those made by ourselves (if we ever made one)

**Pull request merged**
