### PR TITLE
Test transcript seeding

### PR DESCRIPTION
**Pull request by corbin-chris**
Tests for functions involved in transcript seeding, plus some refactoring to facilitate this. I've covered most functions except for very short file-readers with only minimum sense checking. There are smaller tests only on '_add_old_gene_changed_transcript' because of uncertainty over wanted behaviour (see below).
 
Note that all tests pass except for 5 of them. These are tests for other modules which were broken by an update to main, and are being fixed on a separate branch.

Please especially check and feed back on the following:
- test_add_old_gene_changed_transcript: is the current behaviour of '_add_old_gene_changed_transcript' acceptable, or do we need to change it to make it so that there can only ever be 1 db entry per transcript? Currently different sources and genome references can cause this.

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/28)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/28)* status: 3 of 9 files reviewed, 10 unresolved discussions (waiting on @corbin-chris and @JasonLing95)

___
*[`requests_app/management/commands/_parse_transcript.py` line 237 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB1cT04zbzTkJ0kfTt:-NfB1cT17ULfihvvTGOF:b-l4ali0) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/requests_app/management/commands/_parse_transcript.py#L237)):*
> ```Python
>     if len(markname[short_hgnc_id]) > 1:
>         err = f"{hgnc_id} has two or more entries in markname HGMD table."
>         return None, err
> ```

I'm not sure on structure of markname, but is this possible and something we need to handle? i.e can there be 2 entries in here that point to the same HGNC ID where a previous and current gene symbol  are present?



_Code quote:_
```Python
    if len(markname[short_hgnc_id]) > 1:
        err = f"{hgnc_id} has two or more entries in markname HGMD table."
        return None, err
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 278 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB31B22bCj9W5qTuZy:-NfB31B22bCj9W5qTuZz:b-kdrxvx) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/requests_app/management/commands/_parse_transcript.py#L278)):*
> ```Python
>     clinical = False
>     source = None
>     err = None
> ```

a random thing but if you're assigning multiple variables to None you're safe to do the assignment in one line like:
```
source = err = None
```

this is unlike if you assigned them all to any other object like a list as they'd each refer to the same object, but fine for None/False



_Code quote:_
```Python
    source = None
    err = None
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 280 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB2SU73B3X_U1mNfKf:-NfB2SU73B3X_U1mNfKg:b-6r45c5) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/requests_app/management/commands/_parse_transcript.py#L280)):*
will we _always_ have transcripts stored with versions? if we don't then this would raise a value error on trying to split:
```
>>> tx1='NM_12345.2'
>>> tx2='NM_12345'

>>> base, _ = tx1.split('.')
>>> base, _ = tx2.split('.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: not enough values to unpack (expected 2, got 1)
```

different approach to consider that would handle it:
```
>>> re.sub(r'\.[\d]+$', '', tx1)
'NM_12345'
>>> re.sub(r'\.[\d]+$', '', tx2)
'NM_12345'
```



_Code quote:_
```Python
    tx_base, _ = tx.split(".")
```
___
*[`requests_app/management/commands/_parse_transcript.py` line 295 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB2qfC6FWJef-dJps8:-NfB2qfC6FWJef-dJps9:b-9chp70) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/requests_app/management/commands/_parse_transcript.py#L295)):*
> ```Python
>         # MANE transcript search
>         mane_tx = mane_data[hgnc_id]
>         mane_base, _ = mane_tx.split(".")
> ```

as above



_Code quote:_
```Python
    mane_base, _ = mane_tx.split(".")
```
___
*[`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_add_gene_and_transcript_to_db.py` line 13 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB3l-H3tsdb1tM5sm9:-NfB3l-H3tsdb1tM5smA:ba2ung6) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_add_gene_and_transcript_to_db.py#L13)):*
> ```Python
> 
> 
> class TestAddGeneTranscript_FromScratch(TestCase):
> ```

I find it can be helpful to add class level descriptions about what the function being tested is expected to do, and therefore what we're expecting to be testing (it makes it easier as someone less familiar to the code to understand without jumping around through the code), doesn't have to be much just something like this:

https://github.com/eastgenomics/dias_batch_running/blob/a4dda8702e4d7ed28acd86ec2d4ef7d8aa4664df/resources/home/dnanexus/dias_batch/tests/test_utils.py#L33



_Code quote:_
```Python
class TestAddGeneTranscript_FromScratch(TestCase):
```
___
*[`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_add_gene_and_transcript_to_db.py` line 41 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB4GV-1iAsOYDX_2SE:-NfB4GV-1iAsOYDX_2SF:b46tlzh) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_add_gene_and_transcript_to_db.py#L41)):*
> ```Python
>         err += value_check(new_transcripts[0].reference_genome, "ref", "")
> 
>         errors = "".join(err)
> ```

do your individual error strings have line breaks or will this become one large munged string?



_Code quote:_
```Python
"".join(err)
```
___
*[`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_add_gene_and_transcript_to_db.py` line 75 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB4P8g4YKUg8uz8F1F:-NfB4P8g4YKUg8uz8F1G:b-9chp70) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_add_gene_and_transcript_to_db.py#L75)):*
> ```Python
>         err += value_check(second.reference_genome, "ref", "")
> 
>         errors = "".join(err)
> ```

as above



_Code quote:_
```Python
errors = "".join(err)
```
___
*[`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_get_clin_transcript_from_hgmd_files.py` line 83 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB4rZwEAgXDT0rDGA9:-NfB4rZwEAgXDT0rDGAA:b29o0cs) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_get_clin_transcript_from_hgmd_files.py#L83)):*
> ```Python
>     
>     def test_gene2reqseq_entry_contains_list_of_lists(self):
>         #TODO: complete this test
> ```

is this done?



_Code quote:_
```Python
#TODO: complete this test
```
___
*[`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_transcript_assigner.py` line 26 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB5GOO-1lNidt9XN_m:-NfB5GOO-1lNidt9XN_n:b-lgsdws) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_transcript_assigner.py#L26)):*
> ```Python
> 
>         clinical, source, err = _transcript_assigner(tx, hgnc_id, gene_clinical_transcript, 
>                          mane_data, markname_hgmd, gene2refseq_hgmd)
> ```

think this would be nicer something like:

```
errors = [x for x in [clinical, source, err] if x]

assert not errors, f"oh no :sadpepe: {errors}"
```
___
*[`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_transcript_assigner.py` line 51 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB5eEr6XcvwAEmghwM:-NfB5eEr6XcvwAEmghwN:b2b409c) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_transcript_assigner.py#L51)):*
> ```Python
>                          mane_data, markname_hgmd, gene2refseq_hgmd)
> 
>         assert clinical
> ```

as above with the asserts

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/28)* status: 3 of 9 files reviewed, 10 unresolved discussions (waiting on @corbin-chris and @jethror1)

___
*[`requests_app/management/commands/_parse_transcript.py` line 237 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB1cT04zbzTkJ0kfTt:-NfB6JQXCdglSBGtzsGy:b3039f) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/requests_app/management/commands/_parse_transcript.py#L237)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I'm not sure on structure of markname, but is this possible and something we need to handle? i.e can there be 2 entries in here that point to the same HGNC ID where a previous and current gene symbol  are present?
</blockquote></details>

haven't seen a 2 entries returned for a hgnc-id yet but we simply assign non-clinical to the transcript if that happens

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/28)* status: 3 of 9 files reviewed, 11 unresolved discussions (waiting on @corbin-chris and @jethror1)

___
*[`requests_app/management/commands/_parse_transcript.py` line 285 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfBKMpn2e_inYLcMw_t:-NfBKMpn2e_inYLcMw_u:b-rdkuj1) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/requests_app/management/commands/_parse_transcript.py#L285)):*
> ```Python
>     # any following transcripts will be non-clinical by default
>     if hgnc_id in gene_clinical_transcript:
>         if tx_base not in gene_clinical_transcript[hgnc_id][0].split(".", 1)[0]:
> ```

just trying to sanity check this if statement, why is this needed?

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/28)* status: 1 of 9 files reviewed, 11 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`requests_app/management/commands/_parse_transcript.py` line 237 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB1cT04zbzTkJ0kfTt:-NfL2Awf6ehCjF8TotTh:ba0g9se) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/requests_app/management/commands/_parse_transcript.py#L237)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

haven't seen a 2 entries returned for a hgnc-id yet but we simply assign non-clinical to the transcript if that happens
</blockquote></details>

It shouldn't ever happen, and duplicates of a HGNC ID imply something is weird with their input file - hence returning an error. However at the moment the errors just get dumped in a log file. We should probably write it into a process that the log gets checked, or maybe it should print to screen too.

The transcript gets assigned as 'non-clinical' because we can't work out whether it's clinical or not. It's seen as the safer option than the reverse, e.g. an obscure transcript being treated by scientists as the clinical one.
___
*[`requests_app/management/commands/_parse_transcript.py` line 278 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB31B22bCj9W5qTuZy:-NfHGJ_mE2LVjeESXqJA:b-uywn7o) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/requests_app/management/commands/_parse_transcript.py#L278)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

a random thing but if you're assigning multiple variables to None you're safe to do the assignment in one line like:
```
source = err = None
```

this is unlike if you assigned them all to any other object like a list as they'd each refer to the same object, but fine for None/False
</blockquote></details>

Why is Python like this
___
*[`requests_app/management/commands/_parse_transcript.py` line 280 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB2SU73B3X_U1mNfKf:-NfL48xWClcTlmn6DoZN:bnxb1bf) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/requests_app/management/commands/_parse_transcript.py#L280)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

will we _always_ have transcripts stored with versions? if we don't then this would raise a value error on trying to split:
```
>>> tx1='NM_12345.2'
>>> tx2='NM_12345'

>>> base, _ = tx1.split('.')
>>> base, _ = tx2.split('.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: not enough values to unpack (expected 2, got 1)
```

different approach to consider that would handle it:
```
>>> re.sub(r'\.[\d]+$', '', tx1)
'NM_12345'
>>> re.sub(r'\.[\d]+$', '', tx2)
'NM_12345'
```
</blockquote></details>

I think they should always be stored with versions but you are correct, I have changed it.
___
*[`requests_app/management/commands/_parse_transcript.py` line 285 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfBKMpn2e_inYLcMw_t:-NfLDUI7CSapOQJryMDn:b4us6ml) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/requests_app/management/commands/_parse_transcript.py#L285)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

just trying to sanity check this if statement, why is this needed?
</blockquote></details>

This first checks if a HGNC is in gene_clinical_transcripts already, and if it is, it checks that the current transcript **with the version removed** does not match the versionless transcript in gene_clinical_transcripts.
It's to address the case where a transcript is in gff with 2 versions of the same ID, for example {"HGNC:1": ["NM100.1", "NM100.2"]. I ran 'set' on this transcript list first, but NM100.1 and NM100.2 won't be deduplicated by that.
A thing I find confusing about this code is that it flip-flops on transcript versions. It does version-less comparison to MANE and HGMD, but then I think the final version does get put in Eris. Would we want the highest version-number to be in Eris? If so, I need to add some logic to handle this - what do we do if NM100.1 is in MANE but NM100.2 is in HGMD? Let me know what you think and I can add it
___
*[`requests_app/management/commands/_parse_transcript.py` line 295 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB2qfC6FWJef-dJps8:-NfL5gCkCxtrqhnYvUXE:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/requests_app/management/commands/_parse_transcript.py#L295)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

as above
</blockquote></details>

Done.
___
*[`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_add_gene_and_transcript_to_db.py` line 13 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB3l-H3tsdb1tM5sm9:-NfLLRdj9UiRzG1JxadB:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_add_gene_and_transcript_to_db.py#L13)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I find it can be helpful to add class level descriptions about what the function being tested is expected to do, and therefore what we're expecting to be testing (it makes it easier as someone less familiar to the code to understand without jumping around through the code), doesn't have to be much just something like this:

https://github.com/eastgenomics/dias_batch_running/blob/a4dda8702e4d7ed28acd86ec2d4ef7d8aa4664df/resources/home/dnanexus/dias_batch/tests/test_utils.py#L33
</blockquote></details>

Done.
___
*[`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_add_gene_and_transcript_to_db.py` line 41 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB4GV-1iAsOYDX_2SE:-NfHHExpCdogs04FrUyH:b-896fjx) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_add_gene_and_transcript_to_db.py#L41)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

do your individual error strings have line breaks or will this become one large munged string?
</blockquote></details>

Done
___
*[`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_add_gene_and_transcript_to_db.py` line 75 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB4P8g4YKUg8uz8F1F:-NfHHHXN8nEO5i4rT2c6:bb6un1j) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_add_gene_and_transcript_to_db.py#L75)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

as above
</blockquote></details>

Done
___
*[`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_get_clin_transcript_from_hgmd_files.py` line 83 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB4rZwEAgXDT0rDGA9:-NfHHbRXDb22VkaYDMf_:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_get_clin_transcript_from_hgmd_files.py#L83)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this done?
</blockquote></details>

Done.
___
*[`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_transcript_assigner.py` line 26 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB5GOO-1lNidt9XN_m:-NfLID7j3XyoIeJvZ1Dk:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_transcript_assigner.py#L26)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

think this would be nicer something like:

```
errors = [x for x in [clinical, source, err] if x]

assert not errors, f"oh no :sadpepe: {errors}"
```
</blockquote></details>

Done.
___
*[`tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_transcript_assigner.py` line 51 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB5eEr6XcvwAEmghwM:-NfLIqqKBPS-dgrMIkQf:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/tests/tests_requests_app/test_management/test_commands/test_parse_transcript/test_transcript_assigner.py#L51)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

as above with the asserts
</blockquote></details>

Done.

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 3 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/28)* status: all files reviewed, 1 unresolved discussion (waiting on @corbin-chris)

___
*[`requests_app/management/commands/_parse_transcript.py` line 237 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfB1cT04zbzTkJ0kfTt:-NfLQIGT9e1gE80OcYoz:b-5t3rer) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/requests_app/management/commands/_parse_transcript.py#L237)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

It shouldn't ever happen, and duplicates of a HGNC ID imply something is weird with their input file - hence returning an error. However at the moment the errors just get dumped in a log file. We should probably write it into a process that the log gets checked, or maybe it should print to screen too.

The transcript gets assigned as 'non-clinical' because we can't work out whether it's clinical or not. It's seen as the safer option than the reverse, e.g. an obscure transcript being treated by scientists as the clinical one.
</blockquote></details>

Until we got further solution to deal with weird cases on transcripts, I think assigning it non-clinical is a valid response.
___
*[`requests_app/management/commands/_parse_transcript.py` line 285 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfBKMpn2e_inYLcMw_t:-NfLRs_k3n5b0mbcoIZw:b-unnafv) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/requests_app/management/commands/_parse_transcript.py#L285)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

This first checks if a HGNC is in gene_clinical_transcripts already, and if it is, it checks that the current transcript **with the version removed** does not match the versionless transcript in gene_clinical_transcripts.
It's to address the case where a transcript is in gff with 2 versions of the same ID, for example {"HGNC:1": ["NM100.1", "NM100.2"]. I ran 'set' on this transcript list first, but NM100.1 and NM100.2 won't be deduplicated by that.
A thing I find confusing about this code is that it flip-flops on transcript versions. It does version-less comparison to MANE and HGMD, but then I think the final version does get put in Eris. Would we want the highest version-number to be in Eris? If so, I need to add some logic to handle this - what do we do if NM100.1 is in MANE but NM100.2 is in HGMD? Let me know what you think and I can add it
</blockquote></details>

but if NM100.1 is already in gene_clinical_transcripts, wouldn't that mean HGNC:1 is already set as the dict key thus any other version NM100.2 should become non-clinical - wouldn't that make the second if statement unnecessary

**Review by corbin-chris — COMMENTED** [review]
The sudden extra files are because I pulled from main and had to resolve a merge conflict semi-manually - it's code that's been reviewed.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/28#-:-NfMWSOl9Tq-P10LXEHc:b-78r9gd)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @JasonLing95 and @jethror1)

___
*[`requests_app/management/commands/_parse_transcript.py` line 285 at r1](https://reviewable.io/reviews/eastgenomics/eris/28#-NfBKMpn2e_inYLcMw_t:-NfMEm9J2mJxeArAwRZ2:b8uirhl) ([raw file](https://github.com/eastgenomics/eris/blob/e793494a769601018a3b4cec9671269fd3c03138/requests_app/management/commands/_parse_transcript.py#L285)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

but if NM100.1 is already in gene_clinical_transcripts, wouldn't that mean HGNC:1 is already set as the dict key thus any other version NM100.2 should become non-clinical - wouldn't that make the second if statement unnecessary
</blockquote></details>

OK I think I get what you mean now. I've edited it.
I may make a separate ticket for how to handle changed transcript versions, in case MANE/HGMD ever uses different version

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/28)* status: all files reviewed, 2 unresolved discussions (waiting on @corbin-chris)

___
*[`requests_app/management/commands/_parse_transcript.py` line 287 at r4](https://reviewable.io/reviews/eastgenomics/eris/28#-NfMc5MSDSuOkP01Lp-6:-NfMc5MSDSuOkP01Lp-7:b2mug6q) ([raw file](https://github.com/eastgenomics/eris/blob/5523e9704baddfe176fdaf7c0d0f4b4464dcbc8d/requests_app/management/commands/_parse_transcript.py#L287)):*
> ```Python
>     if hgnc_id in gene_clinical_transcript:
>         gene_clin_tx_base = re.sub(r'\.[\d]+$', '',  gene_clinical_transcript[hgnc_id][0])
>         if tx_base not in gene_clin_tx_base:
> ```

i think this logic is wrong
e.g. NM100.1 and NM100.2, both the same hgnc-id
in this case we already have NM100.1 assigned clinical with MANE
based on the if statement:
hgnc-id is in clinical_transcript_dict
the tx_base is in gene_clin_tx_base meaning it will not be returned clinical=False but instead go down to re-do the MANE or HGMD assignment

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/28)* status: all files reviewed, 2 unresolved discussions (waiting on @corbin-chris)

___
*[`requests_app/management/commands/_parse_transcript.py` line 287 at r4](https://reviewable.io/reviews/eastgenomics/eris/28#-NfMc5MSDSuOkP01Lp-6:-NfMdRQU3K7AjXDPzPOw:b-oh59r0) ([raw file](https://github.com/eastgenomics/eris/blob/5523e9704baddfe176fdaf7c0d0f4b4464dcbc8d/requests_app/management/commands/_parse_transcript.py#L287)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

i think this logic is wrong
e.g. NM100.1 and NM100.2, both the same hgnc-id
in this case we already have NM100.1 assigned clinical with MANE
based on the if statement:
hgnc-id is in clinical_transcript_dict
the tx_base is in gene_clin_tx_base meaning it will not be returned clinical=False but instead go down to re-do the MANE or HGMD assignment
</blockquote></details>

instead we want the function to return clinical=False straight away since there's already one transcript being clinical for the hgnc-id

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/28)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`requests_app/management/commands/_parse_transcript.py` line 287 at r4](https://reviewable.io/reviews/eastgenomics/eris/28#-NfMc5MSDSuOkP01Lp-6:-NfPr64DBJ-f3jwe4xRy:b-nfji3j) ([raw file](https://github.com/eastgenomics/eris/blob/5523e9704baddfe176fdaf7c0d0f4b4464dcbc8d/requests_app/management/commands/_parse_transcript.py#L287)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

instead we want the function to return clinical=False straight away since there's already one transcript being clinical for the hgnc-id
</blockquote></details>

Forgot to push the change I thought I'd made at last comment... should show up soon

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/28)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbin-chris)

**Pull request merged**
