### PR TITLE
In 463 unit test generate

### PR DESCRIPTION
**Pull request by corbin-chris**
This branch increases the coverage of generate.py to 75%. The uncovered functions are those which parse arguments and handle the top-level function calls - these are highly likely to be picked up in integration testing, and contain relatively uncomplicated logic.

If you want coverage reports as HTMLs please message me. I'll attach a top-level summary to the ticket in Confluence.

Back-end seeding steps were tried and are working.
Additionally, panels_backend tests are passing, though please note that an error introduced in a variant_db test is still present and is being addressed by an issue.

Ran 164 tests in 5.515s

OK
Destroying test database for alias 'default'...

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/94)

### CODE REVIEW

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/94)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`panels_backend/management/commands/generate.py` line 604 at r2](https://reviewable.io/reviews/eastgenomics/eris/94#-Nr_D8cy6wlGaLLbzbZ9:-Nr_yIQY5sHfii9cP8I4:b-wai2no) ([raw file](https://github.com/eastgenomics/eris/blob/120e09e0c2c4bd36503fc70e6a4659ba2c13804f/panels_backend/management/commands/generate.py#L604)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

the step to check whether there's release in db is already done further upstream by _block_genepanels_if_db_not_ready(). This step shouldn't be possible with that check upstream - if it is, the check function itself should be modified.

is the genepanel not outputting at this point?
</blockquote></details>

I think I added it because once while I was testing, I had a TD release in my local directory, but hadn't correctly added anything else, so the file came out blank. This 'shouldn't happen' if the manual is followed properly. _block_genepanels_if_db_not_ready() currently only checks there's any TD release, and no pending CI-Panels or CI-SuperPanels. It doesn't check for whether CI-Panels or CI-SuperPanels is entirely empty. I may add them now.

The genepanel is output in_write_genepanels_results().



_Code snippet:_
```Python
            results = self._generate_genepanels_results(hgncs_to_exclude)
            if results:
                self._write_genepanels_results(results, output_directory)
                print(f"Genepanel file created at {output_directory}")
            else:
                print(
                    "No genepanel results were found - check that the database"
```
___
*[`panels_backend/management/commands/generate.py` line 665 at r2](https://reviewable.io/reviews/eastgenomics/eris/94#-Nr_DnCsCxOnP0q9zLqC:-Nra-_yvB03WIE01Yz7u:b-oesji2) ([raw file](https://github.com/eastgenomics/eris/blob/120e09e0c2c4bd36503fc70e6a4659ba2c13804f/panels_backend/management/commands/generate.py#L665)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

same for this step, the check for possibilities should be further upstream. At this stage of the code, it shouldn't still be checking for error.

Is the g2t not output-ing result at this stage?
</blockquote></details>

As above, I might need to add more checks to the blocker function

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/94)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @corbin-chris and @jethror1)

___
*[`panels_backend/management/commands/generate.py` line 604 at r2](https://reviewable.io/reviews/eastgenomics/eris/94#-Nr_D8cy6wlGaLLbzbZ9:-Nra0Ngs1T1Y3DiOOPES:b-lrbhsi) ([raw file](https://github.com/eastgenomics/eris/blob/120e09e0c2c4bd36503fc70e6a4659ba2c13804f/panels_backend/management/commands/generate.py#L604)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I think I added it because once while I was testing, I had a TD release in my local directory, but hadn't correctly added anything else, so the file came out blank. This 'shouldn't happen' if the manual is followed properly. _block_genepanels_if_db_not_ready() currently only checks there's any TD release, and no pending CI-Panels or CI-SuperPanels. It doesn't check for whether CI-Panels or CI-SuperPanels is entirely empty. I may add them now.

The genepanel is output in_write_genepanels_results().
</blockquote></details>

that's why the check shouldn't be here rather be in _generate_genepanel_result itself to raise Exception if something doesn't add up. This step on writing genepanel result should only be reached if there's no issue

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/94)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`panels_backend/management/commands/generate.py` line 665 at r2](https://reviewable.io/reviews/eastgenomics/eris/94#-Nr_DnCsCxOnP0q9zLqC:-Nra12GAEFnjxdxmQf-l:bqk8gjo) ([raw file](https://github.com/eastgenomics/eris/blob/120e09e0c2c4bd36503fc70e6a4659ba2c13804f/panels_backend/management/commands/generate.py#L665)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

similar to above, there shouldn't be checks here instead it should be further upstream
</blockquote></details>

By the blocker function, I meant I could write a g2t version of '\_block\_genepanels\_if\_db\_not\_ready', which I'd call before '_generate_g2t_result' and '_write_g2t_result'.

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/94)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @corbin-chris and @jethror1)

___
*[`panels_backend/management/commands/generate.py` line 604 at r2](https://reviewable.io/reviews/eastgenomics/eris/94#-Nr_D8cy6wlGaLLbzbZ9:-NreYqUN9QdG4k2j2DLk:b-2648f7) ([raw file](https://github.com/eastgenomics/eris/blob/120e09e0c2c4bd36503fc70e6a4659ba2c13804f/panels_backend/management/commands/generate.py#L604)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

that's why the check shouldn't be here rather be in _generate_genepanel_result itself to raise Exception if something doesn't add up. This step on writing genepanel result should only be reached if there's no issue
</blockquote></details>

what's causing the CI-Panels or CI-SuperPanels to return entirely empty? Has it been addressed upstream?
___
*[`panels_backend/management/commands/generate.py` line 665 at r2](https://reviewable.io/reviews/eastgenomics/eris/94#-Nr_DnCsCxOnP0q9zLqC:-NreZ7ze-ylH63_Ma09-:b-g2cmg5) ([raw file](https://github.com/eastgenomics/eris/blob/120e09e0c2c4bd36503fc70e6a4659ba2c13804f/panels_backend/management/commands/generate.py#L665)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

By the blocker function, I meant I could write a g2t version of '\_block\_genepanels\_if\_db\_not\_ready', which I'd call before '_generate_g2t_result' and '_write_g2t_result'.
</blockquote></details>

same here, has the reason that is causing empty gene-to-transcript been addressed upstream?

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/94)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`panels_backend/management/commands/generate.py` line 604 at r2](https://reviewable.io/reviews/eastgenomics/eris/94#-Nr_D8cy6wlGaLLbzbZ9:-Nrdy8Fo6NRFEkZVtVp5:b-nnlm25) ([raw file](https://github.com/eastgenomics/eris/blob/120e09e0c2c4bd36503fc70e6a4659ba2c13804f/panels_backend/management/commands/generate.py#L604)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

what's causing the CI-Panels or CI-SuperPanels to return entirely empty? Has it been addressed upstream?
</blockquote></details>

Give me a minute, I'm still pushing stuff!

**Review by corbin-chris — COMMENTED** [review]
Note that normalize_version now returns None. I've done this because we previously discussed how I'd rather versionless panels showed None rather than 0.0, especially at the front-end, so we don't have people asking 'who assigned such a weird version name to a panel?' when the truth is they just don't have versions. I think sometimes custom panels are versionless - unless you've stopped users being allowed to do that in the front end @JasonLing95 ?

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/94#-:-Nrejh9mAy25VgE9JHn5:b-4vqwnh)* status: 1 of 12 files reviewed, 2 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`panels_backend/management/commands/generate.py` line 604 at r2](https://reviewable.io/reviews/eastgenomics/eris/94#-Nr_D8cy6wlGaLLbzbZ9:-NrejHF82lCzTZzDK7GU:b-46ukps) ([raw file](https://github.com/eastgenomics/eris/blob/120e09e0c2c4bd36503fc70e6a4659ba2c13804f/panels_backend/management/commands/generate.py#L604)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Give me a minute, I'm still pushing stuff!
</blockquote></details>

RE things causing CI-Panels/SuperPanels to return empty - I think this was a local error I had once and wasn't able to replicate it, so I think let's just leave it
___
*[`panels_backend/management/commands/generate.py` line 665 at r2](https://reviewable.io/reviews/eastgenomics/eris/94#-Nr_DnCsCxOnP0q9zLqC:-Nrejb928bwEpZY2fT9N:b-8a05gs) ([raw file](https://github.com/eastgenomics/eris/blob/120e09e0c2c4bd36503fc70e6a4659ba2c13804f/panels_backend/management/commands/generate.py#L665)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

same here, has the reason that is causing empty gene-to-transcript been addressed upstream?
</blockquote></details>

As above

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/94)* status: 2 of 14 files reviewed, 2 unresolved discussions (waiting on @JasonLing95)

___
*[`panels_backend/management/commands/generate.py` line 453 at r4](https://reviewable.io/reviews/eastgenomics/eris/94#-Ns849u07AAPAg-X8EmE:-Ns8DqS3Cz2ZC0D3ayWW:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/8c275fd0b4e2fa457d0a56d2b36cbd0d463191c6/panels_backend/management/commands/generate.py#L453)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

since we are writing function for two different task, might be better to split it into two functions which will make unit testing each of them easier
</blockquote></details>

Done.
___
*[`panels_backend/management/commands/generate.py` line 612 at r4](https://reviewable.io/reviews/eastgenomics/eris/94#-Ns84IZ07h4la6WBPPbb:-Ns8DrlcAb4aIQNBbcHR:b-67tpj4) ([raw file](https://github.com/eastgenomics/eris/blob/7b80b9753d4645af723b44eb3b67bf2351e4e5ee/panels_backend/management/commands/generate.py#L612)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

#NOTE
</blockquote></details>

Is this about splitting the function? If yes I've done that now

**Review by corbin-chris — COMMENTED** [review]
Ran `python manage.py test` at 4th March 2024, 11:46am:
Ran 190 tests in 4.770s

OK
Destroying test database for alias 'default'...

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/94#-:-Ns8HMR57Z4bPRYxCIMR:b-9xiisz)* status: 2 of 15 files reviewed, 2 unresolved discussions (waiting on @JasonLing95)

**Review by JasonLing95 — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, 2 of 3 files at r2, 4 of 7 files at r4, 4 of 5 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/94)* status: 13 of 15 files reviewed, all discussions resolved (waiting on @corbin-chris)

**Pull request merged**
