### PR TITLE
IN-244

### PR DESCRIPTION
**Pull request by corbin-chris**
Added the ability to manually change the clinical indication of a panel, using 'manage.py' from command line. Code can be reused for front end equivalent.
Note that a panel may have multiple clinical indications, a clinical indication may be linked to more than 1 panel, and any number of these links can be **set to current**. In practice most panel-indications will be 1:1.

### panel that is made up
python manage.py edit panel_id_clin_ind 10000 add R45.1
python manage.py edit panel_name_clin_ind 10000 add R45.1

The panel ID 10000 was not found in the database
The panel name "10000" was not found in the database

### try clinical indication that is made up
python manage.py edit panel_name_clin_ind "Stickler syndrome" add Rtest.1

The clinical indication code "Rtest.1" was not found in the database

### try to add pre-existing link
Both ID and name versions of the command:
python manage.py edit panel_name_clin_ind "Stickler syndrome" add R45.1
python manage.py edit panel_id_clin_ind 1 add R45.1

The panel "Stickler syndrome" and clinical indication "R45.1" are already linked and marked as current in the database. No change made.
The panel "1" and clinical indication "R45.1" are already linked and marked as current in the database. No change made.

### try to link a new clinical indication to a panel that does exist, but isn't presently linked - R141.1

python manage.py edit panel_name_clin_ind "Stickler syndrome" add R141.1
(no errors for ID version: python manage.py edit panel_id_clin_ind 1 add R141.1)

screenshots from dummy database, table and history table:

added_new_clinical_indication_link
history_added_new

### try to remove non-existent link
python manage.py edit panel_name_clin_ind "Stickler syndrome" remove Rtest.1
(tried after screenshots and found no errors for ID version: python manage.py edit panel_id_clin_ind 1 remove R141.1)

The clinical indication code "Rtest.1" was not found in the database

### remove the link we made earlier

python manage.py edit panel_name_clin_ind "Stickler syndrome" remove R141.1

screenshots from dummy database, table and history table:
deactivated_old_clinical_indication_link

history_removed_old

### then try to remove the link again, with ID this time
python manage.py edit panel_id_clin_ind 1 remove R141.1

The panel "Stickler syndrome" and clinical indication "R141.1" are already deactivated in the database. No change made.

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/3)

### CODE REVIEW

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/3)* status: 3 of 5 files reviewed, 18 unresolved discussions (waiting on @JasonLing95)

___
*[`requests_app/management/queries.py` line 24 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfj51K32YnOVfqNb0J:-NZg1QQBAdK_KPyD9H9I:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/queries.py#L24)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this function won't need to be atomic since it's not inserting data into db
</blockquote></details>

Done.
___
*[`requests_app/management/queries.py` line 25 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfkIRn3_2ZJaXziRDy:-NZg1Pb-CKN5_X6WsjqG:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/queries.py#L25)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

type hinting
```
def get_panel_by_id(panel_id: str) -> Panel | None
```
</blockquote></details>

Done.
___
*[`requests_app/management/queries.py` line 36 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfk9V6B4Rdlp76xgxm:-NZg1RwW16cUu14g6R7R:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/queries.py#L36)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this function won't need to be atomic since it's not inserting data into db
</blockquote></details>

Done.
___
*[`requests_app/management/queries.py` line 42 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfkBMvA8WX-3kRSpX0:-NZjSMJhBdRRpRd3Dk8K:bt3edor) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/queries.py#L42)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

check for empty results rather than DoesNotExist
</blockquote></details>

I think I do, when I call get_panel_by_name? With 'if not'



_Code snippet:_
```Python
panel = get\_panel\_by\_name(panel\_name)

if not panel:

    print("The panel name \\"{}\\" was not found in the database".format(panel\_name))

    exit(1)
```
___
*[`requests_app/management/queries.py` line 48 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfkA9lChIoxTiABmF_:-NZg1j2158tDELoURl93:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/queries.py#L48)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this function won't need to be atomic since it's not inserting data into db
</blockquote></details>

Done.
___
*[`requests_app/management/queries.py` line 54 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfjm1vBD7AW2wMp-Eo:-NZjT1JG9pHf99PVQMWv:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/queries.py#L54)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

filter will not raise DoesNotExist error, rather it will return an empty QuerySet, essentially an empty list. So you might want to check if results is empty
```
if results:
   return True
else:
   return False
```
</blockquote></details>

Done.
___
*[`requests_app/management/queries.py` line 61 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfkzCT79crzRNELf2M:-NZg2JfN5c9XCvGPDYyu:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/queries.py#L61)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

type hint
</blockquote></details>

Done.
___
*[`requests_app/management/queries.py` line 73 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZflOin5c4Z_Yv6DLgn:-NZg2e7ZAFGW564vhpKb:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/queries.py#L73)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

could be singular since we are expecting on ClinicalIndicationPanel
</blockquote></details>

Done.
___
*[`requests_app/management/queries.py` line 86 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZflYw3B0wZXjrtqBCz:-NZg2PHv1VjNNDXVDGr0:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/queries.py#L86)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

shouldn't this be the user argument in the function to record who did the modification (reactivation) rather than 'test user'
</blockquote></details>

Done.
___
*[`requests_app/management/queries.py` line 90 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfsNR8BXEVsd3uXshE:-NZg3NPWBcdA-4czdB7_:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/queries.py#L90)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

save is called implicitly when create is called, thus not needed
</blockquote></details>

Done.
___
*[`requests_app/management/queries.py` line 94 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfs8Zw4xJQgDnfFFXg:-NZg5TySCw0fpbCaZGAb:b-nkegu9) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/queries.py#L94)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

i think this can just be clinical_indication_panel = ClinicalIndicationPanel.objects...... wihout the new variable
</blockquote></details>

Yeah that was a mistake, I'm surprised that still ran. Done.
___
*[`requests_app/management/queries.py` line 100 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfsFM7EoN2LM4CM7c_:-NZg3PUL0FwxZaiWkvL2:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/queries.py#L100)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

create should automatically save() without needing .save()
</blockquote></details>

Done.
___
*[`requests_app/management/queries.py` line 109 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfserX2AEj4nyiff4-:-NZg3P1J65LXuU7mvQdE:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/queries.py#L109)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

no need .save()
</blockquote></details>

Done.
___
*[`requests_app/management/commands/edit.py` line 78 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfuZXm2MR2GVThAmI7:-NZg6v8R9iiYB8Xttcbl:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/commands/edit.py#L78)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

will be good to have a list of viable commands which we can `assert command in ['panel_id_clin_ind', 'panel_name_clin_ind'] else return 'command not available or something'
</blockquote></details>

Done.
___
*[`requests_app/management/commands/edit.py` line 97 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfvAFYA-KLTUpkUa70:-NZji-g88eG56vOv7g3E:b1j1ave) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/commands/edit.py#L97)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

could we move this above with 
` if not add_or_remove` and `if not r_code` so we can just aggregate all the initial checks above before we call all our command below
</blockquote></details>

Discussed this in Slack - moved a little for readability but can only aggregate so far, right now.
___
*[`requests_app/management/commands/edit.py` line 115 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfxGLL3LO-ZNB65qDD:-NZjTcol28SekuwJbdZ3:b-2ct0ui) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/commands/edit.py#L115)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

could simply return
</blockquote></details>

I don't understand which bit you want me to return - could you explain more please?
___
*[`requests_app/management/commands/edit.py` line 126 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfw0AgEsaVeYZqnpOr:-N_d8W3KBY00dGHczOuI:b-z34baw) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/commands/edit.py#L126)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

there can be case where clinical indication have similar R codes within the database but only one is linked to a Panel while the other is deactivate. Scenario is when CI's name is changed in recent TD version, then the backend will make a new CI (because we won't remove previous CI for audit purpose), the CI-Panel link will be changed from the old CI to this newly created CI. 

Thus here, the logic to setup is to find the one CI with active CI-Panel link. 

Example of duplicate CI
```
231	R78.4	Hereditary neuropathy or pain disorder - NOT PMP22 copy number	WGS
285	R78.4	Hereditary neuropathy or pain disorder	WGS
```
</blockquote></details>

I've added code to try to pick out clinical indications with CURRENT links in the clinical-indication-panel table. A very quick test is below:

Test: Try to link the duplicate R-code to panel 1 

R78.4 is present twice in my test database (I added a fake entry):
ClinicalIndication
id	r_code	name	test_method
237	R78.4	Hereditary neuropathy or pain disorder	WGS
286	R78.4	Hereditary neuropathy but with name changed	WGS

I try to link R78.4 code to panel ID '1':

python manage.py edit panel_id_clin_ind 1 add R78.4

This prints out the information:
'The clinical indication "R78.4" is present more than once in the database but only 1 has a current panel link - defaulting to the current indication'

The link between panel 1 and this clinical indication, is shown in the history table:
280	2023-07-18	14:06:33	Panel/indication link created and set to current by user	test_user	280
___
*[`requests_app/management/commands/edit.py` line 135 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfxWrCDSQin-z5ebQW:-NZg4JqM0ITE5raxu3R5:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/commands/edit.py#L135)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

```
if not result and not error
elif not result and error
else: pass
```
will be easier to read
</blockquote></details>

Done.

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/3)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @corbin-chris)

___
*[`requests_app/management/queries.py` line 24 at r5](https://reviewable.io/reviews/eastgenomics/eris/3#-N_dBKnuAmceofIfFeYw:-N_dBKnv3Gu7QuRi-uaJ:b-ikyd11) ([raw file](https://github.com/eastgenomics/eris/blob/93e361116d931e2ee9bdf4042d183f178732fe74/requests_app/management/queries.py#L24)):*
> ```Python
> 
> 
> def get_panel_by_id(panel_id) -> Panel | None:
> ```

type hint for function params please
___
*[`requests_app/management/queries.py` line 35 at r5](https://reviewable.io/reviews/eastgenomics/eris/3#-N_dHc7_3dJWqeNdKj2l:-N_dHc7_3dJWqeNdKj2m:b-xnxcjr) ([raw file](https://github.com/eastgenomics/eris/blob/93e361116d931e2ee9bdf4042d183f178732fe74/requests_app/management/queries.py#L35)):*
> ```Python
> 
> 
> def get_panel_by_name(panel_name) -> Panel | None:
> ```

type hint error

this function will return a `Queryset[Panel] | None` because you're returning results.all()

same for those functions with .filter
___
*[`requests_app/management/queries.py` line 119 at r5](https://reviewable.io/reviews/eastgenomics/eris/3#-N_dCFBp-0xLPn15xvPv:-N_dCFBp-0xLPn15xvPw:b-71a7n0) ([raw file](https://github.com/eastgenomics/eris/blob/93e361116d931e2ee9bdf4042d183f178732fe74/requests_app/management/queries.py#L119)):*
> ```Python
>     
>     except ClinicalIndicationPanel.MultipleObjectsReturned:
>         error = "This clinical indication and panel are linked multiple times in the linking table. Exiting."
> ```

these errors could simply be printed out in this function rather than returned, since you're printing it out later on anyway - will make this function cleaner as it wont be returning two outputs
___
*[`requests_app/management/queries.py` line 149 at r5](https://reviewable.io/reviews/eastgenomics/eris/3#-N_dCaRFA88PFX63Rbz4:-N_dCaRGAiCkVBuK4Iz0:bsi88t9) ([raw file](https://github.com/eastgenomics/eris/blob/93e361116d931e2ee9bdf4042d183f178732fe74/requests_app/management/queries.py#L149)):*
> ```Python
> 
>         else:
>             error_msg = "The panel \"{}\" and clinical indication \"{}\" are already".format(panel_name, r_code) +\
> ```

same here where these messages can just be printed out in this function rather than returned
___
*[`requests_app/management/queries.py` line 163 at r5](https://reviewable.io/reviews/eastgenomics/eris/3#-N_dGE7KEC3wvxm-RzI0:-N_dGE7KEC3wvxm-RzI1:bxryefs) ([raw file](https://github.com/eastgenomics/eris/blob/93e361116d931e2ee9bdf4042d183f178732fe74/requests_app/management/queries.py#L163)):*
> ```Python
> 
> 
> def current_and_non_current_panel_links(clinical_indication) \
> ```

type hint function param. I believe this input is a ClinicalIndication model?
___
*[`requests_app/management/queries.py` line 196 at r5](https://reviewable.io/reviews/eastgenomics/eris/3#-N_dFuC4-bvvP3VeMs__:-N_dFuC4-bvvP3VeMs_a:b-lo899e) ([raw file](https://github.com/eastgenomics/eris/blob/93e361116d931e2ee9bdf4042d183f178732fe74/requests_app/management/queries.py#L196)):*
> ```Python
>         # panels
>         current_indications = []
>         for ind in clinical_indications.values():
> ```

isnt clinical_indications param a list of ClinicalIndication models, this might fail `.values`.

However you could actually skip this step by simply returning `ClinicalIndicationPanel.objects.filter(current=True)` rather than filtering it with a for loop
___
*[`requests_app/management/commands/edit.py` line 115 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfxGLL3LO-ZNB65qDD:-N_dEDtH-Litfs9C72OW:b-j0cjvv) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/commands/edit.py#L115)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I don't understand which bit you want me to return - could you explain more please?
</blockquote></details>

rather than exit(1), could simply just `return` 
___
*[`requests_app/management/commands/edit.py` line 104 at r5](https://reviewable.io/reviews/eastgenomics/eris/3#-N_dSK6v8egM2L68_cY8:-N_dSK6v8egM2L68_cY9:bguy1pp) ([raw file](https://github.com/eastgenomics/eris/blob/93e361116d931e2ee9bdf4042d183f178732fe74/requests_app/management/commands/edit.py#L104)):*
> ```Python
>             name_for_error_message = panel_id
>             if not panel:
>                 print("The panel \"{}\" was not found in the database".format(name_for_error_message))
> ```

why not put panel_id into the print statement e.g. `print(f"The panel {panel_id} was not found in the database")`
same for the one below
___
*[`requests_app/management/commands/edit.py` line 126 at r5](https://reviewable.io/reviews/eastgenomics/eris/3#-N_dV7kd6DYRpczDMnC7:-N_dV7kd6DYRpczDMnC8:bez35kx) ([raw file](https://github.com/eastgenomics/eris/blob/93e361116d931e2ee9bdf4042d183f178732fe74/requests_app/management/commands/edit.py#L126)):*
> ```Python
>         # check that clinical_indication ('r_code') exists - prompt for it to be added to the database otherwise
>         r_code_res = get_clin_indication_by_r_code(r_code)
>         indication, msg = retrieve_active_clin_indication_by_r_code(r_code, r_code_res)
> ```

functions above `get_clin_indication_by_r_code` will return a Queryset / list of ClinicalIndication. to get those that have have active Ci-Panel link, you could query the ClinicalIndicationPanel table `ClinicalIndicationPanel.objects.filter(clinical_indication_id__in=[ci.id for ci in clinical_indications], current=True)`

This will return all CI-Panel that are currently active, that are also in those returned clinical indications - I think it will make the code cleaner

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/3)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @JasonLing95)

___
*[`requests_app/management/queries.py` line 24 at r5](https://reviewable.io/reviews/eastgenomics/eris/3#-N_dBKnuAmceofIfFeYw:-N_mX34G-kpmLd8iV5OF:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/93e361116d931e2ee9bdf4042d183f178732fe74/requests_app/management/queries.py#L24)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

type hint for function params please
</blockquote></details>

Done.
___
*[`requests_app/management/queries.py` line 35 at r5](https://reviewable.io/reviews/eastgenomics/eris/3#-N_dHc7_3dJWqeNdKj2l:-N_mOiMD-A1SJHLmB7SQ:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/93e361116d931e2ee9bdf4042d183f178732fe74/requests_app/management/queries.py#L35)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

type hint error

this function will return a `Queryset[Panel] | None` because you're returning results.all()

same for those functions with .filter
</blockquote></details>

Done.
___
*[`requests_app/management/queries.py` line 119 at r5](https://reviewable.io/reviews/eastgenomics/eris/3#-N_dCFBp-0xLPn15xvPv:-N_mR6IhBH-A6UgUQBxy:boxe461) ([raw file](https://github.com/eastgenomics/eris/blob/93e361116d931e2ee9bdf4042d183f178732fe74/requests_app/management/queries.py#L119)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

these errors could simply be printed out in this function rather than returned, since you're printing it out later on anyway - will make this function cleaner as it wont be returning two outputs
</blockquote></details>

I'm keeping it with returned messages, for the following reasons:
- The current layout will be faster and easier to adapt for a web front-end - our web controller function can capture any of these messages, and simply pass them to the user (https://docs.djangoproject.com/en/4.2/ref/contrib/messages/). That means we don't have to type the errors out in both the web and command-line controller functions.
- It's easier to unit-test the constituent functions if we cover this section (in my opinion) - you can just do asserts for the contents of the message
___
*[`requests_app/management/queries.py` line 149 at r5](https://reviewable.io/reviews/eastgenomics/eris/3#-N_dCaRFA88PFX63Rbz4:-N_mSCmXAVuopvav8W2M:b-8a05gs) ([raw file](https://github.com/eastgenomics/eris/blob/93e361116d931e2ee9bdf4042d183f178732fe74/requests_app/management/queries.py#L149)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

same here where these messages can just be printed out in this function rather than returned
</blockquote></details>

As above
___
*[`requests_app/management/queries.py` line 163 at r5](https://reviewable.io/reviews/eastgenomics/eris/3#-N_dGE7KEC3wvxm-RzI0:-N_mXVqW6BCk-Tnn5HPr:b-ahrpi4) ([raw file](https://github.com/eastgenomics/eris/blob/93e361116d931e2ee9bdf4042d183f178732fe74/requests_app/management/queries.py#L163)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

type hint function param. I believe this input is a ClinicalIndication model?
</blockquote></details>

This one is a dict, as it takes looped 'clinical_indications.values()' rather than being fed the ClinicalIndication model
___
*[`requests_app/management/queries.py` line 196 at r5](https://reviewable.io/reviews/eastgenomics/eris/3#-N_dFuC4-bvvP3VeMs__:-N_mXmXJ3fmGUs9cgcL7:b-5k9vph) ([raw file](https://github.com/eastgenomics/eris/blob/93e361116d931e2ee9bdf4042d183f178732fe74/requests_app/management/queries.py#L196)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

isnt clinical_indications param a list of ClinicalIndication models, this might fail `.values`.

However you could actually skip this step by simply returning `ClinicalIndicationPanel.objects.filter(current=True)` rather than filtering it with a for loop
</blockquote></details>

I'd rather not change it as it works and it won't save many lines (it passed testing with multiple indications). 'for ind in clinical_indications.values()' turns it into a list of dicts, then loops, so it doesn't fail. But I'll bear it in mind for the next ticket.
___
*[`requests_app/management/commands/edit.py` line 115 at r1](https://reviewable.io/reviews/eastgenomics/eris/3#-NZfxGLL3LO-ZNB65qDD:-N_mSXc_E5kNVWJfzCTQ:b-72v7p3) ([raw file](https://github.com/eastgenomics/eris/blob/80288e0b1fbd68c31fa96d9b365bf375b0359387/requests_app/management/commands/edit.py#L115)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

rather than exit(1), could simply just `return` 
</blockquote></details>

Not changing this because in a top-level function, they're equivalent to each other. I feel that 'exit' makes it more obvious that we're killing the whole script without trying to salvage, because something has gone wrong. https://stackoverflow.com/questions/23547284/exit-0-vs-return-0-python-preference 
___
*[`requests_app/management/commands/edit.py` line 104 at r5](https://reviewable.io/reviews/eastgenomics/eris/3#-N_dSK6v8egM2L68_cY8:-N_mZhsp4zQ9IUKFsu6-:bw1id7t) ([raw file](https://github.com/eastgenomics/eris/blob/93e361116d931e2ee9bdf4042d183f178732fe74/requests_app/management/commands/edit.py#L104)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

why not put panel_id into the print statement e.g. `print(f"The panel {panel_id} was not found in the database")`
same for the one below
</blockquote></details>

It's because we reuse the name_for_error_message outside the "if command ==" loop, further down, and I didn't want to do that 'if' again. Changed it though.
___
*[`requests_app/management/commands/edit.py` line 126 at r5](https://reviewable.io/reviews/eastgenomics/eris/3#-N_dV7kd6DYRpczDMnC7:-N_ma12W8VTQLh_v-20J:b-pqeiip) ([raw file](https://github.com/eastgenomics/eris/blob/93e361116d931e2ee9bdf4042d183f178732fe74/requests_app/management/commands/edit.py#L126)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

functions above `get_clin_indication_by_r_code` will return a Queryset / list of ClinicalIndication. to get those that have have active Ci-Panel link, you could query the ClinicalIndicationPanel table `ClinicalIndicationPanel.objects.filter(clinical_indication_id__in=[ci.id for ci in clinical_indications], current=True)`

This will return all CI-Panel that are currently active, that are also in those returned clinical indications - I think it will make the code cleaner
</blockquote></details>

In the interests of getting Eris done by the end of this year, I am skipping this as a more-minor suggestion

**Review by JasonLing95 — COMMENTED** [review]
> Reviewed 2 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/3)* status: 3 of 5 files reviewed, all discussions resolved

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbin-chris)

**Pull request merged**
