### PR TITLE
In 415 schema revisions

### PR DESCRIPTION
**Pull request by corbin-chris**
Please see ticket for IN-415 for change details.

Unit tests are completing successfully:
Ran 136 tests in 4.600s

OK
Destroying test database for alias 'default'...

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/73)

### CODE REVIEW

**Comment by spaul91** [comment]
Changes (https://cuhbioinformatics.atlassian.net/browse/IN-415):

- Add a column to Interpretation for all of the various ACGS-style ‘levels’ and ‘evidence’ notes (they must all be nullable)
- There’s probably a better way to normalise this - but will do it ‘the long way’ on this branch, just to be sure it lives somewhere
- Add more to the documentation string for ‘AssertionCriteria', ‘ClinicalSignificanceDescription’ and ‘ClinvarAlleleOrigin’
- ALREADY IN SCHEMA Multiple Interpretations now possible for a Variant
- Add Interpreted? column to Variants
- Make a ‘clinical_indication' column in Interpretation table. Explain why it isn’t an FK!
- probesetID, link to interpretation
- Associated_disease on Interpretation table
- Known_inheritance as string column on Interpretation (NOT ModeOfInheritance)
- Prevalence as string column on Interpretation
- Add Organisation and Institution

**Comment by spaul91** [comment]
*[`variant_db/models.py` line 29 at r1](https://reviewable.io/reviews/eastgenomics/eris/73#-NoCFJvC41cr8lXw3cUc:-NoCFJvC41cr8lXw3cUd:b1dj926) ([raw file](https://github.com/eastgenomics/eris/blob/3b68db15c0e8a356f493b0cbcd9b7be825990082/variant_db/models.py#L29)):*
> ```Python
> 
> 
> class TestCode(models.Model):
> ```

What's the relationship between a sample, test code and probeset? Are they all 1:1? My feeling is that test code and probeset could probably live together in the same table as the rest of the sample data, it'd probably be more performant when it comes to querying due to the fewer joins. Plus, the data is meaningfully related to each other, so splitting into separate tables doesn't feel necessary

**Comment by spaul91** [comment]
*[`variant_db/models.py` line 197 at r1](https://reviewable.io/reviews/eastgenomics/eris/73#-NoCFzm32fhgX_gMD9kR:-NoCFzm32fhgX_gMD9kS:b-gfl24b) ([raw file](https://github.com/eastgenomics/eris/blob/3b68db15c0e8a356f493b0cbcd9b7be825990082/variant_db/models.py#L197)):*
> ```Python
> 
> 
> class Organization(models.Model):
> ```

Probably a Wook question, but while this makes sense in theory, does the NHS ever have multiple organisations per institution/vice versa? I'm inclined to suggest collapsing these two tables into one

**Comment by spaul91** [comment]
*[`variant_db/models.py` line 239 at r1](https://reviewable.io/reviews/eastgenomics/eris/73#-NoCGaj2BAqZUnVi_r-E:-NoCGaj3CXc_3ZRoHuH_:bvm7cgi) ([raw file](https://github.com/eastgenomics/eris/blob/3b68db15c0e8a356f493b0cbcd9b7be825990082/variant_db/models.py#L239)):*
> ```Python
>     # TODO: long term, switch to using ClinicalIndication as an FK here. For now, tolerate strings.
>     # N.B. this is NOT a ClinicalIndication FK.
>     clinical_indication = models.TextField(
> ```

Sorry, can you re-explain to me why we've changed this here?

**Review by spaul91 — COMMENTED** [review]
Some clarification needed

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/73#-:-NoCGvBP8NU4QZduHgiV:b2vt5iw)* status: all files reviewed, 3 unresolved discussions (waiting on @corbin-chris)

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/73)* status: all files reviewed, 3 unresolved discussions (waiting on @spaul91)

___
*[`variant_db/models.py` line 29 at r1](https://reviewable.io/reviews/eastgenomics/eris/73#-NoCFJvC41cr8lXw3cUc:-NoCd8Ye2fCo20Cphpiv:bwkyanc) ([raw file](https://github.com/eastgenomics/eris/blob/3b68db15c0e8a356f493b0cbcd9b7be825990082/variant_db/models.py#L29)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

What's the relationship between a sample, test code and probeset? Are they all 1:1? My feeling is that test code and probeset could probably live together in the same table as the rest of the sample data, it'd probably be more performant when it comes to querying due to the fewer joins. Plus, the data is meaningfully related to each other, so splitting into separate tables doesn't feel necessary
</blockquote></details>

No, there's a relatively small number of test codes, and many samples under each test code. Probeset and test code are not 1:1 either. 
I'm not avoiding normalising the data table just to avoid joins, and I'm not doing performance optimisation before we have a first draft of the code.
___
*[`variant_db/models.py` line 197 at r1](https://reviewable.io/reviews/eastgenomics/eris/73#-NoCFzm32fhgX_gMD9kR:-NoCh3tg5hPxryZ2uANJ:b-hkafd7) ([raw file](https://github.com/eastgenomics/eris/blob/3b68db15c0e8a356f493b0cbcd9b7be825990082/variant_db/models.py#L197)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Probably a Wook question, but while this makes sense in theory, does the NHS ever have multiple organisations per institution/vice versa? I'm inclined to suggest collapsing these two tables into one
</blockquote></details>

This will depend on how the orgs/institutes have set up their ClinVar IDs, I think. Chasing it up now
___
*[`variant_db/models.py` line 239 at r1](https://reviewable.io/reviews/eastgenomics/eris/73#-NoCGaj2BAqZUnVi_r-E:-NoCh1ZT0dDVftS60v5L:b7q059g) ([raw file](https://github.com/eastgenomics/eris/blob/3b68db15c0e8a356f493b0cbcd9b7be825990082/variant_db/models.py#L239)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

Sorry, can you re-explain to me why we've changed this here?
</blockquote></details>

Explained in chat

**Review by spaul91 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/73#-:-NoCu92v1DX3q9TrKP5D:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @corbin-chris)

**Pull request merged**
