### PR TITLE
IN-420: Include editing database interaction in readme

### PR DESCRIPTION
**Pull request by JasonLing95**
- clean up editing db through cmd line
- update readme

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/74)

### CODE REVIEW

**Review by corbin-chris — CHANGES_REQUESTED** [review]
Do the unit tests still run OK with those files being deleted?

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/74#-:-NoLwtwjAtEkvmBzTpXM:bvocjmq)* status: all files reviewed, 5 unresolved discussions (waiting on @JasonLing95)

___
*[`panels_backend/management/commands/edit.py` line 22 at r2](https://reviewable.io/reviews/eastgenomics/eris/74#-NoLrfMVDTjCbi58c7Z3:-NoLrfMVDTjCbi58c7Z4:bu7dkun) ([raw file](https://github.com/eastgenomics/eris/blob/2e3f270c6666cac37f900fd9607a37dd7c6f6a9a/panels_backend/management/commands/edit.py#L22)):*
> ```Python
> 
>     # def _validate_panel_exists(self, panel) -> bool:
>     # TODO: need to check the panel exists
> ```

Did you complete this TODO yet?
___
*[`panels_backend/management/commands/edit.py` line 25 at r2](https://reviewable.io/reviews/eastgenomics/eris/74#-NoLuzs565PAO_Sxfnmt:-NoLuzs565PAO_Sxfnmu:bcc6e7u) ([raw file](https://github.com/eastgenomics/eris/blob/2e3f270c6666cac37f900fd9607a37dd7c6f6a9a/panels_backend/management/commands/edit.py#L25)):*
> ```Python
> 
>     def add_arguments(self, parser) -> None:
>         """Define the source of the data to import."""
> ```

Instead of having to worry about manually writing the logic for 'you can provide panel_id or panel_name but not both' (and the same for clinical_indication's arguments), try mutually exclusive groups. Then it will stop the user from using both and print an error without you having to do any more coding.



_Code snippet:_
```Python
panel_group = parser.add_mutually_exclusive_group()
panel_group.add_argument('-panel_id', type=int, help="panel id", action='store_true')
panel_group.add_argument('-panel_name', type=int, help="panel name", action='store_true')
# you can make a CI group too
```
___
*[`panels_backend/management/commands/edit.py` line 81 at r2](https://reviewable.io/reviews/eastgenomics/eris/74#-NoLsIDj1jxSpU_f_XJQ:-NoLsIDj1jxSpU_f_XJR:b-u02h3b) ([raw file](https://github.com/eastgenomics/eris/blob/2e3f270c6666cac37f900fd9607a37dd7c6f6a9a/panels_backend/management/commands/edit.py#L81)):*
> ```Python
> 
>         if panel_id:
>             assert panel_id, "Please specify panel ID"
> ```

This assert statement might be redundant? Will things not already have failed at 'if panel_id' in this case?

You maybe need to also assert that the user has provided panel_id or panel_name, but not both. Alternatively, if the user provides both panel_id and panel_name, you need to check that they are both for the same Panel. (Obviously, ignore some of this if you've already fixed the 'one or the other' problem with 'add_mutually_exclusive_group')



_Code snippet:_
```Python
# Something like this - it's not the shortest but should cover all situations
panel_name_id_error = "Please specify either panel ID or panel name, not both"
if panel_id:
    assert not panel_name, panel_name_id_error
if panel_name:
    assert not panel_id, panel_name_id_error
if not panel_id and not panel_name:
    assert False, panel_name_id_error
```
___
*[`panels_backend/management/commands/edit.py` line 105 at r2](https://reviewable.io/reviews/eastgenomics/eris/74#-NoLtkKA9hnXLpO3UMFI:-NoLtkKA9hnXLpO3UMFJ:b-tpsj0i) ([raw file](https://github.com/eastgenomics/eris/blob/2e3f270c6666cac37f900fd9607a37dd7c6f6a9a/panels_backend/management/commands/edit.py#L105)):*
> ```Python
>             clinical_indication_id is not None
>             and clinical_indication_r_code is not None
>         ), "Please specify either clinical indication database id or r-code, not both"
> ```

Does this successfully reject the case where the user has provided neither?

Your code might simplify to this, but test it first



_Code snippet:_
```Python
assert not(clinical_indication_id and clinical_indication_r_code)
```
___
*[`panels_backend/management/commands/edit.py` line 113 at r2](https://reviewable.io/reviews/eastgenomics/eris/74#-NoLwL7NAi-gAcgT-uh5:-NoLwL7NAi-gAcgT-uh6:b-n6lz15) ([raw file](https://github.com/eastgenomics/eris/blob/2e3f270c6666cac37f900fd9607a37dd7c6f6a9a/panels_backend/management/commands/edit.py#L113)):*
> ```Python
> 
>             # foresee r-code might return multiple ci entries
>             assert len(clinical_indication) < 2, (
> ```

Wrong arrow direction. You want to check if there's more than 1 CI, not fewer than 2.
Give these a manual test before resubmitting please?



_Code snippet:_
```Python
assert len(clinical_indication) > 1, (
```

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/74)* status: all files reviewed, 5 unresolved discussions (waiting on @corbin-chris)

___
*[`panels_backend/management/commands/edit.py` line 22 at r2](https://reviewable.io/reviews/eastgenomics/eris/74#-NoLrfMVDTjCbi58c7Z3:-NoOQg7A8EWHsR18J7rV:b-z6soz6) ([raw file](https://github.com/eastgenomics/eris/blob/2e3f270c6666cac37f900fd9607a37dd7c6f6a9a/panels_backend/management/commands/edit.py#L22)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Did you complete this TODO yet?
</blockquote></details>

removed. I think this TODO is done
___
*[`panels_backend/management/commands/edit.py` line 25 at r2](https://reviewable.io/reviews/eastgenomics/eris/74#-NoLuzs565PAO_Sxfnmt:-NoOSfQZ-QyIuiIvDQgV:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/2e3f270c6666cac37f900fd9607a37dd7c6f6a9a/panels_backend/management/commands/edit.py#L25)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Instead of having to worry about manually writing the logic for 'you can provide panel_id or panel_name but not both' (and the same for clinical_indication's arguments), try mutually exclusive groups. Then it will stop the user from using both and print an error without you having to do any more coding.
</blockquote></details>

done
___
*[`panels_backend/management/commands/edit.py` line 81 at r2](https://reviewable.io/reviews/eastgenomics/eris/74#-NoLsIDj1jxSpU_f_XJQ:-NoOSja-4Jm-VFyCORVi:b6bdu0l) ([raw file](https://github.com/eastgenomics/eris/blob/2e3f270c6666cac37f900fd9607a37dd7c6f6a9a/panels_backend/management/commands/edit.py#L81)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

This assert statement might be redundant? Will things not already have failed at 'if panel_id' in this case?

You maybe need to also assert that the user has provided panel_id or panel_name, but not both. Alternatively, if the user provides both panel_id and panel_name, you need to check that they are both for the same Panel. (Obviously, ignore some of this if you've already fixed the 'one or the other' problem with 'add_mutually_exclusive_group')
</blockquote></details>

since we changed it to add_mutually_exclusive_groups(required=true) this assertion is currently not required because either panel_id or panel_name. 
___
*[`panels_backend/management/commands/edit.py` line 105 at r2](https://reviewable.io/reviews/eastgenomics/eris/74#-NoLtkKA9hnXLpO3UMFI:-NoOT8Cx0CLBPEWsOUCP:bn1ow06) ([raw file](https://github.com/eastgenomics/eris/blob/2e3f270c6666cac37f900fd9607a37dd7c6f6a9a/panels_backend/management/commands/edit.py#L105)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Does this successfully reject the case where the user has provided neither?

Your code might simplify to this, but test it first
</blockquote></details>

add_mutually_exclusive_groups(required=true) means this assertion is no longer required as it's ensured upstream
___
*[`panels_backend/management/commands/edit.py` line 113 at r2](https://reviewable.io/reviews/eastgenomics/eris/74#-NoLwL7NAi-gAcgT-uh5:-NoOTZH-4F9yBJ2KrNZE:bodq7c8) ([raw file](https://github.com/eastgenomics/eris/blob/2e3f270c6666cac37f900fd9607a37dd7c6f6a9a/panels_backend/management/commands/edit.py#L113)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Wrong arrow direction. You want to check if there's more than 1 CI, not fewer than 2.
Give these a manual test before resubmitting please?
</blockquote></details>

we want to assert that the length is 1 basically. thus, based on the code, any length more than 1 will raise an assertion so the arrow direction is correct

**Review by corbin-chris — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/74)* status: all files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

___
*[`panels_backend/management/commands/edit.py` line 113 at r2](https://reviewable.io/reviews/eastgenomics/eris/74#-NoLwL7NAi-gAcgT-uh5:-NoRFeiK8NJxl17gNfk5:b-68cqxd) ([raw file](https://github.com/eastgenomics/eris/blob/2e3f270c6666cac37f900fd9607a37dd7c6f6a9a/panels_backend/management/commands/edit.py#L113)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

we want to assert that the length is 1 basically. thus, based on the code, any length more than 1 will raise an assertion so the arrow direction is correct
</blockquote></details>

You're right, I had a dumb moment.
___
*[`panels_backend/management/commands/edit.py` line 29 at r3](https://reviewable.io/reviews/eastgenomics/eris/74#-NoRExBs1zT5uQMqEJQX:-NoRExBs1zT5uQMqEJQY:b6vabpk) ([raw file](https://github.com/eastgenomics/eris/blob/3fa05d1a725b8e800f5911c276cf9fb2e11b2deb/panels_backend/management/commands/edit.py#L29)):*
> ```Python
>             "--panel_id",
>             type=int,
>             help="panel name",
> ```

I think the help text for 'panel_id' and 'panel_name' are mixed up here.
I'm otherwise happy with this.

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/74)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @corbin-chris)

___
*[`panels_backend/management/commands/edit.py` line 29 at r3](https://reviewable.io/reviews/eastgenomics/eris/74#-NoRExBs1zT5uQMqEJQX:-NoRGtIlC8tNVuK96pcQ:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/3fa05d1a725b8e800f5911c276cf9fb2e11b2deb/panels_backend/management/commands/edit.py#L29)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I think the help text for 'panel_id' and 'panel_name' are mixed up here.
I'm otherwise happy with this.
</blockquote></details>

done

**Comment by JasonLing95** [comment]
latest unit test result
```
Found 136 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.........................Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: True
Data insertion completed.
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
................................For panel Acute rhabdomyolyosis, skipping gene without confidence information: acyl-CoA dehydrogenase family member 9
.For panel Acute rhabdomyolyosis, skipping gene without confidence information: acyl-CoA dehydrogenase family member 9
..For panel Acute rhabdomyolyosis, skipping gene without HGNC ID: acyl-CoA dehydrogenase family member 9
...........Aborting because API returned a non-200 exit code: 500
......................Start 2 gene bulk create: 11:15:01
.Linking 1 unchanged genes to new HGNC release vversion2
.Linking 3 unchanged genes to new HGNC release vversion2
.....Preparing HGNC files
Start bulk-updating 2 gene symbols: 11:15:02
Linking 0 unchanged genes to new HGNC release v1.0
Start 13 gene bulk create: 11:15:02
.Preparing HGNC files
Start bulk-updating 2 gene symbols: 11:15:02
Linking 0 unchanged genes to new HGNC release v1.0
Start 13 gene bulk create: 11:15:02
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 11:15:02
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 11:15:02
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 11:15:02
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 11:15:02
.................Start bulk-updating 1 gene symbols: 11:15:02
.Start bulk-updating 2 gene symbols: 11:15:02
.
----------------------------------------------------------------------
Ran 136 tests in 5.202s

OK
Destroying test database for alias 'default'...
```

**Review by corbin-chris — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/74)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Review by corbin-chris — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/74)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
