### PR TITLE
IN-246-1 HGNC Panels

### PR DESCRIPTION
**Pull request by JasonLing95**
# Changes
- running `python manage.py seed panelapp all` now checks for HGNC-type panel with similar PanelGene content as panel from PanelApp. If instance found, both ci-panel links will be flagged for review.
- [FrontEnd] showing ClinicalIndication-SuperPanel interaction in ClinicalIndication info page
- removed a function `_retrieve_unknown_metadata_records` which return 4 None - value declared instead
- fixed some mock panelapp api to be more accurate

```
Found 136 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.........................Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: True
Data insertion completed.
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
................................For panel Acute rhabdomyolyosis, skipping gene without confidence information: acyl-CoA dehydrogenase family member 9
.For panel Acute rhabdomyolyosis, skipping gene without confidence information: acyl-CoA dehydrogenase family member 9
..For panel Acute rhabdomyolyosis, skipping gene without HGNC ID: acyl-CoA dehydrogenase family member 9
...........Aborting because API returned a non-200 exit code: 500
......................Start 2 gene bulk create: 21:50:31
.Linking 1 unchanged genes to new HGNC release vversion2
.Linking 3 unchanged genes to new HGNC release vversion2
.....Preparing HGNC files
Start bulk-updating 2 gene symbols: 21:50:31
Linking 0 unchanged genes to new HGNC release v1.0
Start 13 gene bulk create: 21:50:31
.Preparing HGNC files
Start bulk-updating 2 gene symbols: 21:50:31
Linking 0 unchanged genes to new HGNC release v1.0
Start 13 gene bulk create: 21:50:31
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 21:50:31
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 21:50:31
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 21:50:31
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 21:50:31
.................Start bulk-updating 1 gene symbols: 21:50:31
.Start bulk-updating 2 gene symbols: 21:50:31
.
----------------------------------------------------------------------
Ran 136 tests in 5.141s

OK
Destroying test database for alias 'default'...
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/76)

### CODE REVIEW

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/76)* status: 12 of 16 files reviewed, 7 unresolved discussions (waiting on @corbin-chris)

___
*[`panels_backend/management/commands/_insert_panel.py` line 285 at r1](https://reviewable.io/reviews/eastgenomics/eris/76#-NoR9y6H8xtNPRxO7Eh_:-NoWOc5M2oCBGSs4qziK:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/0049f56c86b6c6cc9032f891784342736de4e07b/panels_backend/management/commands/_insert_panel.py#L285)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Please put something like this instead? I think it's important to emphasise that the PanelApp panel wouldn't actually be given a name with HGNCs strung together - that's just a step you're doing to make it easier to look up in the database.

'Function to disable custom hgnc panels, if a PanelApp-created panel is linked to exactly the same HGNC IDs as those in the custom panel's name'.
</blockquote></details>

done
___
*[`panels_backend/management/commands/_insert_panel.py` line 304 at r1](https://reviewable.io/reviews/eastgenomics/eris/76#-NoR2W-q6zC9JjFY9Fh_:-NoWOcni9nv7bnocyLeC:b-z6dxuy) ([raw file](https://github.com/eastgenomics/eris/blob/0049f56c86b6c6cc9032f891784342736de4e07b/panels_backend/management/commands/_insert_panel.py#L304)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

For 'normal' non-custom panels we can have multiple entries with the same name, but different versions. But custom panels only have version=None - is that why there can only be 1 panel?
I'm wondering if we should formalise this by setting 'unique_together's under the Panel class. Would [panel_name, panel_version] make sense or would that fall over somewhere, e.g. when dealing with PanelApp versus custom panels?
</blockquote></details>

for custom panel yes. because a different version of it will definitely have different panel-gene interaction, thus it'll always alter the panel name when it's created. so we can be sure there'll only be one panel for a fixed set of panel-gene interaction

setting unique together in panel - done
___
*[`panels_backend/management/commands/_insert_panel.py` line 385 at r1](https://reviewable.io/reviews/eastgenomics/eris/76#-NoRBFaXD5M60W2af8AI:-NoWUInD9Nh5f1Hv60gc:bjftfrb) ([raw file](https://github.com/eastgenomics/eris/blob/0049f56c86b6c6cc9032f891784342736de4e07b/panels_backend/management/commands/_insert_panel.py#L385)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Would it make sense to move '_disable_custom_hgnc_panels()' so that it's called under the 'if created' block (maybe after 'provisionally_link_clinical_indication_to_panels'? As if the PanelApp panel already existed (created=False) it should already have been deactivated, and so it would be redundant to call it.
</blockquote></details>

it make sense but we will lose one functionality - which is re-running to capture any newly seeded custom panels from test directory. so I think not to keep it under "if created" is better.
___
*[`panels_web/views.py` line 1056 at r1](https://reviewable.io/reviews/eastgenomics/eris/76#-NoRDls1EdQYEeY5rhuw:-NoWV8T17TnMX69vO1gW:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/0049f56c86b6c6cc9032f891784342736de4e07b/panels_web/views.py#L1056)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Use None instead of 1.0? We discussed it a long time ago but I'm uncomfortable with setting a version in the display where one doesn't exist.
</blockquote></details>

done
___
*[`panels_web/views.py` line 1081 at r1](https://reviewable.io/reviews/eastgenomics/eris/76#-NoRDRe_CDmjTmdP7-7a:-NoWV96E4xyhKJ034ARh:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/0049f56c86b6c6cc9032f891784342736de4e07b/panels_web/views.py#L1081)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Do you mean cisp["superpanel_id__panel_version"] = 1.0 here?
Please don't make the version 1.0 if the version doesn't exist or can't be normalised - that's just making stuff up. It's better to show None if there isn't a version, and maybe display the string "None" on the user side if that results in a blank space.
</blockquote></details>

done
___
*[`panels_web/views.py` line 1230 at r2](https://reviewable.io/reviews/eastgenomics/eris/76#-NoWM-Yt4XLMLLxYhtEg:-NoWVHMz2JTUVD30tm4c:b-bc600b) ([raw file](https://github.com/eastgenomics/eris/blob/d4475e3e2646d9fa9067b6d975b56e4393dfd211/panels_web/views.py#L1230)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Could you please confirm that you've tested that this works, either by unit test or by artificially adding extra CI links to the database and seeing whether this returns anything? This 'looks ok' to me, but I'm not very familiar with using Q
</blockquote></details>

posted the evidence in PR comments
___
*[`panels_web/templates/web/review/pending.html` line 56 at r2](https://reviewable.io/reviews/eastgenomics/eris/76#-NoWMpLQ8iPlS80seS8K:-NoWVqOx3xUZUmZbA_lw:b-l9mh2q) ([raw file](https://github.com/eastgenomics/eris/blob/e0d089e4baf74946bad9ee30b2f80d600b554086/panels_web/templates/web/review/pending.html#L56)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Is there a reason why you got rid of this? I think alerting the user that their action has 'gone through' is generally a good idea.
</blockquote></details>

decided to change to a new system in "pending page" so that will be another PR in the future

**Comment by JasonLing95** [comment]
Screenshot 2024-01-19 at 11 37 07
Screenshot 2024-01-19 at 11 37 29

**Review by corbin-chris — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/76)* status: all files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

___
*[`panels_backend/management/commands/_insert_panel.py` line 385 at r1](https://reviewable.io/reviews/eastgenomics/eris/76#-NoRBFaXD5M60W2af8AI:-NoWc8x38qYUbz0XCsYv:bls0va6) ([raw file](https://github.com/eastgenomics/eris/blob/0049f56c86b6c6cc9032f891784342736de4e07b/panels_backend/management/commands/_insert_panel.py#L385)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

it make sense but we will lose one functionality - which is re-running to capture any newly seeded custom panels from test directory. so I think not to keep it under "if created" is better.
</blockquote></details>

Sure, we'll keep it for now.
___
*[`panels_web/views.py` line 1081 at r1](https://reviewable.io/reviews/eastgenomics/eris/76#-NoRDRe_CDmjTmdP7-7a:-NoWcZA81l15PyBPUB3f:b-zcsghp) ([raw file](https://github.com/eastgenomics/eris/blob/0049f56c86b6c6cc9032f891784342736de4e07b/panels_web/views.py#L1081)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

done
</blockquote></details>

Still need to change
cisp["panel_id__panel__version"]
to
cisp["superpanel_id__panel_version"]

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/76)* status: all files reviewed, 1 unresolved discussion (waiting on @corbin-chris)

___
*[`panels_web/views.py` line 1081 at r1](https://reviewable.io/reviews/eastgenomics/eris/76#-NoRDRe_CDmjTmdP7-7a:-NoWdsxD8d1tMvPyYtc3:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/0049f56c86b6c6cc9032f891784342736de4e07b/panels_web/views.py#L1081)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Still need to change
cisp["panel_id__panel__version"]
to
cisp["superpanel_id__panel_version"]
</blockquote></details>

done

**Review by corbin-chris — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/76)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
