### PR TITLE
In 353 transcript seed optimise

### PR DESCRIPTION
**Pull request by corbin-chris**
This addresses ticket IN-353.

Changes made to improve the run speed of transcript-seeding:
- Adding a versionless transcript accession column to the parsed MANE file - makes searching for base-matches faster.
- Run bulk TranscriptReleaseTranscript database additions in 1 batch, rather than 1 batch per transcript.
- Adjusting unit tests accordingly

On my laptop, cProfile now shows a total run time of 430 seconds, down from 2000 seconds. Further optimisation is possible but I think we're at the 'diminishing returns' stage, so please advise on whether this total time is more workable now.

Unit tests are passing:
Ran 117 tests in 4.035s

OK

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/65)

### CODE REVIEW

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/65)* status: all files reviewed, 5 unresolved discussions (waiting on @corbin-chris)

___
*[`requests_app/management/commands/_parse_transcript.py` line 564 at r1](https://reviewable.io/reviews/eastgenomics/eris/65#-Nlh6q6H-VMqTK0e63ZH:-Nlh6q6IAzGY6vNeVzCu:b-35w2hc) ([raw file](https://github.com/eastgenomics/eris/blob/74178968dbeadad356b94b6e5c4848cd5ccf9b6a/requests_app/management/commands/_parse_transcript.py#L564)):*
> ```Python
> 
> 
> def _add_transcript_categorisation_to_db(data_dict: dict) -> None:
> ```

type hint what's the dict structure
___
*[`requests_app/management/commands/_parse_transcript.py` line 689 at r1](https://reviewable.io/reviews/eastgenomics/eris/65#-Nlh7OFHAVXa9z12u2vn:-Nlh7OFHAVXa9z12u2vo:b-jel202) ([raw file](https://github.com/eastgenomics/eris/blob/74178968dbeadad356b94b6e5c4848cd5ccf9b6a/requests_app/management/commands/_parse_transcript.py#L689)):*
> ```Python
>     mane_base_match = [d for d in mane_data if d["RefSeq_versionless"] == tx_base]
> 
>     relevant_panels = PanelGene.objects.filter(gene__hgnc_id=hgnc_id)
> ```

I forgot the logic here. Why are we checking for Panel-Gene?
___
*[`requests_app/management/commands/_parse_transcript.py` line 697 at r1](https://reviewable.io/reviews/eastgenomics/eris/65#-Nlh7rYPCdnuA7WdH7kD:-Nlh7rYPCdnuA7WdH7kE:b-d0op7k) ([raw file](https://github.com/eastgenomics/eris/blob/74178968dbeadad356b94b6e5c4848cd5ccf9b6a/requests_app/management/commands/_parse_transcript.py#L697)):*
> ```Python
>             # it's relevant to. If it's not relevant, just skip it. Otherwise throw an error
>             if len(relevant_panels) != 0:
>                 raise ValueError(f"Transcript in MANE more than once: {tx}")
> ```

and why are we only raising error if there is PanelGene?
___
*[`requests_app/management/commands/_parse_transcript.py` line 720 at r1](https://reviewable.io/reviews/eastgenomics/eris/65#-Nlh83XH8ID9rJ4VLEq_:-Nlh83XH8ID9rJ4VLEqa:b1ddpil) ([raw file](https://github.com/eastgenomics/eris/blob/74178968dbeadad356b94b6e5c4848cd5ccf9b6a/requests_app/management/commands/_parse_transcript.py#L720)):*
> ```Python
> 
>     # fall through to here if no exact match - see if there's a versionless match instead
>     elif mane_base_match:
> ```

nice catch. If we have exact match, there's no point doing the rest
___
*[`requests_app/management/commands/_parse_transcript.py` line 1117 at r1](https://reviewable.io/reviews/eastgenomics/eris/65#-NlhAArU7bORW5odZzwS:-NlhAArU7bORW5odZzwT:b-on29xc) ([raw file](https://github.com/eastgenomics/eris/blob/74178968dbeadad356b94b6e5c4848cd5ccf9b6a/requests_app/management/commands/_parse_transcript.py#L1117)):*
> ```Python
>             tx_data_mane_select["transcript"] = tx_data_mane_plus_clinical[
>                 "transcript"
>             ] = tx_data_hgmd["transcript"] = transcript
> ```

it seems like you are making three new dicts and re-populating them with tx and release 
why not just populate the three dicts that are returned by the _transcript_assign_to_source function which already contain their respective data (match_base, match_clinical, clinical)

**Review by corbin-chris — COMMENTED** [review]
Unit tests passing OK.
cProfile gives the total runtime of the transcript step as 501.902 seconds on my laptop (a little over 8 minutes)

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/65#-:-Nm1hHJt6NCnIf7Vnxcv:b-btdxa8)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @JasonLing95)

___
*[`requests_app/management/commands/_parse_transcript.py` line 564 at r1](https://reviewable.io/reviews/eastgenomics/eris/65#-Nlh6q6H-VMqTK0e63ZH:-Nm1Sdje4oC6Kkhl8spW:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/74178968dbeadad356b94b6e5c4848cd5ccf9b6a/requests_app/management/commands/_parse_transcript.py#L564)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

type hint what's the dict structure
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_parse_transcript.py` line 689 at r1](https://reviewable.io/reviews/eastgenomics/eris/65#-Nlh7OFHAVXa9z12u2vn:-Nm1TZ575GcgLvZuwfL8:bn7w23q) ([raw file](https://github.com/eastgenomics/eris/blob/74178968dbeadad356b94b6e5c4848cd5ccf9b6a/requests_app/management/commands/_parse_transcript.py#L689)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

I forgot the logic here. Why are we checking for Panel-Gene?
</blockquote></details>

Done Added an explanatory note - it's because MANE for GRCh37 has a transcript which appears more than once, for some bizarre reason. However the only time it's happened, it was a transcript for a gene that isn't in any of our panels, so I just wrote logic to skip it.
___
*[`requests_app/management/commands/_parse_transcript.py` line 697 at r1](https://reviewable.io/reviews/eastgenomics/eris/65#-Nlh7rYPCdnuA7WdH7kD:-Nm1Txle1DOLK7_RwZKv:bab0qyf) ([raw file](https://github.com/eastgenomics/eris/blob/74178968dbeadad356b94b6e5c4848cd5ccf9b6a/requests_app/management/commands/_parse_transcript.py#L697)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

and why are we only raising error if there is PanelGene?
</blockquote></details>

Done. See above
___
*[`requests_app/management/commands/_parse_transcript.py` line 1117 at r1](https://reviewable.io/reviews/eastgenomics/eris/65#-NlhAArU7bORW5odZzwS:-Nm1_eFw92FKWDYb_n-a:bln1ah9) ([raw file](https://github.com/eastgenomics/eris/blob/74178968dbeadad356b94b6e5c4848cd5ccf9b6a/requests_app/management/commands/_parse_transcript.py#L1117)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

it seems like you are making three new dicts and re-populating them with tx and release 
why not just populate the three dicts that are returned by the _transcript_assign_to_source function which already contain their respective data (match_base, match_clinical, clinical)
</blockquote></details>

Done. Had a dumb moment

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/65)* status: all files reviewed, 3 unresolved discussions (waiting on @corbin-chris)

___
*[`requests_app/management/commands/_parse_transcript.py` line 564 at r2](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm5iuYZAv1GNOyxyKyY:-Nm5iuYZAv1GNOyxyKyZ:b-ckgwj) ([raw file](https://github.com/eastgenomics/eris/blob/e131c55b5a2f4e5251bcd0e5bb28e0f52474b3ae/requests_app/management/commands/_parse_transcript.py#L564)):*
> ```Python
> 
> def _add_transcript_categorisation_to_db(
>     data_dict: dict[str : Transcript | TranscriptRelease | bool],
> ```

this is a list of dict of Transcript | TranscriptRelease | bool
___
*[`requests_app/management/commands/_parse_transcript.py` line 596 at r2](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm5j6zfCEB39VSZYKsd:-Nm5j6zfCEB39VSZYKse:b3elgz9) ([raw file](https://github.com/eastgenomics/eris/blob/e131c55b5a2f4e5251bcd0e5bb28e0f52474b3ae/requests_app/management/commands/_parse_transcript.py#L596)):*
> ```Python
> 
> def _get_clin_transcript_from_hgmd_files(
>     hgnc_id: str, markname: dict, gene2refseq: dict
> ```

same for most functions. we need type-hint for the dict as the :params: in the function comment didn't really state what could the dict be - it will be hard for future developers to pick up
___
*[`requests_app/management/commands/_parse_transcript.py` line 655 at r2](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm5jLVt4XJMHL7bWd8J:-Nm5jLVt4XJMHL7bWd8K:b-6or9rf) ([raw file](https://github.com/eastgenomics/eris/blob/e131c55b5a2f4e5251bcd0e5bb28e0f52474b3ae/requests_app/management/commands/_parse_transcript.py#L655)):*
> ```Python
>     hgnc_id: str,
>     mane_data: list[dict],
>     markname_hgmd: dict,
> ```

type-hint

**Review by corbin-chris — COMMENTED** [review]
Unit tests still passing, transcript-population is running in approx 7-8 minutes

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/65#-:-Nm6kLgNCBCdJPm-sOE0:bzgwuwi)* status: 3 of 10 files reviewed, 3 unresolved discussions (waiting on @JasonLing95)

___
*[`requests_app/management/commands/_parse_transcript.py` line 564 at r2](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm5iuYZAv1GNOyxyKyY:-Nm64-nuARt_rcVLLTJu:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/e131c55b5a2f4e5251bcd0e5bb28e0f52474b3ae/requests_app/management/commands/_parse_transcript.py#L564)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this is a list of dict of Transcript | TranscriptRelease | bool
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_parse_transcript.py` line 596 at r2](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm5j6zfCEB39VSZYKsd:-Nm6_BBc55dRE4kUmt5q:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/e131c55b5a2f4e5251bcd0e5bb28e0f52474b3ae/requests_app/management/commands/_parse_transcript.py#L596)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

same for most functions. we need type-hint for the dict as the :params: in the function comment didn't really state what could the dict be - it will be hard for future developers to pick up
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_parse_transcript.py` line 655 at r2](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm5jLVt4XJMHL7bWd8J:-Nm6_OWK6Jwbjd5Rrc9V:bb6un1j) ([raw file](https://github.com/eastgenomics/eris/blob/e131c55b5a2f4e5251bcd0e5bb28e0f52474b3ae/requests_app/management/commands/_parse_transcript.py#L655)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

type-hint
</blockquote></details>

Done

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/65)* status: 7 of 10 files reviewed, 5 unresolved discussions (waiting on @corbin-chris)

___
*[`requests_app/management/commands/_parse_transcript.py` line 655 at r2](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm5jLVt4XJMHL7bWd8J:-Nm6oc-UBjwAjh-nIfcM:bqqfmxl) ([raw file](https://github.com/eastgenomics/eris/blob/e131c55b5a2f4e5251bcd0e5bb28e0f52474b3ae/requests_app/management/commands/_parse_transcript.py#L655)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Done
</blockquote></details>

dict[str, list[str]]
___
*[`requests_app/management/commands/_parse_transcript.py` line 501 at r4](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm6lZvD-A-2VpH0L3kA:-Nm6lZvE7wIpUHwuwdlw:b-y0av5e) ([raw file](https://github.com/eastgenomics/eris/blob/e6ac01746c452185d5a96a334fc05714495c859f/requests_app/management/commands/_parse_transcript.py#L501)):*
> ```Python
> 
> 
> def _prepare_markname_file(markname_file: str) -> dict[int : list[int]]:
> ```

i think the gene-id is read as string so it should be str: list[str]
___
*[`requests_app/management/commands/_parse_transcript.py` line 594 at r4](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm6lj4SACmYOuOf2SGx:-Nm6lj4SACmYOuOf2SGy:bqqfmxl) ([raw file](https://github.com/eastgenomics/eris/blob/e6ac01746c452185d5a96a334fc05714495c859f/requests_app/management/commands/_parse_transcript.py#L594)):*
> ```Python
> def _get_clin_transcript_from_hgmd_files(
>     hgnc_id: str,
>     markname: dict[int, list[int]],
> ```

dict[str, list[str]]
___
*[`requests_app/management/commands/_parse_transcript.py` line 614 at r4](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm6oD7L6Cgx3iqobkZs:-Nm6oD7L6Cgx3iqobkZt:b-jxga8y) ([raw file](https://github.com/eastgenomics/eris/blob/e6ac01746c452185d5a96a334fc05714495c859f/requests_app/management/commands/_parse_transcript.py#L614)):*
> ```Python
>     # Error states: hgnc id not in markname table / hgmd database,
>     # or hgnc id has more than one entry
>     if int(short_hgnc_id) not in markname:
> ```

if this is not turned into int, it should have error out because markname's key is str. We should make sure that we read all file as str for comparison just so that we don't run into a type mismatch instead
___
*[`requests_app/management/commands/_parse_transcript.py` line 626 at r4](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm6oYGG0xIDO5UzXvnj:-Nm6oYGG0xIDO5UzXvnk:bgto95q) ([raw file](https://github.com/eastgenomics/eris/blob/e6ac01746c452185d5a96a334fc05714495c859f/requests_app/management/commands/_parse_transcript.py#L626)):*
> ```Python
>     try:
>         markname_gene_id = markname[int(short_hgnc_id)][0]
>     except IndexError:
> ```

this error should have been errored out above

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/65)* status: 6 of 10 files reviewed, 5 unresolved discussions (waiting on @JasonLing95)

___
*[`requests_app/management/commands/_parse_transcript.py` line 655 at r2](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm5jLVt4XJMHL7bWd8J:-Nm70EUN3rdnaOO_scDm:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/e131c55b5a2f4e5251bcd0e5bb28e0f52474b3ae/requests_app/management/commands/_parse_transcript.py#L655)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

dict[str, list[str]]
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_parse_transcript.py` line 501 at r4](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm6lZvD-A-2VpH0L3kA:-Nm6udAi6_jSa8Z1k0Qd:b47tdz9) ([raw file](https://github.com/eastgenomics/eris/blob/e6ac01746c452185d5a96a334fc05714495c859f/requests_app/management/commands/_parse_transcript.py#L501)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

i think the gene-id is read as string so it should be str: list[str]
</blockquote></details>

Done
I checked by printing, and it's worse than that, it was actually floats (?!). Pandas default behaviour can be very weird.
```
print([type(k) for k in markname_hgmd.keys()])
```
Printed <class 'float'> for every dictionary's key.

I've fixed it by explicitly converting to a nullable integer in _prepare_markname_file. Corrected the tests too.
___
*[`requests_app/management/commands/_parse_transcript.py` line 594 at r4](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm6lj4SACmYOuOf2SGx:-Nm6zjujBR0ygNHCtzYD:b-3486ea) ([raw file](https://github.com/eastgenomics/eris/blob/e6ac01746c452185d5a96a334fc05714495c859f/requests_app/management/commands/_parse_transcript.py#L594)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

dict[str, list[str]]
</blockquote></details>

Done think this was addressed above
___
*[`requests_app/management/commands/_parse_transcript.py` line 614 at r4](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm6oD7L6Cgx3iqobkZs:-Nm6zvec9h5gn_ty4fER:bkjr1rc) ([raw file](https://github.com/eastgenomics/eris/blob/e6ac01746c452185d5a96a334fc05714495c859f/requests_app/management/commands/_parse_transcript.py#L614)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

if this is not turned into int, it should have error out because markname's key is str. We should make sure that we read all file as str for comparison just so that we don't run into a type mismatch instead
</blockquote></details>

Done made types more explicit instead
___
*[`requests_app/management/commands/_parse_transcript.py` line 626 at r4](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm6oYGG0xIDO5UzXvnj:-Nm7-uLs8VAiwFIlkadU:b-c3c4k9) ([raw file](https://github.com/eastgenomics/eris/blob/e6ac01746c452185d5a96a334fc05714495c859f/requests_app/management/commands/_parse_transcript.py#L626)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this error should have been errored out above
</blockquote></details>

It's possible if there's misformatting in the marknames file - so that there's a blank dictionary for a HGNC ID, instead of the HGNC ID just not being present at all

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/65)* status: 7 of 10 files reviewed, 5 unresolved discussions (waiting on @corbin-chris)

___
*[`requests_app/management/commands/_parse_transcript.py` line 501 at r4](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm6lZvD-A-2VpH0L3kA:-NmAmeXM26XM_CTTlvJY:b-yadwxn) ([raw file](https://github.com/eastgenomics/eris/blob/e6ac01746c452185d5a96a334fc05714495c859f/requests_app/management/commands/_parse_transcript.py#L501)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Done
I checked by printing, and it's worse than that, it was actually floats (?!). Pandas default behaviour can be very weird.
```
print([type(k) for k in markname_hgmd.keys()])
```
Printed <class 'float'> for every dictionary's key.

I've fixed it by explicitly converting to a nullable integer in _prepare_markname_file. Corrected the tests too.
</blockquote></details>

i think it's probably the NaN which makes the whole column perceived as float
___
*[`requests_app/management/commands/_parse_transcript.py` line 614 at r4](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm6oD7L6Cgx3iqobkZs:-NmAmVrz1f8MgMcyqlzH:b93gx0w) ([raw file](https://github.com/eastgenomics/eris/blob/e6ac01746c452185d5a96a334fc05714495c859f/requests_app/management/commands/_parse_transcript.py#L614)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Done made types more explicit instead
</blockquote></details>

check here based on below
___
*[`requests_app/management/commands/_parse_transcript.py` line 626 at r4](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm6oYGG0xIDO5UzXvnj:-NmAm69c1pnfkl9mT0WX:b-r2dqac) ([raw file](https://github.com/eastgenomics/eris/blob/e6ac01746c452185d5a96a334fc05714495c859f/requests_app/management/commands/_parse_transcript.py#L626)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

It's possible if there's misformatting in the marknames file - so that there's a blank dictionary for a HGNC ID, instead of the HGNC ID just not being present at all
</blockquote></details>

but you got already two if conditions above: one checking if short_hgnc is in markname or not - it will error out and another checking if short_hgnc will appear more than once in marknaem - it will error out too. The remaining from the logic above should be short_hgnc only have one instance within markname. 

If this Try clause still error out, something is not right on the upstream logic

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/65)* status: 7 of 10 files reviewed, 5 unresolved discussions (waiting on @JasonLing95)

___
*[`requests_app/management/commands/_parse_transcript.py` line 501 at r4](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm6lZvD-A-2VpH0L3kA:-NmAr7yV1UXteuzcDJNU:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/e6ac01746c452185d5a96a334fc05714495c859f/requests_app/management/commands/_parse_transcript.py#L501)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

i think it's probably the NaN which makes the whole column perceived as float
</blockquote></details>

Done.
___
*[`requests_app/management/commands/_parse_transcript.py` line 614 at r4](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm6oD7L6Cgx3iqobkZs:-NmArHXs97tc0-U6S2fs:beu3lce) ([raw file](https://github.com/eastgenomics/eris/blob/e6ac01746c452185d5a96a334fc05714495c859f/requests_app/management/commands/_parse_transcript.py#L614)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

check here based on below
</blockquote></details>

Done markname's key is not a string, I convert it to nullable int in _prepare_markname_file
___
*[`requests_app/management/commands/_parse_transcript.py` line 626 at r4](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm6oYGG0xIDO5UzXvnj:-NmAntw34u_BBEgXrHyy:b8w9vtb) ([raw file](https://github.com/eastgenomics/eris/blob/e6ac01746c452185d5a96a334fc05714495c859f/requests_app/management/commands/_parse_transcript.py#L626)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

but you got already two if conditions above: one checking if short_hgnc is in markname or not - it will error out and another checking if short_hgnc will appear more than once in marknaem - it will error out too. The remaining from the logic above should be short_hgnc only have one instance within markname. 

If this Try clause still error out, something is not right on the upstream logic
</blockquote></details>

Checking if short\_hgnc is in markname or not, will miss the case when 'short_hgnc' exists in the database, but its value is an empty list, e.g. HGNC_1: []
The try-catch is trying to handle the case that short_hgnc exists but is attached to an empty list.
Please see test\_get\_clin\_transcript\_from\_hgmd\_files.py to see what I mean.

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/65)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @corbin-chris)

___
*[`requests_app/management/commands/_parse_transcript.py` line 626 at r4](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm6oYGG0xIDO5UzXvnj:-NmAyV8L9M9wgtEYQ_21:blze565) ([raw file](https://github.com/eastgenomics/eris/blob/e6ac01746c452185d5a96a334fc05714495c859f/requests_app/management/commands/_parse_transcript.py#L626)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Checking if short\_hgnc is in markname or not, will miss the case when 'short_hgnc' exists in the database, but its value is an empty list, e.g. HGNC_1: []
The try-catch is trying to handle the case that short_hgnc exists but is attached to an empty list.
Please see test\_get\_clin\_transcript\_from\_hgmd\_files.py to see what I mean.
</blockquote></details>

shouldn't this be changed to if not markname[int(short_hgnc)) - basically checking if it's an empty array which might be clearer

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/65)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

___
*[`requests_app/management/commands/_parse_transcript.py` line 626 at r4](https://reviewable.io/reviews/eastgenomics/eris/65#-Nm6oYGG0xIDO5UzXvnj:-NmBFsLF-CAKydFY_F7v:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/e6ac01746c452185d5a96a334fc05714495c859f/requests_app/management/commands/_parse_transcript.py#L626)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

shouldn't this be changed to if not markname[int(short_hgnc)) - basically checking if it's an empty array which might be clearer
</blockquote></details>

Done.

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 1 of 7 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/65)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @corbin-chris)

**Pull request merged**
