### PR TITLE
Unit Test: insert_data_into_db

### PR DESCRIPTION
**Pull request by JasonLing95**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/30)

### CODE REVIEW

**Review by corbin-chris — CHANGES_REQUESTED** [review]
Looks good!
You've not written any unit test scenarios where a region is added, or where a gene is backwards-deactivated. Could you please add a couple basic ones? The aim of this would be just to make sure that '_insert_regions' and '_backward_deactivate_panel_gene'  are **called** at the correct time - both of these functions have or will have their own tests, so you don't need to write loads.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/30#-:-NfHDdRz-1GlDP2Ydn6Z:bsolagu)* status: all files reviewed, 2 unresolved discussions (waiting on @JasonLing95)

___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_data_into_db.py` line 28 at r1](https://reviewable.io/reviews/eastgenomics/eris/30#-NfH8BFv2-7-u21dEL55:-NfH8BFv2-7-u21dEL56:b9kxzl0) ([raw file](https://github.com/eastgenomics/eris/blob/cd828a84a33cdc3ad93b89c8ff08c206ec21adff/tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_data_into_db.py#L28)):*
> ```Python
>         """
>         Start condition: Make a Panel, which we will link to genes as part of testing
>         _insert_gene
> ```

You need to change '_insert_gene' to 'insert_data_into_mock_db' in the docstring here - beware of the copy-pastes :) 
___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_data_into_db.py` line 55 at r1](https://reviewable.io/reviews/eastgenomics/eris/30#-NfH9uH-5WTirGSpSGIK:-NfH9uH-5WTirGSpSGIL:b-wod9oz) ([raw file](https://github.com/eastgenomics/eris/blob/cd828a84a33cdc3ad93b89c8ff08c206ec21adff/tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_data_into_db.py#L55)):*
> ```Python
>     ):
>         """
>         test that the core function of `insert_data_to_db` works - insert panel + their metadata
> ```

I'd prefer a little more specific detail here to make it easier to pick out which test does which, e.g.:
'test that the code function of 'insert_data_to_db works, for a scenario where a panel with a new external ID is added - the new panel will be added to the database, plus metadata including a new gene, and a new gene-panel link'

Your description for 'test_that_previous_clinical_indication_panel_is_flagged_when_panel_version_change' was very good, something like that would work.

**Review by JasonLing95 — COMMENTED** [review]
I am thinking backward deactivation is dealt with by `insert_gene` function and regions are dealt with by `insert_region` function those scenario should be tested there instead.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/30#-:-NfI1Kq5EssmwdOqAPph:bscwug7)* status: all files reviewed, 2 unresolved discussions (waiting on @corbin-chris)

___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_data_into_db.py` line 28 at r1](https://reviewable.io/reviews/eastgenomics/eris/30#-NfH8BFv2-7-u21dEL55:-NfI1esEAgNk7wuQdI8Z:bvnrpcm) ([raw file](https://github.com/eastgenomics/eris/blob/cd828a84a33cdc3ad93b89c8ff08c206ec21adff/tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_data_into_db.py#L28)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

You need to change '_insert_gene' to 'insert_data_into_mock_db' in the docstring here - beware of the copy-pastes :)
</blockquote></details>

updated
___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_data_into_db.py` line 55 at r1](https://reviewable.io/reviews/eastgenomics/eris/30#-NfH9uH-5WTirGSpSGIK:-NfI1wEPB79_qtXjozK_:bvnrpcm) ([raw file](https://github.com/eastgenomics/eris/blob/cd828a84a33cdc3ad93b89c8ff08c206ec21adff/tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_data_into_db.py#L55)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I'd prefer a little more specific detail here to make it easier to pick out which test does which, e.g.:
'test that the code function of 'insert_data_to_db works, for a scenario where a panel with a new external ID is added - the new panel will be added to the database, plus metadata including a new gene, and a new gene-panel link'

Your description for 'test_that_previous_clinical_indication_panel_is_flagged_when_panel_version_change' was very good, something like that would work.
</blockquote></details>

updated

**Review by corbin-chris — COMMENTED** [review]
You're right about insert_gene, sorry. Note that if you changed insert_gene more recently than 2 weeks ago, you might need to add tests for insert_gene which cover backwards-deactivation (you may have this on a different branch or ticket already).

I know that insert_region has its own tests. So I understand that on the one hand, we don't want to write redundant code. But on the other hand, for complete test coverage of _backward_deactivate_panel_gene, you need to test that every line inside the test is actually called at least once in one of your tests. This is to make sure insert_region is not skipped, or passed incorrect (e.g. wrong type, data structure, e.t.c.) or incomplete parameters, or any of the other brain-fart things that can happen when you write a lot of code quickly.

Doc strings looking better now, thanks.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/30#-:-NfKmbDJ4lwNBjWRtO0o:b-swcgyt)* status: all files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

**Review by JasonLing95 — COMMENTED** [review]
I've added mock region in the mock PanelApp API and check if the newly inserted panel is linked to the region. 
_backward_deactivation function has been removed because it is doing the same thing as being done in `insert_gene`
I've assigned you on another PR on unit testing: insert_gene which have scenario related to backward deactivation of panel-gene interaction

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/30#-:-NfKw_N7BgbCrRmfvE5d:bym4jpk)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @corbin-chris)

**Review by corbin-chris — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
