### PR TITLE
GenePanels, Gene, Review

### PR DESCRIPTION
**Pull request by JasonLing95**
- more frontend stuff
- added "pending" on models for review purpose (logic need more work for other relationship)
- added page to view genepanel (but the logic for it is not done yet)
- added page to view gene and its associated panels etc.
- added a page "pending" to view links that require manual review

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/7)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/7)* status: 10 of 11 files reviewed, 10 unresolved discussions (waiting on @JasonLing95 and @Yu-jinKim)

___
*[`web/views.py` line 46 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavJwsd7y1f4tjCRe_a:-NavJwsd7y1f4tjCRe_b:bggq5vn) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L46)):*
> ```Python
>                 rnas.add(row["HGNC ID"])
> 
>     return rnas
> ```

this is the same as here is it not?

https://github.com/eastgenomics/eris/blob/86ed079c7fb5e723afbaad1064743e52a3639f4c/requests_app/management/commands/generate.py#L58-L76



_Code quote:_
```Python
def _parse_hgnc(file_path: str) -> set:
    """
    Function to parse hgnc file and return a set of rna hgnc ids
    """
    rnas = set()

    with open(file_path, "r") as f:
        for row in csv.DictReader(f, delimiter="\t"):
            if re.search("rna", row["Locus type"], re.IGNORECASE) or re.search(
                "mitochondrially encoded",
                row["Approved name"],
                re.IGNORECASE,
            ):
                rnas.add(row["HGNC ID"])

    return rnas
```
___
*[`web/views.py` line 730 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavLxhxD32RlPRb6L4R:-NavLxhxD32RlPRb6L4S:b-syr808) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L730)):*
> ```Python
> 
> 
> def review(request):
> ```

missing doc string



_Code quote:_
```Python
def review(request):
```
___
*[`web/views.py` line 735 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavKiXDEgvBIMIFWrHq:-NavKiXDEgvBIMIFWrHr:b-fskxrm) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L735)):*
> ```Python
>     for panel in panels:
>         if panel.panel_version:
>             panel.panel_version = normalize_version(panel.panel_version)
> ```

can be a list comp:
```
panels = [
    normalize_version(panel.version) if panel.version else panel.version
    for panel in panels
]
```



_Code quote:_
```Python
    # normalize panel version
    for panel in panels:
        if panel.panel_version:
            panel.panel_version = normalize_version(panel.panel_version)
```
___
*[`web/views.py` line 741 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavLBWy3GqPLnW1GnLi:-NavLBWy3GqPLnW1GnLj:b-kdw3kt) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L741)):*
> ```Python
>     ).all()
> 
>     cips: QuerySet[ClinicalIndicationPanel] = ClinicalIndicationPanel.objects.filter(
> ```

can these var names be more descriptive than abbreviations as sometimes they can mean other things (i.e. `cis` can also mean same and `cip` in the context of Genomics England is their Clinical Indication Portal (which is confusing when thinking about panelapp too). I think something just like `indications` for cis and `indication_panels` for cip is clearer



_Code quote:_
```Python
cips:
```
___
*[`web/views.py` line 755 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavL5Gi0Fc4gVQ8q9Ez:-NavL5Gj7YobaORxNB4F:b-py5k77) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L755)):*
> ```Python
>             cip["panel_id__panel_version"] = normalize_version(
>                 cip["panel_id__panel_version"]
>             )
> ```

same as above, can be a list comp



_Code quote:_
```Python
    for cip in cips:
        if cip["panel_id__panel_version"]:
            cip["panel_id__panel_version"] = normalize_version(
                cip["panel_id__panel_version"]
            )
```
___
*[`web/views.py` line 776 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavM4jY8SLjpoapSMke:-NavM4jY8SLjpoapSMkf:b-hmyme6) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L776)):*
> ```Python
> 
> 
> def gene(request, gene_id: int):
> ```

stringdoc



_Code quote:_
```Python
def gene(request, gene_id: int):
```
___
*[`web/views.py` line 806 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavM9KiE4qd9CAjtipt:-NavM9KiE4qd9CAjtipu:bnb4o0s) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L806)):*
> ```Python
> def genepanel(request):
>     # TODO: hard-coded
>     rnas = _parse_hgnc("testing_files/hgnc_dump_20230606_1.txt")
> ```

does this want to be an arg? also docstring



_Code quote:_
```Python
    # TODO: hard-coded
    rnas = _parse_hgnc("testing_files/hgnc_dump_20230606_1.txt")
```
___
*[`web/views.py` line 850 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavMhqjACe6mQdmzbi_:-NavMhqjACe6mQdmzbia:b-9uc3y3) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L850)):*
> ```Python
>             for hgnc in panel_genes[panel_id]:
>                 # for each gene associated with that panel
>                 if hgnc in ["HGNC:12029", "HGNC:5541"] or hgnc in rnas:
> ```

is this the same as we previously discussed? why does it need the same here as it shouldn't be in the database, right?



_Code quote:_
```Python
 ["HGNC:12029", "HGNC:5541"]
```
___
*[`web/views.py` line 861 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavN2iI-VMxJcWBBCQ9:-NavN2iI-VMxJcWBBCQA:b-e30zzf) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L861)):*
> ```Python
>                 )
> 
>     sorted(results, key=lambda x: [x[0], x[1], x[2]])
> ```

`sorted()` doesn't modify the variable in place, did you mean to assign this back?



_Code quote:_
```Python
sorted(results, key=lambda x: [x[0], x[1], x[2]])
```
___
*[`web/views.py` line 868 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavNLWP9VAC6T9oNVWJ:-NavNLWQ1SOEtfjjVLgR:b-mvijmp) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L868)):*
> ```Python
>     ci_panel_to_gene = collections.defaultdict(list)
>     for gp in results:
>         ci_panel_to_gene[f"{gp[0]}_{gp[1]}"].append(gp[2])
> ```

can you add more to this comment, what is in gp / results?

also can this be turn into a dict comprehension or can the key from the first 2 parts of gp be created more than once?



_Code quote:_
```Python
    # processing for display in frontend
    ci_panel_to_gene = collections.defaultdict(list)
    for gp in results:
        ci_panel_to_gene[f"{gp[0]}_{gp[1]}"].append(gp[2])
```

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/7)* status: 10 of 11 files reviewed, 10 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`web/views.py` line 46 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavJwsd7y1f4tjCRe_a:-Navh63S8gq-TTKiRpLN:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L46)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this is the same as here is it not?

https://github.com/eastgenomics/eris/blob/86ed079c7fb5e723afbaad1064743e52a3639f4c/requests_app/management/commands/generate.py#L58-L76
</blockquote></details>

done
___
*[`web/views.py` line 730 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavLxhxD32RlPRb6L4R:-NavhcIAAD4hbQQICBLw:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L730)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

missing doc string
</blockquote></details>

done
___
*[`web/views.py` line 735 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavKiXDEgvBIMIFWrHq:-NavhcwM-ilyzv5ywl-1:blma29t) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L735)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can be a list comp:
```
panels = [
    normalize_version(panel.version) if panel.version else panel.version
    for panel in panels
]
```
</blockquote></details>

this will make panels into a list of panel.version rather than panel objects
___
*[`web/views.py` line 741 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavLBWy3GqPLnW1GnLi:-Navi7WmDBS_nCpD0RpO:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L741)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can these var names be more descriptive than abbreviations as sometimes they can mean other things (i.e. `cis` can also mean same and `cip` in the context of Genomics England is their Clinical Indication Portal (which is confusing when thinking about panelapp too). I think something just like `indications` for cis and `indication_panels` for cip is clearer
</blockquote></details>

done
___
*[`web/views.py` line 755 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavL5Gi0Fc4gVQ8q9Ez:-Navi8A85qHG13ZADam5:bj7q64b) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L755)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

same as above, can be a list comp
</blockquote></details>

will make it into list of panel versions rather than panel objects
___
*[`web/views.py` line 806 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavM9KiE4qd9CAjtipt:-NaviX5kCr_leGdULTZ9:bi936ze) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L806)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

does this want to be an arg? also docstring
</blockquote></details>

not yet. in the future will require an upload (an arg) rather than a hard-coded one. But now can't be bothered with the upload function in the front-end
___
*[`web/views.py` line 850 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavMhqjACe6mQdmzbi_:-NaviexO1mdRmn0dG4Ii:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L850)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this the same as we previously discussed? why does it need the same here as it shouldn't be in the database, right?
</blockquote></details>

done
___
*[`web/views.py` line 861 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavN2iI-VMxJcWBBCQ9:-NavipT4523aXzIBfX1d:bh4ilnz) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L861)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`sorted()` doesn't modify the variable in place, did you mean to assign this back?
</blockquote></details>

assigned to itself again
___
*[`web/views.py` line 868 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavNLWP9VAC6T9oNVWJ:-Navj2DY9WpCopnVCWo8:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L868)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you add more to this comment, what is in gp / results?

also can this be turn into a dict comprehension or can the key from the first 2 parts of gp be created more than once?
</blockquote></details>

done

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/7)* status: 10 of 11 files reviewed, 10 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`web/views.py` line 776 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavM4jY8SLjpoapSMke:-NavjQzw29ZygT77Svll:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L776)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

stringdoc
</blockquote></details>

done

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/7)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @JasonLing95 and @Yu-jinKim)

___
*[`web/views.py` line 46 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavJwsd7y1f4tjCRe_a:-Naw1FtHDC4aP1Mv0Go0:b-uk94mk) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L46)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

done
</blockquote></details>

can this function go into utils since its the same as the other and import it?

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/7)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @Yu-jinKim)

___
*[`web/views.py` line 46 at r1](https://reviewable.io/reviews/eastgenomics/eris/7#-NavJwsd7y1f4tjCRe_a:-Nazdne95mZNiMSUbs_E:bb7f2mf) ([raw file](https://github.com/eastgenomics/eris/blob/56e29f490e93785c8b005f41a3f5d9f7de4c92ef/web/views.py#L46)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can this function go into utils since its the same as the other and import it?
</blockquote></details>

done

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/7)* status: all files reviewed, 2 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`web/views.py` line 169 at r3](https://reviewable.io/reviews/eastgenomics/eris/7#-Nazv2M39-5QZnoYbcND:-Nazv2M39-5QZnoYbcNE:b32011a) ([raw file](https://github.com/eastgenomics/eris/blob/a70b7c08cb56fdd8f369e33e681c0d5ebfd02cb6/web/views.py#L169)):*
> ```Python
>             "config_source",
>             "td_version",
>             "created_date",
> ```

didn't you combine the created fields?

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/7)* status: all files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/7)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @Yu-jinKim)

___
*[`web/views.py` line 169 at r3](https://reviewable.io/reviews/eastgenomics/eris/7#-Nazv2M39-5QZnoYbcND:-Nb-AbRW2jPse8PryUQG:b-mpojf2) ([raw file](https://github.com/eastgenomics/eris/blob/a70b7c08cb56fdd8f369e33e681c0d5ebfd02cb6/web/views.py#L169)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

didn't you combine the created fields?
</blockquote></details>

oh ya, this would have cause a problem down the line. good spot

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/7)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @Yu-jinKim)

___
*[`web/views.py` line 169 at r3](https://reviewable.io/reviews/eastgenomics/eris/7#-Nazv2M39-5QZnoYbcND:-Nb-B93e8EykAL9viySm:bvnrpcm) ([raw file](https://github.com/eastgenomics/eris/blob/a70b7c08cb56fdd8f369e33e681c0d5ebfd02cb6/web/views.py#L169)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

oh ya, this would have cause a problem down the line. good spot
</blockquote></details>

updated

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
