### PR TITLE
Vdb helper function tests

### PR DESCRIPTION
**Pull request by spaul91**
Helper function unit tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/88)

### CODE REVIEW

**Comment by spaul91** [comment]
```
pauls4@pauls4-ThinkPad-T590:~/workspace/development/eris$ python manage.py test .
Found 154 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..........................Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: True
Data insertion completed.
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
Data insertion completed.
.Inserting test directory data into database... forced: False
................................For panel Acute rhabdomyolyosis, skipping gene without confidence information: acyl-CoA dehydrogenase family member 9
.For panel Acute rhabdomyolyosis, skipping gene without confidence information: acyl-CoA dehydrogenase family member 9
..For panel Acute rhabdomyolyosis, skipping gene without HGNC ID: acyl-CoA dehydrogenase family member 9
...........Aborting because API returned a non-200 exit code: 500
......................Start 2 gene bulk create: 12:31:02
.Linking 1 unchanged genes to new HGNC release vversion2
.Linking 3 unchanged genes to new HGNC release vversion2
.....Preparing HGNC files
Start bulk-updating 2 gene symbols: 12:31:02
Linking 0 unchanged genes to new HGNC release v1.0
Start 13 gene bulk create: 12:31:02
.Preparing HGNC files
Start bulk-updating 2 gene symbols: 12:31:03
Linking 0 unchanged genes to new HGNC release v1.0
Start 13 gene bulk create: 12:31:03
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 12:31:03
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 12:31:03
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 12:31:03
.Preparing HGNC files
Linking 0 unchanged genes to new HGNC release v1.0
Start 15 gene bulk create: 12:31:03
...................Start bulk-updating 1 gene symbols: 12:31:03
.Start bulk-updating 2 gene symbols: 12:31:03
................
----------------------------------------------------------------------
Ran 154 tests in 8.795s

OK
Destroying test database for alias 'default'...
```

**Review by corbin-chris — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/88)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @spaul91)

___
*[`tests/test_variant_db/test_management/test_commands/test_insert/test_insert_helpers.py` line 5 at r2](https://reviewable.io/reviews/eastgenomics/eris/88#-Nq3-uw02yjY8jrovtFR:-Nq3-uw16FP-YindbjTH:bh5kufu) ([raw file](https://github.com/eastgenomics/eris/blob/5a18ba64a449bf799240167d8ee3ffac7ba78709/tests/test_variant_db/test_management/test_commands/test_insert/test_insert_helpers.py#L5)):*
> ```Python
> 
> class TestInsertHelperFunctions(TestCase):
>     def test_rename_key(self):
> ```

I'd like docstrings for every test in this general sort of format, please. Although we like to make our usual code as non-repetitive as possible, unit tests tend to have an even higher value placed on readability, even if it means writing a lot of comments. Bear in mind your tests will end up being run by future devs who are making extra features and who aren't knowledgable of the 'core' codebase, so they need extra support to interpret tests:
"""
CASE: What the test is doing.
EXPECT: What you think should happen if the test passes
"""
So for this example, it would be something like this:
"""
CASE: _rename_key is run on a dictionary containing two key/value pairs.
EXPECT:  Only the specified key is renamed. The other key remains unchanged.
"""
___
*[`tests/test_variant_db/test_management/test_commands/test_insert/test_insert_helpers.py` line 10 at r2](https://reviewable.io/reviews/eastgenomics/eris/88#-Nq30wqs2AeRJmag-NGe:-Nq30wqs2AeRJmag-NGf:b-3lrmcw) ([raw file](https://github.com/eastgenomics/eris/blob/5a18ba64a449bf799240167d8ee3ffac7ba78709/tests/test_variant_db/test_management/test_commands/test_insert/test_insert_helpers.py#L10)):*
> ```Python
>         self.assertDictEqual(test_output, {"renamed_first_key": 1, "second_key": 2})
>     
>     def test_subset_row(self):
> ```

Example docstring for test_subset_row:
"""
CASE: _subset_row is run twice on a dictionary, in each case, specifying a different set of keys to parse out.
EXPECT: Each _subset_row returns a dictionary which retains only the specified keys.
"""
___
*[`tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py` line 20 at r2](https://reviewable.io/reviews/eastgenomics/eris/88#-Nq330D05bDWjRMTVIhy:-Nq330D05bDWjRMTVIhz:b-e8uv9c) ([raw file](https://github.com/eastgenomics/eris/blob/5a18ba64a449bf799240167d8ee3ffac7ba78709/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py#L20)):*
> ```Python
>         self.assertEqual(_convert_name_to_lowercase("PIZZA_evidence"), "PIZZA_evidence")
>     
>     def test_replace_with_underscores(self):
> ```

You can also test some other character types here, to demonstrate the edges of '_replace_with_underscores' scope. I like to do this with regex things because I find it an easy thing to get unexpected behaviour on.
For example, we'd expect a column header made of special characters ending in ID, e.g. literal '$%*ID', to fail the 'if re.search' string, and end up getting returned with no underscore before its ID.
The test for that would be something like:
self.assertEqual(_replace_with_underscores("$%*ID"), "$%*ID")
___
*[`tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py` line 26 at r2](https://reviewable.io/reviews/eastgenomics/eris/88#-Nq357T38uMSvbLTMX6o:-Nq357T38uMSvbLTMX6p:b-txev9) ([raw file](https://github.com/eastgenomics/eris/blob/5a18ba64a449bf799240167d8ee3ffac7ba78709/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py#L26)):*
> ```Python
>     
>     def test_rename_acgs_column(self):
>         self.assertEqual(_rename_acgs_column("PS1"), "PS1_verdict")
> ```

As for _replace_with_underscores, you're using regex - I'd maybe add checks for 1 or 2 of the other criteria, ones which don't look similar to PS1, to check you've caught everything.

**Review by corbin-chris — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/88)* status: all files reviewed, 4 unresolved discussions (waiting on @spaul91)

**Comment by spaul91** [comment]
*[`tests/test_variant_db/test_management/test_commands/test_insert/test_insert_helpers.py` line 5 at r2](https://reviewable.io/reviews/eastgenomics/eris/88#-Nq3-uw02yjY8jrovtFR:-Nq7ZuZO2T5ZIsQJWTHu:bvt7zhv) ([raw file](https://github.com/eastgenomics/eris/blob/c54e43b97adc7f929b3c20887efa4a605ed110cd/tests/test_variant_db/test_management/test_commands/test_insert/test_insert_helpers.py#L5)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I'd like docstrings for every test in this general sort of format, please. Although we like to make our usual code as non-repetitive as possible, unit tests tend to have an even higher value placed on readability, even if it means writing a lot of comments. Bear in mind your tests will end up being run by future devs who are making extra features and who aren't knowledgable of the 'core' codebase, so they need extra support to interpret tests:
"""
CASE: What the test is doing.
EXPECT: What you think should happen if the test passes
"""
So for this example, it would be something like this:
"""
CASE: _rename_key is run on a dictionary containing two key/value pairs.
EXPECT:  Only the specified key is renamed. The other key remains unchanged.
"""
</blockquote></details>

That's true, I saw the way you'd written your docstrings and I think mine should be more informative. Will update

**Comment by spaul91** [comment]
*[`tests/test_variant_db/test_management/test_commands/test_insert/test_insert_helpers.py` line 5 at r2](https://reviewable.io/reviews/eastgenomics/eris/88#-Nq3-uw02yjY8jrovtFR:-Nq8H8DhELmdpRP-Q2uf:bb6tyiv) ([raw file](https://github.com/eastgenomics/eris/blob/c54e43b97adc7f929b3c20887efa4a605ed110cd/tests/test_variant_db/test_management/test_commands/test_insert/test_insert_helpers.py#L5)):*
<details><summary><i>Previously, spaul91 (Sophie Paul) wrote…</i></summary><blockquote>

That's true, I saw the way you'd written your docstrings and I think mine should be more informative. Will update
</blockquote></details>

DONE

**Comment by spaul91** [comment]
*[`tests/test_variant_db/test_management/test_commands/test_insert/test_insert_helpers.py` line 10 at r2](https://reviewable.io/reviews/eastgenomics/eris/88#-Nq30wqs2AeRJmag-NGe:-Nq8HC-B3BMQB_Uxj_B7:bb6un1j) ([raw file](https://github.com/eastgenomics/eris/blob/c54e43b97adc7f929b3c20887efa4a605ed110cd/tests/test_variant_db/test_management/test_commands/test_insert/test_insert_helpers.py#L10)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Example docstring for test_subset_row:
"""
CASE: _subset_row is run twice on a dictionary, in each case, specifying a different set of keys to parse out.
EXPECT: Each _subset_row returns a dictionary which retains only the specified keys.
"""
</blockquote></details>

Done

**Review by spaul91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/88)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @corbin-chris)

___
*[`tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py` line 20 at r2](https://reviewable.io/reviews/eastgenomics/eris/88#-Nq330D05bDWjRMTVIhy:-Nq8HpMe1_FnGTYb2e9j:b-896fix) ([raw file](https://github.com/eastgenomics/eris/blob/c54e43b97adc7f929b3c20887efa4a605ed110cd/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py#L20)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

You can also test some other character types here, to demonstrate the edges of '_replace_with_underscores' scope. I like to do this with regex things because I find it an easy thing to get unexpected behaviour on.
For example, we'd expect a column header made of special characters ending in ID, e.g. literal '$%*ID', to fail the 'if re.search' string, and end up getting returned with no underscore before its ID.
The test for that would be something like:
self.assertEqual(_replace_with_underscores("$%*ID"), "$%*ID")
</blockquote></details>

Done.
___
*[`tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py` line 26 at r2](https://reviewable.io/reviews/eastgenomics/eris/88#-Nq357T38uMSvbLTMX6o:-Nq8HvSl4NHzm9P3Vp4f:b3tubw7) ([raw file](https://github.com/eastgenomics/eris/blob/c54e43b97adc7f929b3c20887efa4a605ed110cd/tests/test_variant_db/test_management/test_commands/test_workbook/test_workbook_helper_functions.py#L26)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

As for _replace_with_underscores, you're using regex - I'd maybe add checks for 1 or 2 of the other criteria, ones which don't look similar to PS1, to check you've caught everything.
</blockquote></details>

Unsure what this means. I'd be grateful if you could put these tests in and push to this branch if it's immediately obvious to you what needs to be done.

**Review by corbin-chris — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/88)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @spaul91)

**Pull request merged**
