### PR TITLE
Unit Test: insert_gene

### PR DESCRIPTION
**Pull request by JasonLing95**
- fix some logic error in `insert_gene` when doing unit testing
- add a new template to `History()` for when panel-gene get flagged
- main changes in `test_insert_gene` to test the function `insert_gene`

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eris/26)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/26)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_gene.py` line 115 at r1](https://reviewable.io/reviews/eastgenomics/eris/26#-NfB00nB5Gxs6ZE-47VL:-NfB00nB5Gxs6ZE-47VM:boa2vfd) ([raw file](https://github.com/eastgenomics/eris/blob/7930f685bdc64075b19a1b66e3296787502aa2fe/tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_gene.py#L115)):*
> ```Python
>         assert new_gene.hgnc_id == "21497"
>         assert new_gene.gene_symbol == "ACAD9"
>         assert new_gene.alias_symbols == "NPD002,MGC14452"
> ```

where you're doing multiple asserts inside of one test, I prefer to build these to a list of errors and check none are present. That way you can catch them all in one go and not raise an error on the first, which might result in you fixing it for the first error, running tests again and then just hitting the next assert, minimal example here: https://github.com/eastgenomics/dias_batch_running/blob/a4dda8702e4d7ed28acd86ec2d4ef7d8aa4664df/resources/home/dnanexus/dias_batch/tests/test_utils.py#L278



_Code quote:_
```Python
        # assert the inserted gene should have above gene metadata
        new_gene = new_genes[0]
        assert new_gene.hgnc_id == "21497"
        assert new_gene.gene_symbol == "ACAD9"
        assert new_gene.alias_symbols == "NPD002,MGC14452"
```

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/26)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @corbin-chris and @jethror1)

___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_gene.py` line 115 at r1](https://reviewable.io/reviews/eastgenomics/eris/26#-NfB00nB5Gxs6ZE-47VL:-NfBHpHw3UxbGMuenbXI:b-7i18qi) ([raw file](https://github.com/eastgenomics/eris/blob/7930f685bdc64075b19a1b66e3296787502aa2fe/tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_gene.py#L115)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

where you're doing multiple asserts inside of one test, I prefer to build these to a list of errors and check none are present. That way you can catch them all in one go and not raise an error on the first, which might result in you fixing it for the first error, running tests again and then just hitting the next assert, minimal example here: https://github.com/eastgenomics/dias_batch_running/blob/a4dda8702e4d7ed28acd86ec2d4ef7d8aa4664df/resources/home/dnanexus/dias_batch/tests/test_utils.py#L278
</blockquote></details>

updated all to go into list and `assert no errors` at the end of each function

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/26)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @corbin-chris and @JasonLing95)

___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_gene.py` line 115 at r1](https://reviewable.io/reviews/eastgenomics/eris/26#-NfB00nB5Gxs6ZE-47VL:-NfBLvk10WXO9K2g0gXo:b-ty53bl) ([raw file](https://github.com/eastgenomics/eris/blob/7930f685bdc64075b19a1b66e3296787502aa2fe/tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_gene.py#L115)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

updated all to go into list and `assert no errors` at the end of each function
</blockquote></details>

I would keep the gathering and raising of errors within the scope of the single test and not the whole class, as then when you run the tests you know which test it is that the error is coming from and how many have failed

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/26)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @corbin-chris and @jethror1)

___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_gene.py` line 115 at r1](https://reviewable.io/reviews/eastgenomics/eris/26#-NfB00nB5Gxs6ZE-47VL:-NfB_tLi9wAbFqhFS9ma:b-e21ndf) ([raw file](https://github.com/eastgenomics/eris/blob/7930f685bdc64075b19a1b66e3296787502aa2fe/tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_gene.py#L115)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I would keep the gathering and raising of errors within the scope of the single test and not the whole class, as then when you run the tests you know which test it is that the error is coming from and how many have failed
</blockquote></details>

changed to within function scope

**Review by corbin-chris — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/26)* status: all files reviewed, 2 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_gene.py` line 115 at r1](https://reviewable.io/reviews/eastgenomics/eris/26#-NfB00nB5Gxs6ZE-47VL:-NfBQdNSBgW4OTn5QVjs:ba808j1) ([raw file](https://github.com/eastgenomics/eris/blob/7930f685bdc64075b19a1b66e3296787502aa2fe/tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_gene.py#L115)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

changed to within function scope
</blockquote></details>

Agreed with Jethro - I tried class-wide error gathering before, and although it seems more sensible (because per-function gathering seems redundant), it actually makes interpreting pin-pointing failures much harder if your code breaks in future.
___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_gene.py` line 214 at r2](https://reviewable.io/reviews/eastgenomics/eris/26#-NfBRXE08wGy80eJt65Y:-NfBRXE08wGy80eJt65Z:bcv1383) ([raw file](https://github.com/eastgenomics/eris/blob/770961949227d2ddf271379607c994c06d093f77/tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_gene.py#L214)):*
> ```Python
>         new_history = PanelGeneHistory.objects.all()
>         if not len(new_history) == 1:
>             self.errors.append("There should only be one history record")
> ```

I wrote wrapper scripts (len_check_wrapper and value_check_wrapper) which return boring boilerplate text that can be appended straight to the errors list, so we wouldn't have to copy-paste variations on 'There should only be one x' over and over again for every assert in the unit tests. I'm using them in my unit tests for the transcripts, so you're writing redundant code just to avoid them. Can you please put them back?
You don't need to write unique error messages to Ctrl+F them - you can get the line number from the error traceback, and get the location that way.

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/26)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @corbin-chris and @jethror1)

___
*[`tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_gene.py` line 214 at r2](https://reviewable.io/reviews/eastgenomics/eris/26#-NfBRXE08wGy80eJt65Y:-NfL3uPC7K5GHnSU4HU4:bvnrpcm) ([raw file](https://github.com/eastgenomics/eris/blob/770961949227d2ddf271379607c994c06d093f77/tests/tests_requests_app/test_management/test_commands/test_insert_panel/test_insert_gene.py#L214)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I wrote wrapper scripts (len_check_wrapper and value_check_wrapper) which return boring boilerplate text that can be appended straight to the errors list, so we wouldn't have to copy-paste variations on 'There should only be one x' over and over again for every assert in the unit tests. I'm using them in my unit tests for the transcripts, so you're writing redundant code just to avoid them. Can you please put them back?
You don't need to write unique error messages to Ctrl+F them - you can get the line number from the error traceback, and get the location that way.
</blockquote></details>

updated

**Review by corbin-chris — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/26)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eris/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
